/**
 * Level 1 — Úplný začátečník, lessons 1–7: the board and every piece (docs/phase-21-plan.md,
 * curriculum). Checked by `npm run check:lessons`: FENs, accepted moves (complete),
 * collect limits, text lint. Texts: informal „ty“, short sentences, one idea per step,
 * Czech piece names; a piece's first mention uses the `{piece}` placeholder so the child
 * also hears how it looks in their animal set (text.ts).
 */
import type { Lesson } from './types';

const EMPTY = '8/8/8/8/8/8/8/8 w - - 0 1';

export const LEVEL1: readonly Lesson[] = [
  {
    id: 'l1-sachovnice',
    level: 1,
    number: 1,
    title: 'Šachovnice a cíl hry',
    steps: [
      {
        id: 'board',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        text: 'Ahoj! Tohle je šachovnice. Má 64 polí. Světlá a tmavá pole se pořád střídají.',
      },
      {
        id: 'h1',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'h1', brush: 'green' }],
        text: 'Šachovnici vždycky polož tak, aby vpravo dole bylo světlé pole. Pamatuj si: bílé pole vpravo dole.',
      },
      {
        id: 'names',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        shapes: [
          { from: 'a1', to: 'h1', brush: 'blue' },
          { from: 'a1', to: 'a8', brush: 'blue' },
        ],
        text: 'Sloupce mají písmena od a do h. Řady mají čísla od 1 do 8.',
      },
      {
        id: 'e4',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'e4', brush: 'green' }],
        text: 'Každé pole má jméno. Nejdřív písmeno sloupce, potom číslo řady. Tohle pole se jmenuje e4.',
      },
      {
        id: 'name-it',
        kind: 'choose',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'd5', brush: 'green' }],
        text: 'Jak se jmenuje označené pole?',
        options: [
          { id: 'e5', label: 'e5' },
          { id: 'd5', label: 'd5' },
          { id: 'd4', label: 'd4' },
        ],
        correct: ['d5'],
        explain: 'Ano! Sloupec d, řada 5. To je pole d5.',
        wrongExplain: {
          e5: 'Řada 5 sedí. Ale podívej se ještě jednou na písmeno sloupce.',
          d4: 'Sloupec d sedí. Ale podívej se ještě jednou na číslo řady.',
        },
        wrongDefault: 'Písmeno najdeš dole pod sloupcem. Číslo najdeš vlevo vedle řady.',
      },
      {
        id: 'find-it',
        kind: 'choose',
        fen: EMPTY,
        diagram: true,
        text: 'Teď najdi pole f3. Klikni na něj.',
        options: [
          { id: 'f6', square: 'f6' },
          { id: 'c3', square: 'c3' },
          { id: 'f3', square: 'f3' },
        ],
        correct: ['f3'],
        explain: 'Přesně tak, tohle je f3!',
        wrongExplain: {
          f6: 'Tohle je f6. Sloupec sedí, ale řada 3 je níž.',
          c3: 'Tohle je c3. Řada sedí, ale sloupec f je víc vpravo.',
        },
        wrongDefault: 'Najdi nejdřív sloupec f. Potom v něm řadu 3.',
      },
      {
        id: 'goal',
        kind: 'show',
        fen: '7k/6Q1/6K1/8/8/8/8/8 b - - 0 1',
        shapes: [{ from: 'h8', brush: 'red' }],
        text: 'Cílem hry je dát soupeřovu králi mat. Černý král je napadený a nemá kam utéct. To je mat a hra končí.',
      },
      {
        id: 'no-capture',
        kind: 'show',
        fen: '7k/6Q1/6K1/8/8/8/8/8 b - - 0 1',
        text: 'Krále nikdo nikdy nebere. Hra skončí matem dřív, než by na to došlo.',
      },
    ],
    outro: 'Znáš šachovnici i cíl hry. Teď poznáš figurky, jednu po druhé.',
  },

  {
    id: 'l1-vez',
    level: 1,
    number: 2,
    title: 'Věž',
    piece: 'r',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd8', brush: 'green' },
          { from: 'd4', to: 'd1', brush: 'green' },
          { from: 'd4', to: 'a4', brush: 'green' },
          { from: 'd4', to: 'h4', brush: 'green' },
        ],
        text: 'Tohle je {věž}. Jezdí rovně: dopředu, dozadu, doleva a doprava.',
      },
      {
        id: 'distance',
        kind: 'show',
        fen: '8/8/8/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd5', brush: 'green' },
          { from: 'd4', to: 'h4', brush: 'green' },
        ],
        text: 'V jednom tahu jede věž jen jedním směrem. Může ujet jedno pole, nebo klidně celou šachovnici.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/R7 w - - 0 1',
        diagram: true,
        piece: 'a1',
        stars: ['a6', 'f6', 'f8'],
        text: 'Teď ty! Seber věží všechny hvězdy. Stačí na hvězdu dojet.',
        success: 'Paráda! Všechny hvězdy jsou tvoje.',
      },
      {
        id: 'no-jump',
        kind: 'show',
        fen: '8/8/3P4/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd5', brush: 'green' },
          { from: 'd6', brush: 'red' },
        ],
        text: 'Věž nepřeskakuje. Když jí v cestě stojí figurka, musí zastavit před ní.',
      },
      {
        id: 'around',
        kind: 'collect',
        fen: '8/8/8/1P6/8/8/1R2P3/8 w - - 0 1',
        diagram: true,
        piece: 'b2',
        stars: ['b8'],
        maxMoves: 3,
        text: 'Hvězda je schovaná za tvou figurkou. Najdi cestu kolem. Stačí ti 3 tahy.',
        success: 'Výborně! Když rovná cesta nevede, věž jede oklikou.',
      },
      {
        id: 'capture',
        kind: 'show',
        fen: '8/3n4/8/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'd4', to: 'd7', brush: 'green' }],
        text: 'Věž bere stejně, jak jezdí. Stoupne si na pole soupeřovy figurky. Ta pak ze šachovnice zmizí.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: 'k7/8/1p6/8/3R2p1/8/8/7K w - - 0 1',
        movable: ['d4'],
        accept: ['d4g4'],
        completeness: { kind: 'lands', square: 'g4' },
        text: 'Vezmi věží černou figurku. Jen na jednu z nich věž dosáhne.',
        success: 'Výborně! Věž bere rovně, stejně jak jezdí.',
        wrongDefault: 'Tím nic nevezmeš. Najdi figurku, ke které vede rovná cesta.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '8/8/8/8/P7/8/8/R7 w - - 0 1',
        diagram: true,
        text: 'Na které označené pole dojede věž jedním tahem?',
        options: [
          { id: 'a6', square: 'a6' },
          { id: 'c3', square: 'c3' },
          { id: 'f1', square: 'f1' },
        ],
        correct: ['f1'],
        explain: 'Ano! Na f1 vede rovná a volná cesta.',
        wrongExplain: {
          a6: 'Na a6 ne. V cestě stojí tvoje figurka a věž nepřeskakuje.',
          c3: 'Na c3 ne. Cesta tam nevede rovně a věž jezdí jen rovně.',
        },
        wrongDefault: 'Věž jezdí jen rovně a nepřeskakuje.',
      },
    ],
    outro: 'Umíš věž! Jezdí rovně, nepřeskakuje a bere tam, kam jezdí.',
  },

  {
    id: 'l1-strelec',
    level: 1,
    number: 3,
    title: 'Střelec',
    piece: 'b',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3B4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'a7', brush: 'green' },
          { from: 'd4', to: 'h8', brush: 'green' },
          { from: 'd4', to: 'a1', brush: 'green' },
          { from: 'd4', to: 'g1', brush: 'green' },
        ],
        text: 'Tohle je {střelec}. Jezdí šikmo, daleko nebo jen o jedno pole.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/2B5 w - - 0 1',
        diagram: true,
        piece: 'c1',
        stars: ['e3', 'g5', 'h4'],
        text: 'Seber střelcem všechny hvězdy.',
        success: 'Paráda! Střelec to zvládl samými šikmými tahy.',
      },
      {
        id: 'colour',
        kind: 'show',
        fen: '8/8/8/8/8/8/8/2B5 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'a3', brush: 'blue' },
          { from: 'e3', brush: 'blue' },
          { from: 'g5', brush: 'blue' },
        ],
        text: 'Tenhle střelec stojí na tmavém poli. Proto chodí jen po tmavých polích, pořád.',
      },
      {
        id: 'never',
        kind: 'choose',
        fen: '8/8/8/8/8/8/8/2B5 w - - 0 1',
        diagram: true,
        stars: ['e4'],
        text: 'Dojde tenhle střelec někdy na hvězdu? Klidně i za víc tahů.',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nikdy. Hvězda je na světlém poli a tenhle střelec chodí jen po tmavých.',
        wrongDefault: 'Podívej se na barvu pole pod hvězdou. A potom na barvu pole pod střelcem.',
      },
      {
        id: 'same',
        kind: 'choose',
        fen: '8/8/8/8/8/8/8/5B2 w - - 0 1',
        diagram: true,
        stars: ['b5'],
        text: 'A tenhle střelec? Dojde na hvězdu?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ano'],
        explain: 'Ano! Střelec i hvězda jsou na světlých polích. Stačí jeden tah.',
        wrongDefault: 'Podívej se na barvu pole pod hvězdou i pod střelcem. Je stejná?',
      },
      {
        id: 'take',
        kind: 'move',
        fen: 'k7/8/8/6p1/2p5/8/8/2B3K1 w - - 0 1',
        movable: ['c1'],
        accept: ['c1g5'],
        completeness: { kind: 'lands', square: 'g5' },
        text: 'Střelec bere šikmo, stejně jak jezdí. Vezmi střelcem černou figurku.',
        success: 'Výborně! Na druhou figurku tvůj střelec nedosáhne. Stojí na světlém poli.',
        wrongDefault: 'Tím nic nevezmeš. Najdi figurku, ke které vede šikmá cesta.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '8/8/8/8/8/4P3/8/2B5 w - - 0 1',
        diagram: true,
        text: 'Na které označené pole dojede střelec jedním tahem?',
        options: [
          { id: 'g5', square: 'g5' },
          { id: 'c5', square: 'c5' },
          { id: 'a3', square: 'a3' },
        ],
        correct: ['a3'],
        explain: 'Ano! Na a3 vede volná šikmá cesta.',
        wrongExplain: {
          g5: 'Na g5 ne. V cestě stojí tvoje figurka a střelec nepřeskakuje.',
          c5: 'Na c5 ne. To je rovně a střelec jezdí jen šikmo.',
        },
        wrongDefault: 'Střelec jezdí jen šikmo a nepřeskakuje.',
      },
    ],
    outro: 'Umíš střelce! Jezdí šikmo, nepřeskakuje a zůstává na polích své barvy.',
  },

  {
    id: 'l1-dama',
    level: 1,
    number: 4,
    title: 'Dáma',
    piece: 'q',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3Q4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd8', brush: 'green' },
          { from: 'd4', to: 'd1', brush: 'green' },
          { from: 'd4', to: 'a4', brush: 'green' },
          { from: 'd4', to: 'h4', brush: 'green' },
          { from: 'd4', to: 'a7', brush: 'green' },
          { from: 'd4', to: 'h8', brush: 'green' },
          { from: 'd4', to: 'a1', brush: 'green' },
          { from: 'd4', to: 'g1', brush: 'green' },
        ],
        text: 'Tohle je {dáma}. Jezdí rovně jako věž i šikmo jako střelec.',
      },
      {
        id: 'not-there',
        kind: 'choose',
        fen: '8/8/8/8/3Q4/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Dáma umí hodně, ale ne všechno. Na které označené pole jedním tahem nedojede?',
        options: [
          { id: 'd8', square: 'd8' },
          { id: 'e6', square: 'e6' },
          { id: 'g7', square: 'g7' },
        ],
        correct: ['e6'],
        explain: 'Správně. Na e6 to není rovně ani šikmo. Tam dáma nedojede.',
        wrongExplain: {
          d8: 'Na d8 dojede. To je rovně, jako věž.',
          g7: 'Na g7 dojede. To je šikmo, jako střelec.',
        },
        wrongDefault: 'Dáma jezdí jen rovně a šikmo.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/Q7 w - - 0 1',
        diagram: true,
        piece: 'a1',
        stars: ['d4', 'd8', 'h4'],
        maxMoves: 3,
        text: 'Seber dámou všechny hvězdy. Zvládneš to na 3 tahy?',
        success: 'Paráda! Rovně i šikmo, přesně jak dáma umí.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: 'k7/8/5r2/8/8/8/1Q6/6K1 w - - 0 1',
        movable: ['b2'],
        accept: ['b2f6'],
        completeness: { kind: 'lands', square: 'f6' },
        text: 'Vezmi dámou černou věž.',
        success: 'Výborně! Dáma bere rovně i šikmo, jak jezdí.',
        wrongDefault: 'Tím věž nevezmeš. Najdi k ní rovnou nebo šikmou cestu.',
      },
      {
        id: 'way-out',
        kind: 'collect',
        fen: '8/8/8/8/8/8/2PPP3/3Q4 w - - 0 1',
        diagram: true,
        piece: 'd1',
        stars: ['h5', 'a4'],
        maxMoves: 4,
        text: 'Tvoje figurky stojí dámě v cestě. Najdi cestu ven a seber hvězdy.',
        success: 'Výborně! Dáma taky nepřeskakuje, ale cestu si najde.',
      },
    ],
    outro: 'Umíš dámu! Jezdí rovně i šikmo, jako věž a střelec dohromady.',
  },

  {
    id: 'l1-kral',
    level: 1,
    number: 5,
    title: 'Král',
    piece: 'k',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/4K3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: (['d3', 'e3', 'f3', 'd4', 'f4', 'd5', 'e5', 'f5'] as const).map((s) => ({ from: s, brush: 'green' as const })),
        text: 'Tohle je {král}. Chodí jen o jedno pole, ale kterýmkoli směrem.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/4K3 w - - 0 1',
        diagram: true,
        piece: 'e1',
        stars: ['e3', 'g3'],
        maxMoves: 4,
        text: 'Seber králem obě hvězdy. Pomalu, vždycky jen o jedno pole.',
        success: 'Paráda! Král je pomalý, ale dojde všude.',
      },
      {
        id: 'kings',
        kind: 'show',
        fen: '8/8/4k3/8/4K3/8/8/8 w - - 0 1',
        shapes: [
          { from: 'd5', brush: 'red' },
          { from: 'e5', brush: 'red' },
          { from: 'f5', brush: 'red' },
        ],
        text: 'Dva králové nikdy nestojí vedle sebe. Na červená pole tvůj král nesmí.',
      },
      {
        id: 'where',
        kind: 'move',
        fen: '8/8/4k3/8/4K3/8/8/8 w - - 0 1',
        movable: ['e4'],
        accept: ['e4d3', 'e4e3', 'e4f3', 'e4d4', 'e4f4'],
        completeness: { kind: 'legal', from: 'e4' },
        text: 'Táhni svým králem na pole, kam smí.',
        success: 'Ano, tam král smí.',
        wrongDefault: 'Tam král nedojde. Chodí jen o jedno pole.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '8/8/8/8/3K1k2/8/8/8 w - - 0 1',
        text: 'Na které označené pole smí bílý král?',
        options: [
          { id: 'e4', square: 'e4' },
          { id: 'c5', square: 'c5' },
          { id: 'e5', square: 'e5' },
        ],
        correct: ['c5'],
        explain: 'Ano! Pole c5 je daleko od černého krále.',
        wrongExplain: {
          e4: 'Na e4 ne. Stál by hned vedle černého krále.',
          e5: 'Na e5 ne. Stál by šikmo vedle černého krále.',
        },
        wrongDefault: 'Králové nikdy nestojí vedle sebe.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '7k/8/8/3r4/4K3/8/8/8 w - - 0 1',
        movable: ['e4'],
        accept: ['e4d5'],
        completeness: { kind: 'lands', square: 'd5' },
        text: 'Král taky bere, o jedno pole. Vezmi králem černou věž.',
        success: 'Výborně! Věž stála hned vedle, a tak ji král vzal.',
        wrongDefault: 'Tím věž nevezmeš. Stoupni si králem na její pole.',
      },
    ],
    outro: 'Umíš krále! Chodí o jedno pole a nikdy nestojí vedle druhého krále.',
  },

  {
    id: 'l1-jezdec',
    level: 1,
    number: 6,
    title: 'Jezdec',
    piece: 'n',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: (['c6', 'e6', 'f5', 'f3', 'e2', 'c2', 'b3', 'b5'] as const).map((s) => ({ from: s, brush: 'green' as const })),
        text: 'Tohle je {jezdec}. Skáče do tvaru písmene L: dvě pole rovně a jedno do strany.',
      },
      {
        id: 'one-jump',
        kind: 'show',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd6', brush: 'blue' },
          { from: 'd6', to: 'e6', brush: 'blue' },
          { from: 'e6', brush: 'green' },
        ],
        text: 'Tady je jeden skok. Dvě pole nahoru, jedno doprava. Jezdec přistane rovnou na e6.',
      },
      {
        id: 'jumps',
        kind: 'show',
        fen: '8/8/8/8/8/8/PPPP4/1N6 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'a3', brush: 'green' },
          { from: 'c3', brush: 'green' },
        ],
        text: 'Jezdec jako jediný přeskakuje. Nevadí mu, co stojí mezi.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/1N6 w - - 0 1',
        diagram: true,
        piece: 'b1',
        stars: ['c3', 'e4', 'f6'],
        text: 'Seber jezdcem všechny hvězdy.',
        success: 'Paráda! Hop, hop, hop.',
      },
      {
        id: 'colour',
        kind: 'show',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: (['c6', 'e6', 'f5', 'f3', 'e2', 'c2', 'b3', 'b5'] as const).map((s) => ({ from: s, brush: 'green' as const })),
        text: 'Jezdec stojí na tmavém poli. Po každém skoku přistane na poli opačné barvy.',
      },
      {
        id: 'detour',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/N7 w - - 0 1',
        diagram: true,
        piece: 'a1',
        stars: ['b2'],
        text: 'Hvězda je hned vedle jezdce. Stejně k ní musí skákat oklikou!',
        success: 'Výborně! Blízko neznamená pro jezdce snadno.',
      },
      {
        id: 'over',
        kind: 'show',
        fen: '8/8/4p3/3p4/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'e6', brush: 'green' },
          { from: 'd5', brush: 'blue' },
        ],
        text: 'Jezdec bere jen tam, kam doskočí. Figurku, kterou přeskočí, nevezme.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '6k1/8/8/3r4/2p5/2N5/8/6K1 w - - 0 1',
        movable: ['c3'],
        accept: ['c3d5'],
        completeness: { kind: 'lands', square: 'd5' },
        text: 'Vezmi jezdcem černou věž.',
        success: 'Hop a věž je tvoje!',
        wrongDefault: 'Tím věž nevezmeš. Najdi skok do L, který skončí na věži.',
      },
    ],
    outro: 'Umíš jezdce! Skáče do L, přeskakuje a bere jen tam, kam doskočí.',
  },

  {
    id: 'l1-pesec',
    level: 1,
    number: 7,
    title: 'Pěšec',
    piece: 'p',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/8/4P3/8/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'e3', to: 'e4', brush: 'green' }],
        text: 'Tohle je {pěšec}. Chodí rovně dopředu, jen o jedno pole.',
      },
      {
        id: 'first',
        kind: 'show',
        fen: '8/8/8/8/8/8/4P3/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'e2', to: 'e3', brush: 'green' },
          { from: 'e2', to: 'e4', brush: 'green' },
        ],
        text: 'Když pěšec ještě netáhl, smí jít o jedno, nebo o dvě pole. Vybere si.',
      },
      {
        id: 'double',
        kind: 'move',
        fen: '4k3/8/8/8/8/8/4P3/4K3 w - - 0 1',
        movable: ['e2'],
        accept: ['e2e4'],
        completeness: { kind: 'lands', square: 'e4', from: 'e2' },
        text: 'Posuň pěšce co nejdál dopředu.',
        success: 'Výborně! O dvě pole smí jen při svém prvním tahu.',
        wrong: { e2e3: 'To je jen o jedno pole. Z prvního pole smí pěšec i o dvě.' },
        wrongDefault: 'Pěšec jde rovně dopředu. Z prvního pole smí i o dvě.',
      },
      {
        id: 'no-back',
        kind: 'show',
        fen: '8/8/8/8/4P3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'e4', to: 'e5', brush: 'green' },
          { from: 'e4', to: 'e3', brush: 'red' },
        ],
        text: 'Pěšec nikdy necouvá. Jde jen dopředu, směrem k soupeři.',
      },
      {
        id: 'capture',
        kind: 'show',
        fen: '8/8/8/3n1r2/4P3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'e4', to: 'd5', brush: 'green' },
          { from: 'e4', to: 'f5', brush: 'green' },
        ],
        text: 'Pěšec bere jinak, než chodí. Bere šikmo dopředu, o jedno pole.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '6k1/8/8/3r1n2/4P3/8/8/6K1 w - - 0 1',
        movable: ['e4'],
        accept: ['e4d5', 'e4f5'],
        completeness: { kind: 'captures', from: 'e4' },
        text: 'Vezmi pěšcem černou figurku.',
        success: 'Výborně! Pěšec bere šikmo dopředu.',
        wrong: { e4e5: 'Tím nic nevezmeš. Rovně pěšec nebere, bere jen šikmo dopředu.' },
        wrongDefault: 'Pěšec bere šikmo dopředu, o jedno pole.',
      },
      {
        id: 'blocked',
        kind: 'choose',
        fen: '8/8/8/4p3/4P3/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Bílý pěšec stojí proti černému. Může bílý pěšec táhnout?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nemůže. Rovně mu stojí v cestě černý pěšec. Šikmo před ním nic není.',
        wrongDefault: 'Rovně pěšec nebere. A šikmo před ním žádná figurka nestojí.',
      },
    ],
    outro: 'Umíš pěšce! Teď už znáš všechny figurky. Zkus si zahrát první partii.',
    practice: [
      { kind: 'play', level: 1, label: 'Zahraj si partii proti nejslabšímu soupeři' },
      { kind: 'puzzles', band: 'zacatecnik', theme: 'hangingPiece', count: 5, label: 'Úlohy: seber nechráněnou figurku' },
    ],
  },

  // ---- Phase 21b: lessons 8–18 ------------------------------------------------------

  {
    id: 'l1-promena',
    level: 1,
    number: 8,
    title: 'Proměna pěšce',
    steps: [
      {
        id: 'end',
        kind: 'show',
        fen: '8/4P3/8/8/8/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'e7', to: 'e8', brush: 'green' }],
        text: 'Když {pěšec} dojde až na poslední řadu, promění se. Z malého pěšce je najednou silná figurka.',
      },
      {
        id: 'rule',
        kind: 'show',
        fen: '8/4P3/8/8/8/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'e8', brush: 'green' }],
        text: 'Pěšec se promění v dámu, věž, střelce nebo jezdce své barvy. Ne v krále ani v pěšce.',
      },
      {
        id: 'promote',
        kind: 'move',
        fen: '4k3/1P6/8/8/8/8/8/4K3 w - - 0 1',
        accept: ['b7b8q', 'b7b8r', 'b7b8b', 'b7b8n'],
        completeness: { kind: 'lands', square: 'b8' },
        text: 'Posuň pěšce na poslední řadu. Pak si vyber, v co se promění.',
        success: 'Hotovo! Skoro vždy chceš dámu. Je ze všech figurek nejsilnější.',
        wrongDefault: 'Tím se pěšec nepromění. Táhni pěšcem na poslední řadu.',
      },
      {
        id: 'not-king',
        kind: 'choose',
        fen: '8/4P3/8/8/8/8/8/8 w - - 0 1',
        diagram: true,
        text: 'V co se pěšec proměnit nesmí?',
        options: [
          { id: 'dama', label: 'V dámu' },
          { id: 'jezdec', label: 'V jezdce' },
          { id: 'kral', label: 'V krále' },
        ],
        correct: ['kral'],
        explain: 'Správně. Krále má každý jen jednoho, po celou partii.',
        wrongExplain: {
          dama: 'V dámu se proměnit smí. To je nejčastější proměna.',
          jezdec: 'V jezdce se proměnit smí. Jen se to hodí málokdy.',
        },
        wrongDefault: 'Pěšec se smí proměnit v dámu, věž, střelce nebo jezdce.',
      },
      {
        id: 'two-queens',
        kind: 'show',
        fen: '7k/8/8/3Q4/8/8/8/3QK3 w - - 0 1',
        shapes: [
          { from: 'd5', brush: 'green' },
          { from: 'd1', brush: 'green' },
        ],
        text: 'Můžeš mít dvě dámy, klidně i víc. Tady má bílý dvě dámy najednou.',
      },
      {
        id: 'take-promote',
        kind: 'move',
        fen: '3r3k/2P5/8/8/8/8/8/6K1 w - - 0 1',
        accept: ['c7d8q', 'c7d8r', 'c7d8b', 'c7d8n'],
        completeness: { kind: 'lands', square: 'd8' },
        text: 'Pěšec se může proměnit i tak, že bere. Vezmi pěšcem černou věž.',
        success: 'Výborně! Pěšec vzal věž a hned se proměnil.',
        wrongDefault: 'Pěšec bere šikmo dopředu. Najdi černou věž.',
      },
    ],
    outro: 'Umíš proměnu! Pěšec na poslední řadě se promění. Skoro vždy v dámu.',
  },

  {
    id: 'l1-pescova-valka',
    level: 1,
    number: 9,
    title: 'Minihra: Pěšcová válka',
    steps: [
      {
        id: 'rules',
        kind: 'show',
        fen: '8/pppppppp/8/8/8/8/PPPPPPPP/8 w - - 0 1',
        diagram: true,
        text: 'Teď si zahraješ minihru. Není to opravdová partie, má svoje vlastní pravidla. Hrají v ní jen pěšci.',
      },
      {
        id: 'goal',
        kind: 'show',
        fen: '8/pppppppp/8/8/8/8/PPPPPPPP/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'a8', to: 'h8', brush: 'green' }],
        text: 'Vyhraje ten, kdo první dojde pěšcem na poslední řadu. Nebo ten, kdo sebere všechny soupeřovy pěšce.',
      },
      {
        id: 'moves',
        kind: 'show',
        fen: '8/pppppppp/8/8/8/8/PPPPPPPP/8 w - - 0 1',
        diagram: true,
        text: 'Pěšci chodí a berou stejně jako v šachu. Ty hraješ za bílé a začínáš. Když někdo nemá žádný tah, je to remíza.',
      },
      {
        id: 'small',
        kind: 'mini',
        fen: '8/2ppp3/8/8/8/8/1PPP4/8 w - - 0 1',
        diagram: true,
        goal: 'promote-first',
        engineLevel: 1,
        text: 'Nejdřív na zkoušku, tři proti třem. Doběhni pěšcem až na konec!',
        success: 'Vyhráváš! Tvůj pěšec doběhl na konec.',
      },
      {
        id: 'tip',
        kind: 'show',
        fen: '8/2p5/8/8/8/8/5P2/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'f2', to: 'f8', brush: 'green' }],
        text: 'Tip: pěšec, kterému nikdo nestojí v cestě, doběhne nejrychleji. Hlídej ale i soupeřovy pěšce!',
      },
      {
        id: 'full',
        kind: 'mini',
        fen: '8/pppppppp/8/8/8/8/PPPPPPPP/8 w - - 0 1',
        diagram: true,
        goal: 'promote-first',
        engineLevel: 1,
        text: 'A teď celá válka, osm proti osmi. Hodně štěstí!',
        success: 'Vyhráváš pěšcovou válku! Paráda.',
      },
    ],
    outro: 'Skvělá hra! Pěšci jsou malí, ale když dojdou na konec, promění se.',
  },

  {
    id: 'l1-utok-obrana',
    level: 1,
    number: 10,
    title: 'Útok a obrana',
    steps: [
      {
        id: 'attack',
        kind: 'show',
        fen: 'k7/8/8/3n4/8/8/8/3R2K1 w - - 0 1',
        shapes: [{ from: 'd1', to: 'd5', brush: 'red' }],
        text: 'Figurka je napadená, když ji soupeř může dalším tahem vzít. Tvoje věž teď útočí na černého jezdce.',
      },
      {
        id: 'defended',
        kind: 'show',
        fen: 'k7/8/4p3/3n4/8/8/8/3R2K1 w - - 0 1',
        shapes: [
          { from: 'd1', to: 'd5', brush: 'red' },
          { from: 'e6', to: 'd5', brush: 'blue' },
        ],
        text: 'Teď jezdce kryje černý pěšec. Kdyby věž vzala jezdce, pěšec by vzal věž.',
      },
      {
        id: 'hanging',
        kind: 'show',
        fen: 'k7/8/8/3n4/8/8/8/3R2K1 w - - 0 1',
        shapes: [{ from: 'd5', brush: 'red' }],
        text: 'Napadenou figurku, kterou nikdo nekryje, můžeš vzít zadarmo. Říkáme, že visí.',
      },
      {
        id: 'which-hangs',
        kind: 'choose',
        fen: 'k7/8/8/1p6/2n3b1/8/8/2R3RK w - - 0 1',
        text: 'Tvoje věže útočí na dvě černé figurky. Která z nich visí? Klikni na ni.',
        options: [
          { id: 'c4', square: 'c4' },
          { id: 'g4', square: 'g4' },
          { id: 'b5', square: 'b5' },
        ],
        correct: ['g4'],
        explain: 'Ano! Na střelce útočí věž a nikdo ho nekryje.',
        wrongExplain: {
          c4: 'Jezdce kryje pěšec na b5. Ten nevisí.',
          b5: 'Na pěšce na b5 nikdo neútočí.',
        },
        wrongDefault: 'Hledej figurku, na kterou útočíš a kterou nikdo nekryje.',
      },
      {
        id: 'take-free',
        kind: 'move',
        fen: 'k7/8/8/1p6/2n3b1/8/8/2R3RK w - - 0 1',
        accept: ['g1g4'],
        completeness: { kind: 'lands', square: 'g4' },
        text: 'Vezmi figurku, která visí.',
        success: 'Výborně! Střelec byl zadarmo.',
        wrongDefault: 'Tím nic zadarmo nevezmeš. Najdi figurku, kterou nikdo nekryje.',
      },
      {
        id: 'save',
        kind: 'move',
        fen: 'k4r2/8/8/3p4/4N3/b7/8/6K1 w - - 0 1',
        accept: ['e4c3', 'e4d2', 'e4g3', 'e4g5'],
        completeness: { kind: 'safe', from: 'e4' },
        text: 'Pozor, černý pěšec útočí na tvého jezdce. Uhni s jezdcem na pole, kde ho nikdo nevezme.',
        success: 'Výborně! Tam je jezdec v bezpečí.',
        wrongDefault: 'Jezdec pořád visí. Uhni s ním na bezpečné pole.',
      },
    ],
    outro: 'Před každým tahem se podívej: co je napadené a co visí? Tvoje i soupeřovy figurky.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'hangingPiece', count: 5, label: 'Úlohy: seber figurku, která visí' }],
  },

  {
    id: 'l1-hodnota',
    level: 1,
    number: 11,
    title: 'Kolik figury stojí',
    steps: [
      {
        id: 'values',
        kind: 'show',
        fen: '8/8/8/8/PNBRQ3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'a4', brush: 'blue', label: '1' },
          { from: 'b4', brush: 'blue', label: '3' },
          { from: 'c4', brush: 'blue', label: '3' },
          { from: 'd4', brush: 'blue', label: '5' },
          { from: 'e4', brush: 'blue', label: '9' },
        ],
        text: 'Figurky mají různou cenu. Počítá se v pěšcích: pěšec 1, jezdec 3, střelec 3, věž 5, dáma 9.',
      },
      {
        id: 'king',
        kind: 'show',
        fen: '8/8/8/8/4K3/8/8/8 w - - 0 1',
        diagram: true,
        text: 'A král? Ten žádné číslo nemá. O krále se hraje celou partii, nikdy ho nevyměníš.',
      },
      {
        id: 'more',
        kind: 'choose',
        fen: '8/8/8/8/1R3NP1/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Co má větší cenu: věž, nebo jezdec s pěšcem dohromady?',
        options: [
          { id: 'vez', label: 'Věž' },
          { id: 'jezdec-pesec', label: 'Jezdec s pěšcem' },
          { id: 'stejne', label: 'Stejně' },
        ],
        correct: ['vez'],
        explain: 'Ano! Věž je 5. Jezdec s pěšcem jsou dohromady jen 4.',
        wrongExplain: {
          'jezdec-pesec': 'Jezdec a pěšec jsou 3 a 1, dohromady 4. Věž je 5.',
          stejne: 'Skoro! Jezdec a pěšec jsou dohromady 4. Věž je 5, to je víc.',
        },
        wrongDefault: 'Sečti to: jezdec 3 a pěšec 1. A věž je 5.',
      },
      {
        id: 'trade',
        kind: 'show',
        fen: 'k7/8/2p5/3r4/8/4N3/8/6K1 w - - 0 1',
        shapes: [
          { from: 'e3', to: 'd5', brush: 'green' },
          { from: 'c6', to: 'd5', brush: 'blue' },
        ],
        text: 'Tvůj jezdec může vzít věž. Pak pěšec vezme jezdce. Dáš 3 a dostaneš 5, to se vyplatí!',
      },
      {
        id: 'bad-trade',
        kind: 'choose',
        fen: 'k7/8/2p5/3p4/8/8/8/3Q2K1 w - - 0 1',
        text: 'Vyplatí se vzít dámou pěšce na d5?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nevyplatí. Pěšce kryje druhý pěšec. Dáš 9 a dostaneš jen 1.',
        wrongDefault: 'Pěšce na d5 kryje pěšec na c6. Za jednoho pěšce by ti vzal dámu.',
      },
      {
        id: 'good-trade',
        kind: 'move',
        fen: 'k7/8/2p5/p2r4/1p6/4N3/8/1Q4K1 w - - 0 1',
        accept: ['e3d5'],
        completeness: { kind: 'best' },
        text: 'Najdi výměnu, která se ti vyplatí.',
        success: 'Výborně! Za jezdce za 3 dostaneš věž za 5.',
        wrongDefault: 'Tahle výměna se nevyplatí. Hledej, kde dostaneš víc, než dáš.',
      },
      {
        id: 'mini-intro',
        kind: 'show',
        fen: '8/ppppp3/8/8/8/8/8/3Q4 w - - 0 1',
        diagram: true,
        text: 'Teď minihra: tvoje dáma proti pěti pěšcům. Seber je všechny. Žádný pěšec ti ale nesmí vzít dámu ani dojít na konec.',
      },
      {
        id: 'queen-vs-pawns',
        kind: 'mini',
        fen: '8/ppppp3/8/8/8/8/8/3Q4 w - - 0 1',
        diagram: true,
        goal: 'capture-all-pawns',
        engineLevel: 1,
        text: 'Seber dámou všech pět pěšců. Nestoupej šikmo před pěšce, vzal by ti dámu.',
        success: 'Všichni pěšci jsou tvoji! A dáma za 9 zůstala v bezpečí.',
      },
    ],
    outro: 'Pamatuj si ceny: 1, 3, 3, 5, 9. Než něco vezmeš, spočítej, co dáš a co dostaneš.',
  },

  {
    id: 'l1-postaveni',
    level: 1,
    number: 12,
    title: 'Základní postavení a pravidla',
    steps: [
      {
        id: 'setup',
        kind: 'show',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        text: 'Tohle je základní postavení. Takhle stojí figurky na začátku každé partie.',
      },
      {
        id: 'row',
        kind: 'show',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        shapes: [
          { from: 'a1', brush: 'blue' },
          { from: 'b1', brush: 'blue' },
          { from: 'c1', brush: 'blue' },
        ],
        text: 'V rozích stojí věže, vedle nich jezdci a potom střelci. Pěšci stojí v řadě před nimi.',
      },
      {
        id: 'queen',
        kind: 'show',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        shapes: [
          { from: 'd1', brush: 'green' },
          { from: 'd8', brush: 'green' },
        ],
        text: 'Dáma stojí na poli své barvy. Bílá dáma na světlém poli, černá dáma na tmavém.',
      },
      {
        id: 'queen-square',
        kind: 'choose',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNB2BNR w - - 0 1',
        diagram: true,
        text: 'Bílá dáma a bílý král utekli. Na které pole patří dáma?',
        options: [
          { id: 'd1', square: 'd1' },
          { id: 'e1', square: 'e1' },
        ],
        correct: ['d1'],
        explain: 'Ano! Dáma patří na světlé pole d1. Král stojí vedle ní na e1.',
        wrongExplain: { e1: 'Na e1 patří král. Dáma stojí na poli své barvy, na světlém.' },
        wrongDefault: 'Dáma stojí na poli své barvy.',
      },
      {
        id: 'who-starts',
        kind: 'choose',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        text: 'Kdo v partii táhne první?',
        options: [
          { id: 'bily', label: 'Bílý' },
          { id: 'cerny', label: 'Černý' },
        ],
        correct: ['bily'],
        explain: 'Ano, bílý vždycky začíná. Potom se hráči střídají, každý táhne jednou.',
        wrongDefault: 'Černý je až druhý. Bílý vždycky začíná.',
      },
      {
        id: 'touch-move',
        kind: 'show',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        text: 'Na skutečné šachovnici platí: dotknuto, táhnuto. Když se dotkneš své figurky, musíš s ní táhnout.',
      },
    ],
    outro: 'Teď umíš postavit figurky na začátek partie. Zkus to doma na opravdové šachovnici!',
  },

  {
    id: 'l1-sach',
    level: 1,
    number: 13,
    title: 'Šach',
    steps: [
      {
        id: 'check',
        kind: 'show',
        fen: 'k7/8/8/8/8/8/8/r3K3 w - - 0 1',
        shapes: [{ from: 'a1', to: 'e1', brush: 'red' }],
        text: 'Když soupeř útočí na krále, je to šach. Tvůj král je teď v šachu od černé věže.',
      },
      {
        id: 'three-ways',
        kind: 'show',
        fen: 'k7/8/8/8/8/8/8/r3K3 w - - 0 1',
        text: 'Ze šachu musíš krále zachránit hned. Jde to třemi způsoby: uhnout, zakrýt, nebo vzít.',
      },
      {
        id: 'escape',
        kind: 'move',
        fen: 'k7/8/8/8/8/8/8/r3K3 w - - 0 1',
        movable: ['e1'],
        accept: ['e1d2', 'e1e2', 'e1f2'],
        completeness: { kind: 'legal', from: 'e1' },
        text: 'Uhni králem ze šachu.',
        success: 'Výborně! Král uhnul a už není v šachu.',
        wrongDefault: 'Tam král nedojde. Chodí jen o jedno pole.',
      },
      {
        id: 'block',
        kind: 'move',
        fen: '4r2k/8/8/8/8/2N5/8/4K3 w - - 0 1',
        movable: ['c3'],
        accept: ['c3e2', 'c3e4'],
        completeness: { kind: 'legal', from: 'c3' },
        text: 'Teď šach zakryj. Postav jezdce mezi věž a svého krále.',
        success: 'Výborně! Jezdec stojí věži v cestě a král je v bezpečí.',
        wrongDefault: 'Tím šach nezakryješ. Jezdec musí stát mezi věží a králem.',
      },
      {
        id: 'capture',
        kind: 'move',
        fen: 'k7/8/8/8/8/6N1/8/4K2r w - - 0 1',
        movable: ['g3'],
        accept: ['g3h1'],
        completeness: { kind: 'captures', from: 'g3' },
        text: 'A teď figurku, která dává šach, vezmi.',
        success: 'Výborně! Věž je pryč a šach taky.',
        wrong: { g3f1: 'Tím šach zakryješ, to taky jde. Ale teď zkus věž vzít.' },
        wrongDefault: 'Tím věž nevezmeš. Najdi skok jezdce na h1.',
      },
      {
        id: 'no-into-check',
        kind: 'show',
        fen: 'k2r4/8/8/8/4K3/8/8/8 w - - 0 1',
        shapes: [
          { from: 'd3', brush: 'red' },
          { from: 'd4', brush: 'red' },
          { from: 'd5', brush: 'red' },
        ],
        text: 'Do šachu táhnout nesmíš. Král nesmí na pole, které hlídá soupeř.',
      },
      {
        id: 'any-way',
        kind: 'move',
        fen: '4r2k/8/8/8/B7/2N5/8/4K3 w - - 0 1',
        accept: ['e1d1', 'e1d2', 'e1f1', 'e1f2', 'a4e8', 'c3e2', 'c3e4'],
        completeness: { kind: 'legal' },
        text: 'Tady jde uhnout, zakrýt i vzít. Zachraň krále, jak chceš.',
        success: 'Výborně! Král je zase v bezpečí.',
        wrongDefault: 'Tím krále nezachráníš. Uhni, zakryj, nebo vezmi.',
      },
    ],
    outro: 'Šach je útok na krále. Zachráníš ho třemi způsoby: uhni, zakryj, nebo vezmi.',
  },

  {
    id: 'l1-mat',
    level: 1,
    number: 14,
    title: 'Mat',
    steps: [
      {
        id: 'mate',
        kind: 'show',
        fen: '3R2k1/5ppp/8/8/8/8/8/6K1 b - - 0 1',
        shapes: [{ from: 'd8', to: 'g8', brush: 'red' }],
        text: 'Mat: král JE v šachu a nic ho nezachrání. Hra končí a vyhrál ten, kdo dal mat.',
      },
      {
        id: 'why',
        kind: 'show',
        fen: '3R2k1/5ppp/8/8/8/8/8/6K1 b - - 0 1',
        text: 'Černý král nemůže uhnout, šach nejde zakrýt a věž nejde vzít. Proto je to mat.',
      },
      {
        id: 'back-rank',
        kind: 'move',
        fen: '6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1',
        accept: ['a1a8'],
        completeness: { kind: 'mate' },
        text: 'Dej mat jedním tahem. Černému králi stojí v cestě vlastní pěšci.',
        success: 'Mat! Král nemá kam utéct.',
        wrongDefault: 'To není mat. Hledej šach, ze kterého král neuteče.',
      },
      {
        id: 'queen-rank',
        kind: 'move',
        fen: '7k/8/6K1/8/8/8/8/1Q6 w - - 0 1',
        accept: ['b1b8'],
        completeness: { kind: 'mate' },
        text: 'Dej mat dámou. Tvůj král už hlídá pole před černým králem.',
        success: 'Mat! Dáma hlídá celou řadu a král zbytek.',
        wrongDefault: 'To není mat. Dej šach tak, aby černý král neměl kam jít.',
      },
      {
        id: 'queen-kiss',
        kind: 'move',
        fen: '4k3/Q7/4K3/8/8/8/8/8 w - - 0 1',
        accept: ['a7a8', 'a7b8', 'a7e7'],
        completeness: { kind: 'mate' },
        text: 'Dej mat dámou. Tvůj král hlídá pole před černým králem.',
        success: 'Mat! Černý král nemá kam utéct.',
        wrongDefault: 'To není mat. Dej šach tak, aby černý král neměl kam jít.',
      },
      {
        id: 'smothered',
        kind: 'move',
        fen: '6rk/6pp/8/6N1/8/8/8/6K1 w - - 0 1',
        accept: ['g5f7'],
        completeness: { kind: 'mate' },
        text: 'Dej mat jezdcem. Černý král je úplně obklíčený vlastními figurkami.',
        success: 'Mat! Jezdec přeskočí všechno a král se nemá kam hnout.',
        wrongDefault: 'To není mat. Najdi skok jezdce, který dá králi šach.',
      },
      {
        id: 'two-rooks',
        kind: 'move',
        fen: '7k/R7/8/8/8/8/8/1R4K1 w - - 0 1',
        accept: ['b1b8'],
        completeness: { kind: 'mate' },
        text: 'Dej mat věží. Druhá věž už hlídá jednu řadu.',
        success: 'Mat! Jedna věž hlídá řadu 7, druhá dává šach na řadě 8.',
        wrongDefault: 'To není mat. Dej šach na poslední řadě.',
      },
    ],
    outro: 'Umíš dát mat! Šach, ze kterého se král nezachrání, a partie je vyhraná.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'mateIn1', count: 5, label: 'Úlohy: mat 1. tahem' }],
  },

  {
    id: 'l1-pat',
    level: 1,
    number: 15,
    title: 'Pat a remízy',
    steps: [
      {
        id: 'stalemate',
        kind: 'show',
        fen: '7k/5Q2/8/8/8/8/8/K7 b - - 0 1',
        shapes: [
          { from: 'g8', brush: 'red' },
          { from: 'g7', brush: 'red' },
          { from: 'h7', brush: 'red' },
        ],
        text: 'Pat: král NENÍ v šachu, ale hráč na tahu nemá žádný povolený tah. To je remíza.',
      },
      {
        id: 'not-loss',
        kind: 'show',
        fen: '7k/5Q2/8/8/8/8/8/K7 b - - 0 1',
        text: 'Pozor, pat není prohra. Je to remíza a nikdo nevyhrál. Bílý tady byl skoro vítěz, a přišel o to.',
      },
      {
        id: 'which-mate',
        kind: 'choose',
        fen: '7k/7Q/6K1/8/8/8/8/8 b - - 0 1',
        text: 'Černý je na tahu. Je to mat, nebo pat?',
        options: [
          { id: 'mat', label: 'Mat' },
          { id: 'pat', label: 'Pat' },
        ],
        correct: ['mat'],
        verify: { kind: 'state' },
        explain: 'Ano, mat! Král je v šachu a nic ho nezachrání.',
        wrongDefault: 'Podívej se, jestli je černý král v šachu. Dáma na h7 na něj útočí.',
      },
      {
        id: 'which-pat',
        kind: 'choose',
        fen: '7k/8/6Q1/8/8/8/8/K7 b - - 0 1',
        text: 'A tady? Černý je zase na tahu. Mat, nebo pat?',
        options: [
          { id: 'mat', label: 'Mat' },
          { id: 'pat', label: 'Pat' },
        ],
        correct: ['pat'],
        verify: { kind: 'state' },
        explain: 'Ano, pat! Král není v šachu, ale nemá žádný tah. Remíza.',
        wrongDefault: 'Útočí něco na černého krále? Není v šachu. Jen se nemůže hnout.',
      },
      {
        id: 'avoid',
        kind: 'move',
        fen: '7k/4Q3/6K1/8/8/8/8/8 w - - 0 1',
        accept: ['e7d8', 'e7e8', 'e7f8', 'e7g7', 'e7h7'],
        completeness: { kind: 'mate' },
        text: 'Dej mat jedním tahem. Pozor, ať to není pat!',
        success: 'Mat! A žádný pat, výborně.',
        wrongDefault: 'To není mat. Dej králi šach, ze kterého neuteče.',
      },
      {
        id: 'material',
        kind: 'show',
        fen: '8/8/8/3k4/8/3K4/8/8 w - - 0 1',
        text: 'Remíza je i tehdy, když nikdo nemůže dát mat. Třeba když zbydou jen dva králové.',
      },
      {
        id: 'more',
        kind: 'show',
        fen: '8/8/8/3k4/8/3K4/8/8 w - - 0 1',
        text: 'Pro zajímavost ještě tři remízy. Stejná pozice se objeví potřetí. Padesát tahů nikdo nic nevezme a netáhne pěšcem. Nebo se hráči dohodnou.',
      },
    ],
    outro: 'Mat vyhrává, pat je remíza. Když vyhráváš, hlídej, ať soupeřův král má kam jít.',
  },

  {
    id: 'l1-rosada',
    level: 1,
    number: 16,
    title: 'Rošáda',
    steps: [
      {
        id: 'what',
        kind: 'show',
        fen: '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        text: 'Rošáda je zvláštní tah. Táhneš při ní najednou králem i věží.',
      },
      {
        id: 'how',
        kind: 'show',
        fen: '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        shapes: [
          { from: 'e1', to: 'g1', brush: 'green' },
          { from: 'h1', to: 'f1', brush: 'blue' },
        ],
        text: 'Král jde o dvě pole k věži. Věž přeskočí vedle něj na druhou stranu.',
      },
      {
        id: 'short',
        kind: 'move',
        fen: '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        movable: ['e1'],
        accept: ['e1g1'],
        completeness: { kind: 'lands', square: 'g1', from: 'e1' },
        text: 'Udělej krátkou rošádu, k věži na h1. Stačí táhnout králem, věž skočí sama.',
        success: 'Výborně! Král je schovaný v rohu a věž vyjela do hry.',
        wrong: { e1c1: 'To je dlouhá rošáda, k věži na a1. Teď zkus krátkou, k věži na h1.' },
        wrongDefault: 'Při rošádě jde král o dvě pole k věži.',
      },
      {
        id: 'long',
        kind: 'move',
        fen: '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        movable: ['e1'],
        accept: ['e1c1'],
        completeness: { kind: 'lands', square: 'c1', from: 'e1' },
        text: 'A teď dlouhou rošádu, k věži na a1.',
        success: 'Výborně! Král jde i tady o dvě pole a věž skočí vedle něj.',
        wrong: { e1g1: 'To je krátká rošáda. Teď zkus dlouhou, k věži na a1.' },
        wrongDefault: 'Při rošádě jde král o dvě pole k věži.',
      },
      {
        id: 'rules-1',
        kind: 'show',
        fen: '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        text: 'Rošádu smíš udělat, když se král i ta věž ještě ani jednou nepohnuli. A mezi nimi nic nestojí.',
      },
      {
        id: 'rules-2',
        kind: 'show',
        fen: '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        text: 'A ještě: král teď není v šachu. Nepřejde přes pole, které soupeř napadá. A neskončí v šachu.',
      },
      {
        id: 'may-not',
        kind: 'choose',
        fen: '5rk1/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        text: 'Smí bílý udělat krátkou rošádu?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        verify: { kind: 'castle', side: 'k' },
        explain: 'Správně, nesmí. Král by šel přes pole f1 a to napadá černá věž.',
        wrongDefault: 'Podívej se na pole, přes která jde král. Napadá některé z nich černá věž?',
      },
      {
        id: 'rook-attacked',
        kind: 'choose',
        fen: '6kr/8/8/8/8/8/8/R3K2R w KQ - 0 1',
        text: 'Černá věž útočí na tvou věž na h1. Smí bílý udělat krátkou rošádu?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ano'],
        verify: { kind: 'castle', side: 'k' },
        explain: 'Ano, smí! Věž napadená být smí. Hlídat musíš jen pole, přes která jde král.',
        wrongDefault: 'Věž napadená být smí. Král jde přes f1 na g1 a tam nikdo neútočí.',
      },
    ],
    outro: 'Umíš rošádu! Král se schová do rohu a věž vyjede do hry.',
  },

  {
    id: 'l1-mimochodem',
    level: 1,
    number: 17,
    title: 'Braní mimochodem',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '4k3/3p4/8/4P3/8/8/8/4K3 b - - 0 1',
        text: 'Tohle je zajímavost, klidně ji přeskoč. V partii se to stává jen málokdy.',
      },
      {
        id: 'jump',
        kind: 'show',
        fen: '4k3/3p4/8/4P3/8/8/8/4K3 b - - 0 1',
        shapes: [{ from: 'd7', to: 'd5', brush: 'blue' }],
        text: 'Černý pěšec teď skočí o dvě pole. Zastaví se hned vedle tvého pěšce.',
      },
      {
        id: 'rule',
        kind: 'show',
        fen: '4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1',
        shapes: [{ from: 'd6', brush: 'green' }],
        text: 'Soupeřův pěšec skočil o dvě pole a zastavil se hned vedle tvého pěšce. Můžeš ho vzít, jako by šel jen o jedno pole.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1',
        accept: ['e5d6'],
        completeness: { kind: 'lands', square: 'd6', from: 'e5' },
        text: 'Vezmi černého pěšce mimochodem.',
        success: 'Výborně! Tvůj pěšec skončil na d6 a černý pěšec zmizel.',
        wrong: { e5e6: 'Tím ho nevezmeš. Pěšec bere šikmo, na pole, přes které černý pěšec skočil.' },
        wrongDefault: 'Táhni svým pěšcem šikmo na d6. Tak ho vezmeš mimochodem.',
      },
      {
        id: 'only-now',
        kind: 'show',
        fen: '4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1',
        text: 'Ale jen hned v dalším tahu. Když zahraješ něco jiného, šance zmizí.',
      },
      {
        id: 'too-late',
        kind: 'choose',
        fen: '4k3/8/8/3pP3/8/8/8/4K3 w - - 0 1',
        text: 'Černý pěšec skočil na d5 už dřív. Od té doby se táhlo něco jiného. Smíš ho teď vzít mimochodem?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, už ne. Mimochodem se bere jen hned v dalším tahu.',
        wrongDefault: 'Mimochodem se bere jen hned v dalším tahu. Teď už je pozdě.',
      },
    ],
    outro: 'Znáš i braní mimochodem! Je vzácné, ale teď tě nepřekvapí.',
  },

  {
    id: 'l1-zkouska',
    level: 1,
    number: 18,
    title: 'Zkouška úrovně 1',
    test: {
      passScore: 9,
      badge: 'l1',
      failOutro: 'Tentokrát to nevyšlo. Zopakuj si lekce, kde to drhlo, a zkus to znovu.',
    },
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        text: 'Zkouška úrovně 1! Čeká tě 11 úloh. Na každou máš jen jeden pokus a žádnou nápovědu. Když zvládneš aspoň 9, získáš odznak a diplom.',
      },
      {
        id: 'square',
        kind: 'choose',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'g6', brush: 'green' }],
        text: 'Jak se jmenuje označené pole?',
        options: [
          { id: 'f6', label: 'f6' },
          { id: 'g6', label: 'g6' },
          { id: 'g3', label: 'g3' },
        ],
        correct: ['g6'],
        explain: 'Sloupec g, řada 6. Je to pole g6.',
        wrongDefault: 'Sloupec g, řada 6. Je to pole g6.',
      },
      {
        id: 'knight',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/6N1 w - - 0 1',
        diagram: true,
        piece: 'g1',
        stars: ['f3', 'e5', 'c6'],
        maxMoves: 3,
        text: 'Seber jezdcem všechny hvězdy. Máš na to 3 tahy.',
        success: 'Tři skoky a hvězdy jsou tvoje.',
      },
      {
        id: 'king',
        kind: 'choose',
        fen: 'k7/8/8/3r4/8/4K3/8/8 w - - 0 1',
        text: 'Na které označené pole smí bílý král?',
        options: [
          { id: 'd4', square: 'd4' },
          { id: 'd2', square: 'd2' },
          { id: 'f3', square: 'f3' },
        ],
        correct: ['f3'],
        verify: { kind: 'reachable', from: 'e3' },
        explain: 'Pole d4 a d2 hlídá černá věž. Na f3 král smí.',
        wrongDefault: 'Pole d4 a d2 hlídá černá věž. Na f3 král smí.',
      },
      {
        id: 'state-check',
        kind: 'choose',
        fen: '4k3/8/8/8/8/8/8/4RK2 b - - 0 1',
        text: 'Černý je na tahu. Co je to za pozici?',
        options: [
          { id: 'sach', label: 'Šach' },
          { id: 'mat', label: 'Mat' },
          { id: 'pat', label: 'Pat' },
          { id: 'nic', label: 'Nic z toho' },
        ],
        correct: ['sach'],
        verify: { kind: 'state' },
        explain: 'Je to šach. Černý král je napadený, ale může uhnout.',
        wrongDefault: 'Je to šach. Černý král je napadený, ale může uhnout.',
      },
      {
        id: 'state-mate',
        kind: 'choose',
        fen: 'R5k1/5ppp/8/8/8/8/8/6K1 b - - 0 1',
        text: 'Černý je na tahu. Co je to za pozici?',
        options: [
          { id: 'sach', label: 'Šach' },
          { id: 'mat', label: 'Mat' },
          { id: 'pat', label: 'Pat' },
          { id: 'nic', label: 'Nic z toho' },
        ],
        correct: ['mat'],
        verify: { kind: 'state' },
        explain: 'Je to mat. Černý král je v šachu a nic ho nezachrání.',
        wrongDefault: 'Je to mat. Černý král je v šachu a nic ho nezachrání.',
      },
      {
        id: 'state-pat',
        kind: 'choose',
        fen: 'k7/2Q5/8/8/8/8/8/6K1 b - - 0 1',
        text: 'Černý je na tahu. Co je to za pozici?',
        options: [
          { id: 'sach', label: 'Šach' },
          { id: 'mat', label: 'Mat' },
          { id: 'pat', label: 'Pat' },
          { id: 'nic', label: 'Nic z toho' },
        ],
        correct: ['pat'],
        verify: { kind: 'state' },
        explain: 'Je to pat. Černý král není v šachu, ale nemá žádný tah.',
        wrongDefault: 'Je to pat. Černý král není v šachu, ale nemá žádný tah.',
      },
      {
        id: 'escape',
        kind: 'move',
        fen: '6k1/8/8/8/8/3N4/4BPPP/4r2K w - - 0 1',
        accept: ['d3e1', 'e2f1'],
        completeness: { kind: 'legal' },
        text: 'Tvůj král je v šachu. Zachraň ho.',
        success: 'Správně! Král je zase v bezpečí.',
        wrongDefault: 'Král uhnout nemůže. Šach šel zakrýt střelcem, nebo věž vzít jezdcem.',
      },
      {
        id: 'mate',
        kind: 'move',
        fen: '6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1',
        accept: ['d1d8'],
        completeness: { kind: 'mate' },
        text: 'Dej mat jedním tahem.',
        success: 'Mat!',
        wrongDefault: 'To nebyl mat. Dáma na d8 by dala mat na poslední řadě.',
      },
      {
        id: 'free',
        kind: 'move',
        fen: '7k/8/2p5/3n4/6b1/8/8/3Q2K1 w - - 0 1',
        accept: ['d1g4'],
        completeness: { kind: 'best' },
        text: 'Vezmi figurku, která se ti vyplatí.',
        success: 'Správně! Střelec visel a navíc útočil na tvou dámu.',
        wrongDefault: 'Střelec na g4 visel. A navíc útočil na tvou dámu.',
      },
      {
        id: 'castle',
        kind: 'choose',
        fen: '1r4k1/8/8/8/8/8/8/R3K3 w Q - 0 1',
        text: 'Smí bílý udělat dlouhou rošádu?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ano'],
        verify: { kind: 'castle', side: 'q' },
        explain: 'Smí. Král jde přes d1 na c1 a tam nikdo neútočí. Přes b1 jde jen věž, a to nevadí.',
        wrongDefault: 'Smí. Král jde přes d1 na c1 a tam nikdo neútočí. Přes b1 jde jen věž, a to nevadí.',
      },
      {
        id: 'promote',
        kind: 'move',
        fen: '8/5P1k/8/5K2/8/8/8/8 w - - 0 1',
        movable: ['f7'],
        accept: ['f7f8r'],
        completeness: { kind: 'best' },
        text: 'Proměň pěšce. Vyber figurku, se kterou vyhraješ.',
        success: 'Výborně! S dámou by to byl pat. S věží vyhraješ.',
        wrongDefault: 'S touhle figurkou nevyhraješ. Správně byla věž: s dámou by to byl pat.',
      },
    ],
    outro: 'Zkouška je za tebou! Odznak je tvůj a můžeš si vytisknout diplom.',
    practice: [{ kind: 'play', level: 2, label: 'Zahraj si partii proti trochu silnějšímu soupeři' }],
  },
];
