/**
 * Level 2 — Začátečník, lessons 1–14: notation, the "what does it threaten" routine, basic
 * tactics, back-rank mate, the opening, the three basic mates, reviewing one's own game and
 * the level test (docs/phase-21-plan.md, curriculum).
 *
 * Positions are game-like: opening lines (Italian, Two Knights, Petroff, Caro-Kann,
 * Scandinavian, Damiano, Blackburne–Shilling, Steinitz, QGD) and simplified middlegames /
 * endgames, several taken from the Lichess puzzle database (CC0; the id is noted). Every
 * tactic task is checked by `npm run check:lessons`: mates with `mate`, "win material"
 * tasks with `best` (Stockfish: no other move within the margin), task-by-definition moves
 * (notation, ladder mate) with `lands`. Texts: informal „ty“, short sentences, Czech
 * letters (K D V S J), 0-0, „dvojný útok“.
 */
import type { Lesson } from './types';

const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
/** 1.e4 e5 2.Jf3 Jc6 */
const OPEN_GAME = 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3';
/** 1.e4 e5 2.Jf3 Jc6 3.Sc4 Sc5 4.c3 Jf6 5.d3 d6 — both sides may still castle. */
const ITALIAN_QUIET = 'r1bqk2r/ppp2ppp/2np1n2/2b1p3/2B1P3/2PP1N2/PP3PPP/RNBQK2R w KQkq - 0 6';
/** 1.e4 e5 2.Jf3 Jc6 3.Sc4 Jf6 */
const TWO_KNIGHTS = 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4';
/** 1.e4 e5 2.Sc4 Jc6 3.Dh5 — white threatens Dxf7 mate. */
const SCHOLAR_THREAT = 'r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3';

export const LEVEL2: readonly Lesson[] = [
  {
    id: 'l2-zapis',
    level: 2,
    number: 1,
    title: 'Šachový zápis',
    steps: [
      {
        id: 'why',
        kind: 'show',
        fen: START,
        text: 'Šachisté si zapisují každý tah. Podle zápisu si pak partii kdykoli přehraješ znovu.',
      },
      {
        id: 'letters',
        kind: 'show',
        fen: START,
        shapes: [
          { from: 'e1', brush: 'green', label: 'K' },
          { from: 'd1', brush: 'green', label: 'D' },
          { from: 'a1', brush: 'green', label: 'V' },
          { from: 'c1', brush: 'green', label: 'S' },
          { from: 'b1', brush: 'green', label: 'J' },
        ],
        text: 'Každá figurka má svoje písmeno. K je král, D dáma, V věž, S střelec a J jezdec. Pěšec písmeno nemá.',
      },
      {
        id: 'how',
        kind: 'show',
        fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
        shapes: [{ from: 'g1', to: 'f3', brush: 'green' }],
        text: 'Tah napíšeš písmenem figurky a polem, kam jde. Jf3 znamená: jezdec jde na pole f3.',
      },
      {
        id: 'play-sc4',
        kind: 'move',
        fen: OPEN_GAME,
        accept: ['f1c4'],
        completeness: { kind: 'lands', square: 'c4', from: 'f1' },
        text: 'Teď ty. Zahraj tah Sc4.',
        success: 'Výborně! Střelec jde na pole c4.',
        wrong: {
          f1b5: 'To je Sb5. Hledáš pole c4.',
          c2c4: 'To je c4, tah pěšcem. Sc4 je tah střelcem.',
        },
        wrongDefault: 'Sc4 znamená: střelec jde na pole c4.',
      },
      {
        id: 'play-c3',
        kind: 'move',
        fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
        accept: ['c2c3'],
        completeness: { kind: 'lands', square: 'c3', from: 'c2' },
        text: 'U tahu pěšcem je jen pole. Zahraj tah c3.',
        success: 'Výborně! Pěšec jde na c3.',
        wrong: { b1c3: 'To je Jc3, tah jezdcem. Tah pěšcem se píše bez písmena.' },
        wrongDefault: 'Tah c3 znamená: pěšec jde na pole c3.',
      },
      {
        id: 'play-exd4',
        kind: 'move',
        fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2BPP3/2P2N2/PP3PPP/RNBQK2R b KQkq - 0 5',
        accept: ['e5d4'],
        completeness: { kind: 'lands', square: 'd4', from: 'e5' },
        text: 'Braní se píše x. Zahraj za černé exd4: pěšec ze sloupce e bere na d4.',
        success: 'Výborně! Pěšec e5 vzal na d4.',
        wrong: {
          c6d4: 'To je Jxd4, bere jezdec. V zápisu exd4 bere pěšec ze sloupce e.',
          c5d4: 'To je Sxd4, bere střelec. V zápisu exd4 bere pěšec ze sloupce e.',
        },
        wrongDefault: 'Zápis exd4 znamená: pěšec ze sloupce e bere na poli d4.',
      },
      {
        id: 'check',
        kind: 'show',
        fen: 'r1bqk2r/pppp1ppp/2n2n2/8/1bBPP3/5N2/PP3PPP/RNBQK2R w KQkq - 1 7',
        shapes: [{ from: 'b4', to: 'e1', brush: 'red' }],
        text: 'Šach se píše +. Černý zahrál Sb4+: střelec šel na b4 a dává šach. Mat se píše #.',
      },
      {
        id: 'castle',
        kind: 'choose',
        fen: ITALIAN_QUIET,
        text: 'Krátká rošáda se píše 0-0, dlouhá 0-0-0. Bílý zahraje 0-0. Na které pole půjde král?',
        options: [
          { id: 'f1', square: 'f1' },
          { id: 'g1', square: 'g1' },
          { id: 'h1', square: 'h1' },
        ],
        correct: ['g1'],
        explain: 'Ano! Král jde o dvě pole k věži, na g1. Věž přeskočí vedle něj na f1.',
        wrongExplain: {
          f1: 'Na f1 skočí věž. Král jde při rošádě o dvě pole.',
          h1: 'Na h1 stojí věž. Král jde při rošádě o dvě pole.',
        },
        wrongDefault: 'Při rošádě jde král o dvě pole k věži.',
      },
    ],
    outro: 'Umíš číst šachový zápis! Hodí se ti v úlohách, v knížkách i při rozboru partií.',
    practice: [{ kind: 'play', level: 2, label: 'Zahraj si partii a sleduj zápis tahů vedle šachovnice' }],
  },

  {
    id: 'l2-hrozby',
    level: 2,
    number: 2,
    title: 'Co mi hrozí?',
    steps: [
      {
        id: 'routine',
        kind: 'show',
        fen: 'r1bqk2r/ppp2pp1/2np1n1p/2b1p1B1/2B1P3/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 7',
        text: 'Po každém soupeřově tahu se zeptej: Co mi hrozí? Může mi dát šach? Může mi něco vzít?',
      },
      {
        id: 'attacked',
        kind: 'choose',
        fen: 'r1bqk2r/ppp2pp1/2np1n1p/2b1p1B1/2B1P3/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 7',
        text: 'Černý právě zahrál h6. Kterou tvoji figurku napadl?',
        options: [
          { id: 'c4', square: 'c4' },
          { id: 'g5', square: 'g5' },
          { id: 'f3', square: 'f3' },
        ],
        correct: ['g5'],
        explain: 'Ano! Pěšec h6 napadá tvého střelce na g5.',
        wrongExplain: {
          c4: 'Střelce c4 pěšec h6 nenapadá. Pěšec bere šikmo jen o jedno pole.',
          f3: 'Jezdce f3 pěšec h6 nenapadá. Pěšec bere šikmo jen o jedno pole.',
        },
        wrongDefault: 'Podívej se, kam může pěšec h6 brát.',
      },
      {
        id: 'save',
        kind: 'move',
        fen: 'r1bqk2r/ppp2pp1/2np1n1p/2b1p1B1/2B1P3/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 7',
        accept: ['g5f6', 'g5e3', 'g5d2', 'g5c1', 'g5h4'],
        completeness: { kind: 'best', marginCp: 100 },
        text: 'Zachraň střelce. Uhni s ním, nebo si za něj vezmi jezdce.',
        success: 'Výborně! Soupeř ti teď střelce zadarmo nevezme.',
        wrongDefault: 'Tvůj střelec pořád visí. Pěšec h6 ho vezme.',
      },
      {
        id: 'mate-threat',
        kind: 'choose',
        fen: 'r1b2rk1/ppp2ppp/2nb4/3p4/3P3q/2NB4/PPP2PPP/R1BQ1RK1 w - - 0 9',
        text: 'Černý zahrál Dh4. Co ti teď hrozí?',
        options: [
          { id: 'mat', label: 'Mat na h2' },
          { id: 'c3', label: 'Vezme jezdce c3' },
          { id: 'nic', label: 'Nic nehrozí' },
        ],
        correct: ['mat'],
        explain: 'Správně! Dáma a střelec d6 míří na h2. Hrozí Dxh2 a to je mat.',
        wrongExplain: {
          c3: 'Jezdce c3 nic nenapadá. Podívej se, kam míří dáma a střelec d6.',
          nic: 'Pozor, hrozí! Podívej se, kam míří dáma a střelec d6.',
        },
        wrongDefault: 'Podívej se, kam míří dáma a střelec d6.',
      },
      {
        id: 'stop-mate',
        kind: 'move',
        fen: 'r1b2rk1/ppp2ppp/2nb4/3p4/3P3q/2NB4/PPP2PPP/R1BQ1RK1 w - - 0 9',
        accept: ['g2g3', 'f2f4'],
        completeness: { kind: 'best', marginCp: 100 },
        text: 'Zastav ten mat. Najdi nejlepší obranu.',
        success: 'Výborně! Pěšec zavřel střelci d6 cestu na h2. Mat už nehrozí.',
        wrong: {
          h2h3: 'To nestačí. Černý obětuje střelce na h3 a útočí dál.',
          f1e1: 'Pak přijde Dxh2+ a král musí utíkat. Najdi lepší obranu.',
          d1h5: 'Černý dá šach Sxh2+ a potom ti vezme dámu.',
        },
        wrongDefault: 'Tenhle tah mat na h2 nezastaví. Hledej tah, který zavře cestu dámě nebo střelci.',
      },
      {
        id: 'own-move',
        kind: 'choose',
        fen: TWO_KNIGHTS,
        text: 'Ptej se i před svým tahem: Nevezme mi to soupeř? Na které pole jezdce f3 nestav?',
        options: [
          { id: 'g5', square: 'g5' },
          { id: 'd4', square: 'd4' },
          { id: 'h4', square: 'h4' },
        ],
        correct: ['d4'],
        explain: 'Správně. Na d4 by ho vzal pěšec e5. A to zadarmo.',
        wrongExplain: {
          g5: 'Na g5 jezdce nic nevezme. Hledej pole, které hlídá černý pěšec.',
          h4: 'Na h4 jezdce nic nevezme. Hledej pole, které hlídá černý pěšec.',
        },
        wrongDefault: 'Hledej pole, které hlídá černý pěšec.',
      },
    ],
    outro: 'Než táhneš, zeptej se: Co mi hrozí? A nevisí mi po tahu něco?',
    practice: [
      { kind: 'play', level: 2, label: 'Zahraj si partii a před každým tahem se zeptej: Co mi hrozí?' },
      { kind: 'puzzles', band: 'zacatecnik', theme: 'hangingPiece', count: 5, label: 'Úlohy: nechráněná figurka' },
    ],
  },

  {
    id: 'l2-dvojny-utok',
    level: 2,
    number: 3,
    title: 'Dvojný útok',
    steps: [
      {
        // Lichess puzzle nCYTL, after 35.Da7+.
        id: 'idea',
        kind: 'show',
        fen: '1n6/Q6k/p2p1p1p/4qPp1/B5P1/2P5/1P6/6K1 b - - 5 35',
        shapes: [
          { from: 'a7', to: 'h7', brush: 'red' },
          { from: 'a7', to: 'b8', brush: 'red' },
        ],
        text: 'Dvojný útok: jedním tahem napadneš dvě věci naráz. Dáma tu dává šach a napadá jezdce b8. Černý zachrání krále a jezdec padne.',
      },
      {
        // Damiano: 1.e4 e5 2.Jf3 f6? 3.Jxe5 fxe5 4.Dh5+ g6
        id: 'damiano',
        kind: 'move',
        fen: 'rnbqkbnr/pppp3p/6p1/4p2Q/4P3/8/PPPP1PPP/RNB1KB1R w KQkq - 0 5',
        accept: ['h5e5'],
        completeness: { kind: 'best' },
        text: 'Černý zahrál g6 a napadl tvoji dámu. Najdi dvojný útok dámou.',
        success: 'Paráda! Šach a zároveň útok na věž h8. Černý zachrání krále a věž je tvoje.',
        wrongDefault: 'Hledej tah dámou, který napadne dvě věci naráz. Jedna z nich může být král.',
      },
      {
        // Blackburne–Shilling: 1.e4 e5 2.Jf3 Jc6 3.Sc4 Jd4 4.Jxe5?
        id: 'blackburne',
        kind: 'move',
        fen: 'r1bqkbnr/pppp1ppp/8/4N3/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4',
        orientation: 'black',
        accept: ['d8g5'],
        completeness: { kind: 'best' },
        text: 'Teď hraješ za černé. Bílý vzal pěšce e5. Najdi dvojný útok dámou.',
        success: 'Paráda! Dáma napadá jezdce e5 i pěšce g2. A za pěšcem g2 stojí věž h1.',
        wrongDefault: 'Hledej tah dámou, který napadne dvě bílé figurky naráz.',
      },
      {
        id: 'others',
        kind: 'show',
        fen: '4rk2/3R2p1/p3P2p/1pp2n2/8/1P6/5PKP/2B5 w - - 0 41',
        text: 'Dvojný útok umí každá figurka. Věž, střelec, jezdec i pěšec. Dvojnému útoku jezdcem nebo pěšcem se říká vidlička.',
      },
      {
        // Lichess puzzle qMydI.
        id: 'rook',
        kind: 'move',
        fen: '4rk2/3R2p1/p3P2p/1pp2n2/8/1P6/5PKP/2B5 w - - 0 41',
        accept: ['d7f7'],
        completeness: { kind: 'best' },
        text: 'Najdi dvojný útok věží.',
        success: 'Výborně! Věž dává šach a napadá jezdce f5. Pěšec e6 ji chrání.',
        wrongDefault: 'Hledej tah věží, který dá šach a zároveň napadne černou figurku.',
      },
    ],
    outro: 'Dvojný útok je silná zbraň. Nejsilnější je, když jedním z cílů je král.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'fork', count: 5, label: 'Úlohy: dvojný útok a vidlička' }],
  },

  {
    id: 'l2-vidlicka',
    level: 2,
    number: 4,
    title: 'Vidlička',
    steps: [
      {
        // Lichess puzzle s2HB9, after 21.Je5+.
        id: 'idea',
        kind: 'show',
        fen: '8/2p2kp1/p1p2q1p/2bpN3/6b1/2N5/PPP2PPP/4Q1K1 b - - 2 21',
        shapes: [
          { from: 'e5', to: 'f7', brush: 'red' },
          { from: 'e5', to: 'g4', brush: 'red' },
        ],
        text: 'Tohle je vidlička. Jezdec dává šach a zároveň napadá střelce g4. Král musí uhnout a střelec padne.',
      },
      {
        // Lichess puzzle wvGrh.
        id: 'royal',
        kind: 'move',
        fen: '8/6p1/p2k3p/1p4q1/5n2/4Q1NP/P4PP1/6K1 w - - 0 34',
        accept: ['g3e4'],
        completeness: { kind: 'best' },
        text: 'Najdi vidličku jezdcem.',
        success: 'Paráda! Šach a útok na dámu naráz. Dáma je tvoje.',
        wrongDefault: 'Hledej skok jezdce, který napadne dvě černé figurky naráz.',
      },
      {
        // Two Knights: 1.e4 e5 2.Jf3 Jc6 3.Sc4 Jf6 4.Jg5 h6?
        id: 'f7',
        kind: 'move',
        fen: 'r1bqkb1r/pppp1pp1/2n2n1p/4p1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 5',
        accept: ['g5f7'],
        completeness: { kind: 'best' },
        text: 'Černý zahrál h6 a napadl tvého jezdce. Najdi vidličku.',
        success: 'Výborně! Jezdec napadá dámu i věž h8. A střelec c4 ho chrání.',
        wrongDefault: 'Hledej skok jezdce, který napadne dvě velké černé figurky.',
      },
      {
        // 1.e4 e5 2.Jf3 Jc6 3.Sc4 Jf6 4.Jc3 Jxe4 5.Jxe4 d5
        id: 'pawn-idea',
        kind: 'show',
        fen: 'r1bqkb1r/ppp2ppp/2n5/3pp3/2B1N3/5N2/PPPP1PPP/R1BQK2R w KQkq - 0 6',
        shapes: [
          { from: 'd5', to: 'c4', brush: 'red' },
          { from: 'd5', to: 'e4', brush: 'red' },
        ],
        text: 'Vidličku umí i pěšec. Tady černý pěšec d5 napadá střelce i jezdce naráz.',
      },
      {
        // 1.e4 Jc6 2.d4 d6 3.Jc3 Se6?
        id: 'pawn',
        kind: 'move',
        fen: 'r2qkbnr/ppp1pppp/2npb3/8/3PP3/2N5/PPP2PPP/R1BQKBNR w KQkq - 2 4',
        accept: ['d4d5'],
        completeness: { kind: 'best' },
        text: 'Najdi vidličku pěšcem.',
        success: 'Výborně! Pěšec napadá jezdce i střelce. Černý zachrání jen jednoho.',
        wrongDefault: 'Hledej tah pěšcem, po kterém napadne dvě černé figurky.',
      },
      {
        // Lichess puzzle MEpLW.
        id: 'find-square',
        kind: 'choose',
        fen: '8/2kr1pR1/8/3p3P/3NbPp1/r7/3R1K2/8 w - - 3 37',
        text: 'Kam skočí jezdec d4, aby dal šach a napadl věž a3?',
        options: [
          { id: 'b5', square: 'b5' },
          { id: 'e6', square: 'e6' },
          { id: 'c6', square: 'c6' },
        ],
        correct: ['b5'],
        explain: 'Ano! Z b5 napadá jezdec krále c7 i věž a3. To je vidlička.',
        wrongExplain: {
          e6: 'Z e6 dá jezdec šach, ale věž a3 nenapadne. A pěšec f7 by ho vzal.',
          c6: 'Z c6 jezdec nedá šach ani nenapadne věž.',
        },
        wrongDefault: 'Hledej pole, odkud jezdec napadne krále i věž.',
      },
    ],
    outro: 'Vidlička je dvojný útok jezdcem nebo pěšcem. Hledej ji v každé partii, u sebe i u soupeře.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'fork', count: 5, label: 'Úlohy: vidlička' }],
  },

  {
    id: 'l2-vazba',
    level: 2,
    number: 5,
    title: 'Vazba',
    steps: [
      {
        // Steinitz: 1.e4 e5 2.Jf3 Jc6 3.Sb5 d6
        id: 'to-king',
        kind: 'show',
        fen: 'r1bqkbnr/ppp2ppp/2np4/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
        shapes: [
          { from: 'b5', to: 'e8', brush: 'blue' },
          { from: 'c6', brush: 'red' },
        ],
        text: 'Střelec b5 míří přes jezdce c6 až na krále e8. Jezdec je vázaný ke králi.',
      },
      {
        id: 'may-it-move',
        kind: 'choose',
        fen: 'r1bqkbnr/ppp2ppp/2np4/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
        text: 'Smí černý jezdec c6 táhnout?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nesmí. Jeho král by pak byl v šachu. Vazba ke králi platí vždycky.',
        wrongDefault: 'Kdyby jezdec uhnul, střelec by dával šach králi. Do šachu se táhnout nesmí.',
      },
      {
        // QGD: 1.d4 d5 2.c4 e6 3.Jc3 Jf6 4.Sg5
        id: 'to-queen',
        kind: 'show',
        fen: 'rnbqkb1r/ppp2ppp/4pn2/3p2B1/2PP4/2N5/PP2PPPP/R2QKBNR b KQkq - 3 4',
        shapes: [
          { from: 'g5', to: 'd8', brush: 'blue' },
          { from: 'f6', brush: 'red' },
        ],
        text: 'Tady je jezdec f6 vázaný k dámě. Za ním stojí dáma, ne král.',
      },
      {
        id: 'queen-pin',
        kind: 'choose',
        fen: 'rnbqkb1r/ppp2ppp/4pn2/3p2B1/2PP4/2N5/PP2PPPP/R2QKBNR b KQkq - 3 4',
        text: 'Co když jezdec f6 uhne?',
        options: [
          { id: 'zakazano', label: 'Nesmí uhnout, je to zakázané' },
          { id: 'dama', label: 'Smí, ale střelec vezme dámu' },
          { id: 'nic', label: 'Smí a nic se nestane' },
        ],
        correct: ['dama'],
        explain: 'Přesně tak. Táhnout smí, ale přišel by o dámu. Za dámu dostane bílý jen střelce.',
        wrongExplain: {
          zakazano: 'Zakázané je to jen u vazby ke králi. Tady je za jezdcem dáma.',
          nic: 'Stane se! Střelec g5 by pak vzal dámu d8.',
        },
        wrongDefault: 'Podívej se, co stojí za jezdcem f6.',
      },
      {
        // Lichess puzzle D4k0S.
        id: 'win',
        kind: 'move',
        fen: '3n2k1/1R6/8/3K4/1p3P2/8/n7/8 w - - 4 46',
        accept: ['b7b8'],
        completeness: { kind: 'best' },
        text: 'Najdi vazbu, která vyhraje figurku.',
        success: 'Výborně! Jezdec d8 je vázaný ke králi a nesmí uhnout. Příště ho vezmeš.',
        wrongDefault: 'Hledej tah věží, po kterém černý jezdec nesmí uhnout.',
      },
      {
        // Caro-Kann: 1.e4 c6 2.d4 d5 3.Jc3 dxe4 4.Jxe4 Jd7 5.De2 Jgf6?
        id: 'mate',
        kind: 'move',
        fen: 'r1bqkb1r/pp1npppp/2p2n2/8/3PN3/8/PPP1QPPP/R1B1KBNR w KQkq - 3 6',
        accept: ['e4d6'],
        completeness: { kind: 'mate' },
        text: 'Černý pěšec e7 je vázaný. Tvoje dáma za ním míří na krále. Dej mat!',
        success: 'Paráda! Pěšec e7 by jezdce rád vzal. Ale je vázaný, a tak nesmí. Mat!',
        wrongDefault: 'Hledej skok jezdce, který dá šach. Vázaný pěšec e7 ho vzít nesmí.',
      },
    ],
    outro: 'Figurka vázaná ke králi nesmí táhnout vůbec. Vázaná k dámě smí, ale za cenu dámy.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'pin', count: 5, label: 'Úlohy: vazba' }],
  },

  {
    id: 'l2-odtazny',
    level: 2,
    number: 6,
    title: 'Odtažný útok a dvojšach',
    steps: [
      {
        // Petroff: 1.e4 e5 2.Jf3 Jf6 3.Jxe5 Jxe4? 4.De2 Jf6?
        id: 'idea',
        kind: 'show',
        fen: 'rnbqkb1r/pppp1ppp/5n2/4N3/8/8/PPPPQPPP/RNB1KB1R w KQkq - 2 5',
        shapes: [
          { from: 'e2', to: 'e8', brush: 'blue' },
          { from: 'e5', brush: 'red' },
        ],
        text: 'Tvoje dáma míří po sloupci e na krále. V cestě jí stojí tvůj jezdec. Když uhne, dáma dá šach.',
      },
      {
        id: 'discovered-check',
        kind: 'move',
        fen: 'rnbqkb1r/pppp1ppp/5n2/4N3/8/8/PPPPQPPP/RNB1KB1R w KQkq - 2 5',
        accept: ['e5c6'],
        completeness: { kind: 'best' },
        text: 'Uhni jezdcem. Dáma dá šach a jezdec může sám napadnout něco velkého.',
        success: 'Paráda! Dáma dává šach a jezdec napadá dámu d8. Tomu se říká odtažný šach.',
        wrong: {
          e5g6: 'Dobrý nápad, vyhraješ věž h8. Ale jiný skok napadne černou dámu.',
          e5g4: 'Šach to je. Ale jezdec tu nenapadá nic velkého.',
        },
        wrongDefault: 'Uhni jezdcem tak, aby napadl černou dámu.',
      },
      {
        // Lichess puzzle qHrp1.
        id: 'attack-idea',
        kind: 'show',
        fen: '2k2r2/ppp2pp1/2n1p2p/2b5/2r1n3/2N2NP1/PP1B1P1P/2RR2K1 w - - 4 21',
        shapes: [
          { from: 'c1', to: 'c4', brush: 'blue' },
          { from: 'c3', brush: 'red' },
        ],
        text: 'Odtažný útok funguje i bez šachu. Tvoje věž c1 míří na věž c4. V cestě stojí jezdec c3.',
      },
      {
        id: 'discovered-attack',
        kind: 'move',
        fen: '2k2r2/ppp2pp1/2n1p2p/2b5/2r1n3/2N2NP1/PP1B1P1P/2RR2K1 w - - 4 21',
        accept: ['c3e4'],
        completeness: { kind: 'best' },
        text: 'Uhni jezdcem c3 co nejlépe. Ať přitom sám něco vezme.',
        success: 'Výborně! Jezdec vzal jezdce a věž c1 napadá věž c4. Černý o figurku přijde.',
        wrongDefault: 'Jezdec c3 má uhnout a přitom sám něco vzít.',
      },
      {
        // Lichess puzzle OGeQW, after 16.Sb5+.
        id: 'double-idea',
        kind: 'show',
        fen: 'r1b1k3/ppp2prp/3p4/1B1n4/8/5N2/P4PPP/R3R1K1 b q - 1 16',
        shapes: [
          { from: 'b5', to: 'e8', brush: 'red' },
          { from: 'e1', to: 'e8', brush: 'red' },
        ],
        text: 'Dvojšach: šach dávají dvě figurky naráz. Zakrýt ani vzít nepomůže. Král musí uhnout.',
      },
      {
        // Lichess puzzle TuUaC.
        id: 'double-check',
        kind: 'move',
        fen: 'rn2k2r/1pq2ppp/p2b2n1/3p2B1/3P4/7P/PPP1BPP1/R2QR1K1 w kq - 0 14',
        accept: ['e2b5'],
        completeness: { kind: 'best' },
        text: 'Najdi dvojšach. Mat pak bude blízko.',
        success: 'Paráda! Pěšec a6 střelce vzít nesmí, král musí uhnout. Pak Ve8 je mat.',
        wrongDefault: 'Hledej tah střelcem e2, po kterém dá šach i věž e1.',
      },
      {
        id: 'only-king',
        kind: 'choose',
        fen: 'rn2k2r/1pq2ppp/p2b2n1/1B1p2B1/3P4/7P/PPP2PP1/R2QR1K1 b kq - 1 14',
        text: 'Co smí černý proti dvojšachu?',
        options: [
          { id: 'kral', label: 'Jen uhnout králem' },
          { id: 'vzit', label: 'Vzít střelce pěšcem a6' },
          { id: 'zakryt', label: 'Zakrýt šach' },
        ],
        correct: ['kral'],
        explain: 'Správně. Proti dvojšachu pomůže jen tah králem.',
        wrongExplain: {
          vzit: 'Pak by pořád dávala šach věž e1. Proti dvojšachu pomůže jen tah králem.',
          zakryt: 'Jedním tahem zakryješ jen jeden šach. Proti dvojšachu pomůže jen tah králem.',
        },
        wrongDefault: 'Šach dávají dvě figurky. Jedním tahem je nezastavíš obě.',
      },
    ],
    outro: 'Figurka uhne a otevře cestu té za sebou. Tak vzniká odtažný útok, odtažný šach i dvojšach.',
    practice: [
      { kind: 'puzzles', band: 'zacatecnik', theme: 'discoveredAttack', count: 5, label: 'Úlohy: odtažný útok' },
      { kind: 'puzzles', band: 'zacatecnik', theme: 'doubleCheck', count: 5, label: 'Úlohy: dvojšach' },
    ],
  },

  {
    id: 'l2-posledni-rada',
    level: 2,
    number: 7,
    title: 'Mat na poslední řadě',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '3R2k1/p4ppp/1p6/8/8/6P1/PP3P1P/6K1 b - - 1 30',
        shapes: [{ from: 'g8', brush: 'red' }],
        text: 'Černý král je zavřený za vlastními pěšci. Věž mu dala šach na poslední řadě. Král nemá kam utéct: mat!',
      },
      {
        id: 'rook',
        kind: 'move',
        fen: '6k1/5ppp/p7/1p6/8/P7/1P3PPP/4R1K1 w - - 0 25',
        accept: ['e1e8'],
        completeness: { kind: 'mate' },
        text: 'Dej mat na poslední řadě.',
        success: 'Paráda! Král je zavřený za svými pěšci.',
        wrongDefault: 'Hledej šach na osmé řadě. Černý král za pěšci nemá kam uhnout.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '2r3k1/5ppp/p7/1p6/8/P3R3/1P3PPP/2R3K1 w - - 0 25',
        accept: ['c1c8'],
        completeness: { kind: 'mate' },
        text: 'Poslední řadu tu hlídá černá věž. Dej mat i tak.',
        success: 'Výborně! Věž vzala věž a dala mat. Nikdo jiný poslední řadu nehlídal.',
        wrong: { e3e8: 'Tohle pole hlídá černá věž c8. Vzala by tvoji věž.' },
        wrongDefault: 'Hledej, jak se dostat na osmou řadu. Třeba i braním.',
      },
      {
        id: 'window',
        kind: 'show',
        fen: '6k1/5pp1/p6p/1p6/8/P7/1P3PPP/4R1K1 w - - 0 25',
        shapes: [{ from: 'h7', brush: 'green' }],
        text: 'Tady si černý udělal okénko: posunul pěšce na h6. Po šachu na osmé řadě uteče král na h7.',
      },
      {
        id: 'is-it-mate',
        kind: 'choose',
        fen: '6k1/5p1p/p5p1/1p6/8/P7/1P3PPP/4R1K1 w - - 0 25',
        text: 'Je Ve8+ mat?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, není. Pěšec už na g7 nestojí. Král uteče do okénka na g7.',
        wrongDefault: 'Podívej se na pole g7. Nestojí tam okénko?',
      },
      {
        id: 'defend',
        kind: 'move',
        fen: '4r1k1/2R2pp1/p6p/1p6/8/P7/1P3PPP/6K1 w - - 0 26',
        movable: ['f2', 'g2', 'h2', 'b2', 'a3'],
        accept: ['f2f3', 'f2f4', 'g2g3', 'g2g4', 'h2h3', 'h2h4'],
        completeness: { kind: 'best' },
        text: 'Pozor, teď hrozí mat tobě! Černý chce hrát Ve1. Udělej svému králi okénko.',
        success: 'Výborně! Tvůj král má okénko. Po Ve1+ uteče.',
        wrongDefault: 'Tímhle tahem mat nezastavíš. Černý zahraje Ve1 a je to mat.',
      },
    ],
    outro: 'Hlídej si poslední řadu. Když máš chvilku, udělej králi okénko.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'backRankMate', count: 5, label: 'Úlohy: mat na poslední řadě' }],
  },

  {
    id: 'l2-zahajeni',
    level: 2,
    number: 8,
    title: 'Zahájení',
    steps: [
      {
        id: 'three-rules',
        kind: 'show',
        fen: START,
        shapes: [
          { from: 'd4', brush: 'green' },
          { from: 'e4', brush: 'green' },
          { from: 'd5', brush: 'green' },
          { from: 'e5', brush: 'green' },
        ],
        text: 'Zahájení je začátek partie. Tři rady: obsaď střed, vyveď figurky a udělej rošádu.',
      },
      {
        id: 'centre',
        kind: 'choose',
        fen: START,
        text: 'Kterým prvním tahem obsadíš střed?',
        options: [
          { id: 'e4', label: 'e4' },
          { id: 'a4', label: 'a4' },
          { id: 'd4', label: 'd4' },
          { id: 'h4', label: 'h4' },
        ],
        correct: ['e4', 'd4'],
        explain: 'Ano! Pěšec ve středu hlídá důležitá pole. A otevře cestu tvým figurkám.',
        wrongExplain: {
          a4: 'Pěšec a4 je na kraji. Střed jsou pole d4, e4, d5 a e5.',
          h4: 'Pěšec h4 je na kraji. Střed jsou pole d4, e4, d5 a e5.',
        },
        wrongDefault: 'Střed jsou pole d4, e4, d5 a e5.',
      },
      {
        id: 'develop',
        kind: 'move',
        fen: OPEN_GAME,
        movable: ['b1', 'f1'],
        accept: ['f1b5', 'f1c4', 'b1c3', 'f1d3', 'f1e2'],
        completeness: { kind: 'best', marginCp: 75 },
        text: 'Teď vyváděj figurky. Vyveď dalšího jezdce nebo střelce.',
        success: 'Výborně! Další figurka je ve hře.',
        wrong: { b1a3: 'Jezdec na kraji šachovnice moc nedosáhne. Najdi mu lepší pole.' },
        wrongDefault: 'Najdi figurce pole, odkud bude hlídat střed.',
      },
      {
        // Scandinavian: 1.e4 d5 2.exd5 Dxd5
        id: 'early-queen',
        kind: 'move',
        fen: 'rnb1kbnr/ppp1pppp/8/3q4/8/8/PPPP1PPP/RNBQKBNR w KQkq - 0 3',
        accept: ['b1c3'],
        completeness: { kind: 'lands', square: 'c3', from: 'b1' },
        text: 'Černý vytáhl dámu hned na začátku. Napadni ji a vyveď přitom figurku.',
        success: 'Výborně! Dáma musí zase utíkat a ty máš venku jezdce.',
        wrong: { c2c4: 'Pěšec ji taky napadne. Ale lepší je vyvést přitom figurku.' },
        wrongDefault: 'Hledej figurku, která vyjde a hned napadne dámu.',
      },
      {
        id: 'castle-why',
        kind: 'show',
        fen: ITALIAN_QUIET,
        shapes: [{ from: 'g1', brush: 'green' }],
        text: 'Rošáda schová krále do rohu za pěšce. A věž se přitom dostane do hry.',
      },
      {
        id: 'castle',
        kind: 'move',
        fen: ITALIAN_QUIET,
        accept: ['e1g1'],
        completeness: { kind: 'lands', square: 'g1', from: 'e1' },
        text: 'Udělej rošádu.',
        success: 'Výborně! Král je v bezpečí a věž f1 je připravená.',
        wrongDefault: 'Rošáda je tah králem o dvě pole k věži. Věž pak přeskočí vedle něj.',
      },
      {
        id: 'same-piece',
        kind: 'choose',
        fen: TWO_KNIGHTS,
        text: 'Který tah se tu hodí nejvíc?',
        options: [
          { id: 'jc3', label: 'Jc3' },
          { id: 'jh4', label: 'Jh4' },
          { id: 'a3', label: 'a3' },
        ],
        correct: ['jc3'],
        explain: 'Ano! Jc3 vyvede další figurku a hlídá střed.',
        wrongExplain: {
          jh4: 'Jezdec f3 už táhl. Nehraj v zahájení dvakrát stejnou figurkou. A na kraji moc nedosáhne.',
          a3: 'Pěšec na kraji nic nevyvede. Hraj figurkami do hry.',
        },
        wrongDefault: 'Vyváděj figurky, které ještě stojí doma.',
      },
    ],
    outro: 'Obsaď střed, vyveď figurky a udělej rošádu. Dámu nevyváděj brzy a netáhni dvakrát stejnou figurkou.',
    practice: [{ kind: 'play', level: 2, label: 'Zahraj si partii a hlídej si tři rady zahájení' }],
  },

  {
    id: 'l2-ovcak',
    level: 2,
    number: 9,
    title: 'Pozor na ovčáka',
    steps: [
      {
        id: 'f7',
        kind: 'show',
        fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
        shapes: [{ from: 'f7', brush: 'red' }],
        text: 'Pole f7 hlídá na začátku jen černý král. Proto je to slabé místo.',
      },
      {
        id: 'threat',
        kind: 'show',
        fen: SCHOLAR_THREAT,
        shapes: [
          { from: 'h5', to: 'f7', brush: 'red' },
          { from: 'c4', to: 'f7', brush: 'red' },
        ],
        text: 'Bílá dáma a střelec míří na f7. Hrozí Dxf7 a to je mat. Říká se mu ovčácký mat.',
      },
      {
        id: 'mate',
        kind: 'move',
        fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
        accept: ['h5f7'],
        completeness: { kind: 'mate' },
        text: 'Černý hrozbu přehlédl a zahrál Jf6. Dej mat!',
        success: 'Mat! Dámu na f7 chrání střelec, a tak ji král vzít nemůže.',
        wrongDefault: 'Černý nehlídá pole f7. Kterou figurkou tam dáš mat?',
      },
      {
        id: 'defend',
        kind: 'move',
        fen: SCHOLAR_THREAT,
        orientation: 'black',
        accept: ['g7g6', 'd8e7', 'd8f6', 'g8h6'],
        completeness: { kind: 'best', marginCp: 100 },
        text: 'Teď hraješ za černé. Bílý hrozí mat na f7. Ubraň se!',
        success: 'Výborně! Mat na f7 už nehrozí.',
        wrong: {
          d7d5: 'Mat tím na chvíli zastavíš. Ale po Sxd5 hrozí znovu a pěšec je pryč.',
          e8e7: 'Král do středu? Po Dxf7+ by byl ve velkém nebezpečí.',
        },
        wrongDefault: 'Tohle pole f7 neubrání. Bílý zahraje Dxf7 a je to mat.',
      },
      {
        // 1.e4 e5 2.Sc4 Jc6 3.Dh5 g6 4.Df3
        id: 'again',
        kind: 'move',
        fen: 'r1bqkbnr/pppp1p1p/2n3p1/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR b KQkq - 1 4',
        orientation: 'black',
        accept: ['g8f6', 'd8e7', 'g8h6', 'f7f5', 'd8f6'],
        completeness: { kind: 'best', marginCp: 60 },
        text: 'Dáma uhnula na f3 a hrozí na f7 znovu. Ubraň se ještě jednou.',
        success: 'Výborně! Útok na f7 je odražený.',
        wrong: { f7f6: 'Mat tím zastavíš. Ale pěšec f6 bere jezdci jeho nejlepší pole a oslabí krále.' },
        wrongDefault: 'Tohle pole f7 neubrání. Bílý zahraje Dxf7 a je to mat.',
      },
      {
        // 1.e4 e5 2.Jf3 Jc6 3.Sc4 Sc5
        id: 'f2',
        kind: 'show',
        fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
        shapes: [
          { from: 'c4', to: 'f7', brush: 'red' },
          { from: 'c5', to: 'f2', brush: 'red' },
        ],
        text: 'Když hraješ bílými, je stejně slabé pole f2. Hlídej si ho taky.',
      },
    ],
    outro: 'Hlídej pole f7 a f2. Když soupeř vytáhne dámu brzy, ubraň se a vyvíjej figurky.',
    practice: [{ kind: 'puzzles', band: 'zacatecnik', theme: 'attackingF2F7', count: 5, label: 'Úlohy: útok na f2 a f7' }],
  },

  {
    id: 'l2-dve-veze',
    level: 2,
    number: 10,
    title: 'Mat dvěma věžemi',
    steps: [
      {
        id: 'ladder',
        kind: 'show',
        fen: '8/8/8/4k3/R7/1R6/8/7K w - - 0 1',
        shapes: [{ from: 'a4', to: 'h4', brush: 'blue' }],
        text: 'Dvě věže dají mat i bez krále. Jedna hlídá řadu, druhá dá šach o řadu výš. Střídají se jako po žebříku.',
      },
      {
        id: 'rank5',
        kind: 'move',
        fen: '8/8/8/4k3/R7/1R6/8/7K w - - 0 1',
        accept: ['b3b5'],
        completeness: { kind: 'lands', square: 'b5', from: 'b3' },
        text: 'Věž a4 hlídá čtvrtou řadu. Dej druhou věží šach na páté řadě.',
        success: 'Výborně! Král musí o řadu výš.',
        wrong: { a4a5: 'Šach to je. Ale pak nikdo nehlídá čtvrtou řadu a král by utekl dolů.' },
        wrongDefault: 'Věž b3 má dát šach na páté řadě.',
      },
      {
        id: 'rank6',
        kind: 'move',
        fen: '8/8/5k2/1R6/R7/8/8/7K w - - 0 1',
        accept: ['a4a6'],
        completeness: { kind: 'lands', square: 'a6', from: 'a4' },
        text: 'Teď hlídá věž b5. Dej šach druhou věží na šesté řadě.',
        success: 'Výborně! Další příčka žebříku.',
        wrong: { b5b6: 'Šach to je. Ale pak nikdo nehlídá pátou řadu a král by utekl dolů.' },
        wrongDefault: 'Šach dává vždycky ta věž, která je níž.',
      },
      {
        id: 'rank7',
        kind: 'move',
        fen: '8/5k2/R7/1R6/8/8/8/7K w - - 0 1',
        accept: ['b5b7'],
        completeness: { kind: 'lands', square: 'b7', from: 'b5' },
        text: 'A zase ta druhá. Dej šach na sedmé řadě.',
        success: 'Výborně! Král je na kraji.',
        wrong: { a6a7: 'Šach to je. Ale pak nikdo nehlídá šestou řadu a král by utekl dolů.' },
        wrongDefault: 'Šach dává vždycky ta věž, která je níž.',
      },
      {
        id: 'mate',
        kind: 'move',
        fen: '5k2/1R6/R7/8/8/8/8/7K w - - 0 1',
        accept: ['a6a8'],
        completeness: { kind: 'mate' },
        text: 'Poslední příčka. Dej mat!',
        success: 'Mat! Věž b7 hlídá sedmou řadu a věž a8 dává šach.',
        wrong: { b7b8: 'Šach to je, ale ne mat. Sedmou řadu už nikdo nehlídá.' },
        wrongDefault: 'Šach dává vždycky ta věž, která je níž.',
      },
      {
        id: 'too-close',
        kind: 'show',
        fen: '8/8/8/2k5/R7/1R6/8/7K w - - 0 1',
        shapes: [{ from: 'b3', to: 'h3', brush: 'green' }],
        text: 'Pozor, tady je král blízko. Po Vb5+ by věž vzal. Odjeď s věží na druhý konec a pak pokračuj.',
      },
    ],
    outro: 'Umíš žebřík! Jedna věž hlídá, druhá dá šach o řadu výš. Až k matu.',
    practice: [{ kind: 'endgame', id: 'rr', label: 'Koncovky: dvě věže, žebřík' }],
  },

  {
    id: 'l2-dama-kral',
    level: 2,
    number: 11,
    title: 'Mat dámou a králem',
    steps: [
      {
        id: 'box',
        kind: 'show',
        fen: '8/8/5k2/3Q4/8/8/2K5/8 b - - 0 1',
        shapes: [
          { from: 'd5', to: 'd8', brush: 'blue' },
          { from: 'd5', to: 'h5', brush: 'blue' },
        ],
        text: 'Dáma postaví kolem krále krabici. Černý král nesmí přes sloupec d ani přes pátou řadu.',
      },
      {
        id: 'smaller',
        kind: 'choose',
        fen: '8/6k1/8/3Q4/8/8/2K5/8 w - - 0 1',
        text: 'Král uhnul na g7. Kam dáš dámu, aby byla krabice menší?',
        options: [
          { id: 'e6', square: 'e6' },
          { id: 'd7', square: 'd7' },
          { id: 'd8', square: 'd8' },
        ],
        correct: ['e6'],
        explain: 'Ano! Dáma stojí o skok jezdce od krále. Krabice je teď menší.',
        wrongExplain: {
          d7: 'To je šach a král uteče dolů. Dáma má stát o skok jezdce od krále.',
          d8: 'Tím krabici zvětšíš. Král pak smí dolů.',
        },
        wrongDefault: 'Postav dámu o skok jezdce od krále.',
      },
      {
        id: 'edge',
        kind: 'show',
        fen: '6k1/4Q3/8/8/8/4K3/8/8 w - - 0 1',
        text: 'Černý král je na kraji a dáma ho tam drží. Sama mat nedá. Teď přiveď svého krále.',
      },
      {
        id: 'bring-king',
        kind: 'choose',
        fen: '6k1/4Q3/8/8/8/4K3/8/8 w - - 0 1',
        text: 'Kam má jít tvůj král?',
        options: [
          { id: 'd3', square: 'd3' },
          { id: 'f4', square: 'f4' },
          { id: 'e2', square: 'e2' },
        ],
        correct: ['f4'],
        explain: 'Ano! Král jde blíž k černému králi. Pomůže dámě dát mat.',
        wrongDefault: 'Tím se král vzdálí. Má jít blíž k černému králi.',
      },
      {
        id: 'stalemate',
        kind: 'show',
        fen: '7k/5Q2/5K2/8/8/8/8/8 b - - 0 1',
        shapes: [{ from: 'h8', brush: 'yellow' }],
        text: 'Pozor na pat! Černý král není v šachu a nemá žádný tah. To je remíza, ne výhra.',
      },
      {
        id: 'mate',
        kind: 'move',
        fen: '7k/1Q6/6K1/8/8/8/8/8 w - - 0 1',
        accept: ['b7a8', 'b7b8', 'b7c8', 'b7g7', 'b7h7'],
        completeness: { kind: 'mate' },
        text: 'Dej mat. Ale pozor na pat!',
        success: 'Mat! Výborně.',
        wrong: { b7f7: 'To je pat! Černý není v šachu a nemá tah. Remíza.' },
        wrongDefault: 'Tohle ještě není mat. Hledej šach, po kterém král nemá kam utéct.',
      },
    ],
    outro: 'Dáma staví krabici, tvůj král přijde na pomoc. A než dáš mat, zkontroluj, jestli to není pat.',
    practice: [{ kind: 'endgame', id: 'kq', label: 'Koncovky: dáma a král proti králi' }],
  },

  {
    id: 'l2-vez-kral',
    level: 2,
    number: 12,
    title: 'Mat věží a králem',
    steps: [
      {
        id: 'harder',
        kind: 'show',
        fen: '4k3/8/8/8/8/8/8/R3K3 w - - 0 1',
        text: 'Tahle lekce je těžší. Klidně ji přeskoč a vrať se k ní později.',
      },
      {
        id: 'cut',
        kind: 'choose',
        fen: '8/8/8/4k3/8/8/2K5/R7 w - - 0 1',
        text: 'Věž má odříznout černého krále od tvého. Na které pole ji postavíš?',
        options: [
          { id: 'a4', square: 'a4' },
          { id: 'a5', square: 'a5' },
          { id: 'a6', square: 'a6' },
        ],
        correct: ['a4'],
        explain: 'Ano! Věž hlídá čtvrtou řadu. Černý král už nesmí dolů.',
        wrongExplain: {
          a5: 'To je šach. Král pak uteče nahoru nebo dolů.',
          a6: 'Tím zavřeš cestu nahoru. Ale dolů k tvému králi smí dál.',
        },
        wrongDefault: 'Věž má hlídat řadu mezi oběma králi.',
      },
      {
        id: 'picture',
        kind: 'show',
        fen: 'R3k3/8/4K3/8/8/8/8/8 b - - 1 1',
        shapes: [{ from: 'e8', brush: 'red' }],
        text: 'Takhle vypadá mat. Černý král je na kraji a králové stojí proti sobě. Věž dá šach po celé řadě.',
      },
      {
        id: 'mate',
        kind: 'move',
        fen: '3k4/8/3K4/8/8/8/7R/8 w - - 0 1',
        accept: ['h2h8'],
        completeness: { kind: 'mate' },
        text: 'Králové stojí proti sobě. Dej mat!',
        success: 'Mat! Tvůj král hlídá sedmou řadu a věž dává šach.',
        wrongDefault: 'Dej věží šach po osmé řadě.',
      },
      {
        id: 'not-yet',
        kind: 'choose',
        fen: '5k2/8/4K3/8/8/8/8/R7 w - - 0 1',
        text: 'Je teď Va8+ mat?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, není. Králové nestojí proti sobě. Černý uteče na g7.',
        wrongDefault: 'Podívej se na pole g7. Hlídá ho někdo?',
      },
      {
        id: 'plan',
        kind: 'show',
        fen: '4k3/8/8/8/8/8/8/R3K3 w - - 0 1',
        text: 'Postup: věž odřízne krále, tvůj král jde naproti. Když stojí králové proti sobě, věž dá šach. Vyzkoušej to v Koncovkách.',
      },
    ],
    outro: 'Mat věží je těžší. Nevadí, když ho zatím neumíš. Vrať se k němu, až budeš chtít.',
    practice: [{ kind: 'endgame', id: 'kr', label: 'Koncovky: věž a král proti králi' }],
  },

  {
    id: 'l2-rozbor',
    level: 2,
    number: 13,
    title: 'Rozbor vlastní partie',
    steps: [
      {
        id: 'why',
        kind: 'show',
        fen: START,
        text: 'Každá partie tě něco naučí. Nejvíc se naučíš ze svých chyb.',
      },
      {
        id: 'where',
        kind: 'show',
        fen: START,
        text: 'Zahraj si partii. Když skončí, objeví se tlačítko Rozbor. Starší partie najdeš pod tlačítkem Partie.',
      },
      {
        id: 'analyse',
        kind: 'show',
        fen: START,
        text: 'V Rozboru klikni na Analyzovat partii. Počítač projde každý tah. Proužek vedle šachovnice ukáže, kdo stojí lépe.',
      },
      {
        id: 'arrow',
        kind: 'show',
        fen: SCHOLAR_THREAT,
        shapes: [{ from: 'g7', to: 'g6', brush: 'green' }],
        text: 'Šipka ukáže lepší tah. Tady černý zahrál Jf6 a dostal mat. Šipka radí g6.',
      },
      {
        id: 'glyph',
        kind: 'choose',
        fen: START,
        text: 'Co znamenají dva otazníky ?? za tahem?',
        options: [
          { id: 'chyba', label: 'Hrubá chyba' },
          { id: 'skvely', label: 'Skvělý tah' },
          { id: 'sach', label: 'Šach' },
        ],
        correct: ['chyba'],
        explain: 'Ano! ?? je hrubá chyba. Jeden vykřičník ! je skvělý tah.',
        wrongExplain: {
          skvely: 'Skvělý tah má vykřičník !. Otazníky znamenají chybu.',
          sach: 'Šach se píše +. Otazníky znamenají chybu.',
        },
        wrongDefault: 'Otazníky znamenají chybu.',
      },
      {
        id: 'ask',
        kind: 'show',
        fen: START,
        text: 'U každé hrubé chyby se zastav. Zeptej se: Co mi hrozilo? A jaký tah byl lepší?',
      },
    ],
    outro: 'Rozbor je jako trenér, který má čas na každý tvůj tah. Používej ho po každé partii.',
    practice: [{ kind: 'play', level: 1, label: 'Zahraj si partii a pak ji rozeber' }],
  },

  {
    id: 'l2-zkouska',
    level: 2,
    number: 14,
    title: 'Zkouška úrovně 2',
    test: {
      passScore: 8,
      badge: 'l2',
      failOutro: 'Tentokrát to nevyšlo. Podívej se znovu na lekce, které ti dělaly potíže, a zkus to znovu.',
    },
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: START,
        text: 'Zkouška úrovně 2! Čeká tě 10 úloh. Na každou máš jen jeden pokus a žádnou nápovědu. Když zvládneš aspoň 8, získáš odznak a diplom.',
      },
      {
        // 1.e4 e5 2.Jf3 — read the notation, play the move.
        id: 'notation',
        kind: 'move',
        fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 3 2',
        accept: ['b8c6'],
        completeness: { kind: 'lands', square: 'c6', from: 'b8' },
        text: 'Přečti zápis a zahraj tah: Jc6.',
        success: 'Správně! Jezdec b8 šel na pole c6.',
        wrongDefault: 'Jc6 znamená: jezdec jde na pole c6. Který jezdec tam dosáhne?',
      },
      {
        id: 'hrozi',
        kind: 'choose',
        fen: 'r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3',
        text: 'Bílý zahrál Dh5. Co bílému teď hrozí?',
        options: [
          { id: 'mat', label: 'Mat na f7' },
          { id: 'e5', label: 'Vzít pěšce e5' },
          { id: 'nic', label: 'Nic nehrozí' },
        ],
        correct: ['mat'],
        explain: 'Ano! Dáma a střelec míří na f7. Hrozí Dxf7 a to je mat.',
        wrongExplain: {
          e5: 'Pěšec e5 dámu nenapadá. Podívej se, kam míří dáma a střelec.',
          nic: 'Pozor, hrozí! Podívej se, kam míří dáma a střelec.',
        },
        wrongDefault: 'Podívej se, kam míří dáma a střelec.',
      },
      {
        // Damiano: 1.e4 e5 2.Jf3 f6? 3.Jxe5 fxe5 4.Dh5+ g6 — double attack with the queen.
        id: 'utok',
        kind: 'move',
        fen: 'rnbqkbnr/pppp3p/6p1/4p2Q/4P3/8/PPPP1PPP/RNB1KB1R w KQkq - 0 5',
        accept: ['h5e5'],
        completeness: { kind: 'best' },
        text: 'Najdi dvojný útok dámou.',
        success: 'Paráda! Šach a zároveň útok na věž h8.',
        wrongDefault: 'Hledej tah dámou, který napadne dvě věci naráz. Jedna z nich je král.',
      },
      {
        // Lichess puzzle wvGrh — a knight fork on king and queen.
        id: 'vidlicka',
        kind: 'move',
        fen: '8/6p1/p2k3p/1p4q1/5n2/4Q1NP/P4PP1/6K1 w - - 0 34',
        accept: ['g3e4'],
        completeness: { kind: 'best' },
        text: 'Najdi vidličku jezdcem.',
        success: 'Paráda! Šach a útok na dámu naráz.',
        wrongDefault: 'Hledej skok jezdce, který napadne dvě černé figurky naráz.',
      },
      {
        // Steinitz: 1.e4 e5 2.Jf3 Jc6 3.Sb5 d6 — the knight is pinned to the king.
        id: 'vazba',
        kind: 'choose',
        fen: 'r1bqkbnr/ppp2ppp/2np4/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
        text: 'Smí černý jezdec c6 táhnout?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nesmí. Jeho král by pak byl v šachu.',
        wrongDefault: 'Kdyby jezdec uhnul, střelec by dával šach králi.',
      },
      {
        // Petroff: 1.e4 e5 2.Jf3 Jf6 3.Jxe5 Jxe4? 4.De2 — a discovered check.
        id: 'odtazny',
        kind: 'move',
        fen: 'rnbqkb1r/pppp1ppp/5n2/4N3/8/8/PPPPQPPP/RNB1KB1R w KQkq - 2 5',
        accept: ['e5c6'],
        completeness: { kind: 'best' },
        text: 'Uhni jezdcem tak, aby dal šach a napadl něco velkého.',
        success: 'Paráda! Dáma dává šach a jezdec napadá dámu d8.',
        wrongDefault: 'Uhni jezdcem tak, aby napadl černou dámu.',
      },
      {
        id: 'rada',
        kind: 'move',
        fen: '6k1/5ppp/p7/1p6/8/P7/1P3PPP/4R1K1 w - - 0 25',
        accept: ['e1e8'],
        completeness: { kind: 'mate' },
        text: 'Dej mat na poslední řadě.',
        success: 'Mat! Černý král je zavřený za svými pěšci.',
        wrongDefault: 'Hledej šach na osmé řadě.',
      },
      {
        // 1.e4 e5 2.Jf3 Jc6 3.Sc4 Jf6 — develop another piece, not the edge knight again.
        id: 'zahajeni',
        kind: 'choose',
        fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
        text: 'Který tah se tu hodí nejvíc?',
        options: [
          { id: 'jc3', label: 'Jc3' },
          { id: 'jh4', label: 'Jh4' },
          { id: 'a3', label: 'a3' },
        ],
        correct: ['jc3'],
        explain: 'Ano! Jc3 vyvede další figurku a hlídá střed.',
        wrongDefault: 'Vyváděj figurky, které ještě stojí doma.',
      },
      {
        // 1.e4 e5 2.Sc4 Jc6 3.Dh5 g6 4.Df3 — defend against the second ovčácký mat try.
        id: 'ovcak',
        kind: 'move',
        fen: 'r1bqkbnr/pppp1p1p/2n3p1/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR b KQkq - 1 4',
        orientation: 'black',
        accept: ['g8f6', 'd8e7', 'g8h6', 'f7f5', 'd8f6'],
        completeness: { kind: 'best', marginCp: 60 },
        text: 'Bílý hrozí na f7. Ubraň se.',
        success: 'Výborně! Útok na f7 je odražený.',
        wrongDefault: 'Tohle pole f7 neubrání. Bílý zahraje Dxf7 a je to mat.',
      },
      {
        id: 'mat',
        kind: 'move',
        fen: '7k/1Q6/6K1/8/8/8/8/8 w - - 0 1',
        accept: ['b7a8', 'b7b8', 'b7c8', 'b7g7', 'b7h7'],
        completeness: { kind: 'mate' },
        text: 'Dej mat. Ale pozor na pat!',
        success: 'Mat! Výborně.',
        wrongDefault: 'Tohle ještě není mat. Hledej šach, po kterém král nemá kam utéct.',
      },
    ],
    outro: 'Zkouška je za tebou! Odznak je tvůj a můžeš si vytisknout diplom.',
    practice: [
      { kind: 'play', level: 3, label: 'Zahraj si partii proti silnějšímu soupeři' },
      { kind: 'puzzles', band: 'zacatecnik', count: 10, label: 'Úlohy: víc taktiky' },
    ],
  },
];
