/**
 * Level 3 — Mírně pokročilý, lessons 1–13 (docs/phase-22-plan.md, curriculum). Tactics
 * (odstranění obránce, přetížení, odlákání, vlákání, rentgen, chycená figurka, mezitah),
 * mate patterns, mate in 2, and the first two pawn-endgame ideas (opozice, pravidlo
 * čtverce). Lesson 13 is the level test. Positions are game-like: simplified middlegames
 * (several from the Lichess puzzle database, CC0; the id is noted) and two classic
 * traps (Légal, Morphy's Opera Game) verified move by move with chess.js. Every tactic
 * task is checked by `npm run check:lessons`: mates with `mate`, "win material" tasks
 * with `best` (Stockfish: no other move within the margin). Texts: informal „ty“, short
 * sentences, Czech letters (K D V S J), 0-0.
 */
import type { Lesson } from './types';

export const LEVEL3: readonly Lesson[] = [
  {
    id: 'l3-odstraneni-obrance',
    level: 3,
    number: 1,
    title: 'Odstranění obránce',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '2kr3r/ppp2ppp/8/2b5/8/2N5/PPP2PPP/2KR3R w - - 0 1',
        shapes: [
          { from: 'c3', to: 'c5', brush: 'blue' },
          { from: 'd8', brush: 'red' },
        ],
        text: 'Věž d8 hlídá pole d1. Kdyby zmizela, tvoje věž by se tam dostala. Takové hlídačce se říká obránce.',
      },
      {
        // Lichess puzzle INSwD, after 32.Nc7.
        id: 'take-guard',
        kind: 'move',
        fen: '4r2k/1pNr2pp/4q3/4P3/2QP4/1P3R1P/P5P1/6K1 b - - 6 32',
        accept: ['e6c4'],
        completeness: { kind: 'best' },
        text: 'Bílá dáma c4 hlídá jezdce c7. Vezmi ji.',
        success: 'Paráda! Po bxc4 je jezdec c7 bez obrany. Věž d7 ho příště sebere.',
        wrongDefault: 'Hledej tah dámou, po kterém bude jezdec c7 bez obrany.',
      },
      {
        // Lichess puzzle HKPPH.
        id: 'combo',
        kind: 'move',
        fen: 'r2r2k1/pp2ppbp/2n5/2pNN2n/2P5/7P/PP3PP1/R1B1K2R w KQ - 2 15',
        accept: ['e5c6'],
        completeness: { kind: 'best' },
        text: 'Jezdec c6 hlídá pole e7 a d8. Vezmi ho a uvolni cestu druhému jezdci.',
        success: 'Paráda! Po bxc6 skočí druhý jezdec Jxe7+ a vezme si věž d8.',
        wrongDefault: 'Hledej tah, který sebere jezdce c6. Ten hlídá důležitá pole.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: 'r5k1/1pn3pp/8/3N4/8/8/1P4PP/R5K1 w - - 0 1',
        text: 'Věž a1 už teď útočí na věž a8. Kterou figurku musíš vzít nejdřív, aby zůstala tvoje věž?',
        options: [
          { id: 'c7', square: 'c7' },
          { id: 'a8', square: 'a8' },
          { id: 'b7', square: 'b7' },
        ],
        correct: ['c7'],
        explain: 'Ano! Jezdec c7 hlídá věž a8. Vezmi jezdce, a věž a8 je pak tvoje zadarmo.',
        wrongExplain: {
          a8: 'Tím by sis jen vyměnil věž za věž. Jezdec c7 věž a8 hlídá.',
          b7: 'Pěšec b7 věž a8 nehlídá.',
        },
        wrongDefault: 'Hledej figurku, která hlídá věž a8.',
      },
      {
        id: 'defender-of-king',
        kind: 'show',
        fen: '2kr3r/ppp2ppp/8/2b5/8/2N5/PPP2PPP/2KR3R w - - 0 1',
        shapes: [
          { from: 'c8', brush: 'red' },
          { from: 'd8', brush: 'blue' },
        ],
        text: 'Obráncem může být pěšec, jezdec, dáma, i vlastní král. Tady král c8 hlídá věž d8. Vždycky se ptej: kdo tohle pole hlídá?',
      },
    ],
    outro: 'Než zaútočíš na figurku, podívej se, kdo ji hlídá. Sundej obránce, a figurka je tvoje.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'capturingDefender', count: 5, label: 'Úlohy: odstranění obránce' }],
  },

  {
    id: 'l3-pretizeni',
    level: 3,
    number: 2,
    title: 'Přetížení',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        shapes: [
          { from: 'd8', to: 'd5', brush: 'blue' },
          { from: 'd8', to: 'b8', brush: 'blue' },
        ],
        text: 'Věž d8 hlídá dvě věci najednou: jezdce d5 i střelce b8. Tomu se říká přetížení.',
      },
      {
        id: 'win',
        kind: 'move',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        accept: ['a7b8'],
        completeness: { kind: 'best' },
        text: 'Věž nestíhá obě práce. Zaútoč na jednu z nich.',
        success: 'Výborně! Věž musí vzít zpátky Vxb8, a pak už nehlídá jezdce d5. Vxd5 ho příště sebere zadarmo.',
        wrongDefault: 'Zaútoč na střelce b8, nebo na jezdce d5. Věž d8 hlídá obojí a na obojí nestačí.',
      },
      {
        id: 'which-overloaded',
        kind: 'choose',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        text: 'Která figurka je přetížená?',
        options: [
          { id: 'd8', square: 'd8' },
          { id: 'd5', square: 'd5' },
          { id: 'a7', square: 'a7' },
        ],
        correct: ['d8'],
        explain: 'Ano! Věž d8 musí hlídat jezdce i střelce najednou. Na obojí nestačí.',
        wrongExplain: {
          d5: 'Jezdec d5 nikoho nehlídá, jenom je hlídaný.',
          a7: 'Střelec a7 je tvoje figurka, žádnou práci navíc nemá.',
        },
        wrongDefault: 'Hledej figurku, která hlídá dvě věci najednou.',
      },
      {
        // Lichess puzzle exQ1C.
        id: 'rook-idea',
        kind: 'show',
        fen: '2r1r3/5kp1/p4n1p/P2p4/6P1/P1B1R2P/2P5/2K1R3 b - - 2 26',
        shapes: [
          { from: 'e3', to: 'c3', brush: 'blue' },
          { from: 'e3', to: 'e1', brush: 'blue' },
        ],
        text: 'Bílá věž e3 taky hlídá dvě věci: střelce c3 a věž e1. Najdi, jak toho využít.',
      },
      {
        id: 'rook',
        kind: 'move',
        fen: '2r1r3/5kp1/p4n1p/P2p4/6P1/P1B1R2P/2P5/2K1R3 b - - 2 26',
        accept: ['c8c3'],
        completeness: { kind: 'best' },
        text: 'Zaútoč na střelce c3.',
        success: 'Paráda! Po Vxc3 věž e3 zmizí z e-sloupce a Vxe1 sebereš druhou věž.',
        wrongDefault: 'Vezmi střelce c3. Věž e3 ho hlídá, ale hlídá i věž e1.',
      },
    ],
    outro: 'Když jedna figurka hlídá dvě věci, zaútoč na jednu z nich. Na obě nestačí.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'deflection', count: 5, label: 'Úlohy: přetížení a odlákání' }],
  },

  {
    id: 'l3-odlakani',
    level: 3,
    number: 3,
    title: 'Odlákání',
    steps: [
      {
        // Lichess puzzle 2warR, before 43.Rd7-d5.
        id: 'idea',
        kind: 'show',
        fen: '8/2pRP3/1p6/1P2rk1p/7p/8/5KP1/8 w - - 1 43',
        shapes: [{ from: 'e5', to: 'e7', brush: 'red' }],
        text: 'Věž e5 hlídá pole před pěšcem. Bez ní pěšec projde a promění se. Musíš ji odlákat.',
      },
      {
        id: 'lure',
        kind: 'move',
        fen: '8/2pRP3/1p6/1P2rk1p/7p/8/5KP1/8 w - - 1 43',
        accept: ['d7d5'],
        completeness: { kind: 'best' },
        text: 'Dej šach věží. Věž e5 ho musí vzít, a tím uvolní cestu pěšci.',
        success: 'Výborně! Po Vxd5 už nikdo nehlídá pole e8. Pěšec se promění v dámu.',
        wrongDefault: 'Hledej šach věží, po kterém musí černá věž vzít a odejít od pěšce.',
      },
      {
        // Lichess puzzle 9OVqg, before 57.Rf4-f5.
        id: 'idea2',
        kind: 'show',
        fen: '8/2P5/8/1kr5/p4R2/8/4K3/8 w - - 2 57',
        shapes: [{ from: 'c5', to: 'c8', brush: 'red' }],
        text: 'Tady zase věž c5 hlídá cestu bílému pěšci k proměně. Odlákej ji.',
      },
      {
        id: 'lure2',
        kind: 'move',
        fen: '8/2P5/8/1kr5/p4R2/8/4K3/8 w - - 2 57',
        accept: ['f4f5'],
        completeness: { kind: 'best' },
        text: 'Nabídni věži výměnu na páté řadě.',
        success: 'Paráda! Věž musí vzít, jinak přijde Vf7 a pěšec se stejně promění. Po Vxf5 pěšec c8D vyhrává.',
        wrongDefault: 'Nabídni svoji věž na páté řadě. Černá věž ji musí vzít, a pak už nehlídá pěšce.',
      },
      {
        id: 'not-attraction',
        kind: 'choose',
        fen: '8/2pRP3/1p6/1P2rk1p/7p/8/5KP1/8 w - - 1 43',
        text: 'Proč věž e5 musí vzít na d5?',
        options: [
          { id: 'jina', label: 'Jinak přijde o věž zadarmo, nebo pěšec projde' },
          { id: 'nemusi', label: 'Nemusí, může klidně nechat pěšce jít' },
          { id: 'pat', label: 'Protože jinak je to pat' },
        ],
        correct: ['jina'],
        explain: 'Přesně tak. Braní stojí věž, ale nebranit stojí celou partii — pěšec se promění.',
        wrongExplain: {
          nemusi: 'Musí. Bez věže na e5 pěšec e7 dojde na e8 a promění se v dámu.',
          pat: 'O pat tu nejde. Černý má i jiné tahy, jen jsou všechny horší.',
        },
        wrongDefault: 'Podívej se, co se stane, když věž e5 pěšce nechá být.',
      },
    ],
    outro: 'Odlákej figurku, která něco hlídá, i za cenu výměny. Bez ní se ti otevře cesta.',
    practice: [
      { kind: 'puzzles', band: 'lehke', theme: 'deflection', count: 5, label: 'Úlohy: odlákání' },
      { kind: 'endgame', id: 'race', label: 'Koncovky: utíkej s pěšcem' },
    ],
  },

  {
    id: 'l3-vlakani',
    level: 3,
    number: 4,
    title: 'Vlákání',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: 'rn1q1bnr/ppp1kB1p/3p2p1/4N3/4P3/2N5/PPPP1PPP/R1BbK2R w KQ - 1 7',
        shapes: [{ from: 'f7', to: 'e7', brush: 'red' }],
        text: 'Vlákání je opak odlákání: nalákáš figurku (často krále) na špatné pole. Král tu musel na e7.',
      },
      {
        // Légal's trap: 1.e4 e5 2.Jf3 d6 3.Sc4 Sg4 4.Jc3 g6 5.Jxe5!? Sxd1 6.Sxf7+ Ke7 7.Jd5#.
        id: 'legal',
        kind: 'move',
        fen: 'rn1q1bnr/ppp1kB1p/3p2p1/4N3/4P3/2N5/PPPP1PPP/R1BbK2R w KQ - 1 7',
        accept: ['c3d5'],
        completeness: { kind: 'mate' },
        text: 'Černý vzal zadarmo dámu, ale jeho král skončil na e7. Dej mat!',
        success: 'Mat! Král na e7 nemá kam utéct, jezdec d5 hlídá i pole e7 okolí.',
        wrongDefault: 'Král stojí na e7. Hledej skok jezdce, který ho tam zamatuje.',
      },
      {
        id: 'opera-idea',
        kind: 'show',
        fen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
        shapes: [
          { from: 'b3', to: 'b8', brush: 'blue' },
          { from: 'd1', to: 'd8', brush: 'red' },
        ],
        text: 'Slavná partie: Morphy hraje bílými. Chce dostat věž na d8. Jezdec d7 mu ale kryje pole d8.',
      },
      {
        // Morphy's "Opera Game" (Paris, 1858), 16.Qb8+!
        id: 'opera-sac',
        kind: 'move',
        fen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
        accept: ['b3b8'],
        completeness: { kind: 'best' },
        text: 'Obětuj dámu šachem. Nalákej jezdce d7 na pole b8.',
        success: 'Paráda! Jezdec musí vzít Jxb8. Teď už pole d8 nikdo nehlídá.',
        wrongDefault: 'Hledej šach dámou, který nalákal jezdce d7 pryč od pole d8.',
      },
      {
        id: 'opera-mate',
        kind: 'move',
        fen: '1n2kb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 w k - 0 17',
        accept: ['d1d8'],
        completeness: { kind: 'mate' },
        text: 'Jezdec je teď na b8, ne na d8. Dej mat!',
        success: 'Mat! Král je zavřený mezi svými figurkami a věž hlídá celou poslední řadu.',
        wrongDefault: 'Pole d8 už nikdo nehlídá. Dej tam šach věží.',
      },
      {
        id: 'why',
        kind: 'choose',
        fen: '1n2kb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 w k - 0 17',
        text: 'Proč Morphy obětoval dámu na b8?',
        options: [
          { id: 'odlakat', label: 'Aby odlákal jezdce z pole d8' },
          { id: 'zadarmo', label: 'Protože dáma byla stejně napadená' },
          { id: 'omyl', label: 'Byl to omyl, dámu ztratil zbytečně' },
        ],
        correct: ['odlakat'],
        explain: 'Ano! Jezdec d7 hlídal pole d8. Obětí ho Morphy odlákal a uvolnil cestu k matu.',
        wrongExplain: {
          zadarmo: 'Dáma napadená nebyla. Šlo o to nalákat jezdce na pole b8.',
          omyl: 'Nebyl to omyl. Za dámu Morphy dostal mat.',
        },
        wrongDefault: 'Podívej se, co jezdec d7 hlídal, než šel na b8.',
      },
    ],
    outro: 'Vlákání i odlákání mění stráž na poli, které potřebuješ. Klidně za to zaplať figurku.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'attraction', count: 5, label: 'Úlohy: vlákání' }],
  },

  {
    id: 'l3-rentgen',
    level: 3,
    number: 5,
    title: 'Rentgen',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '4q3/pp4pp/8/4k3/8/6K1/PP5P/7R w - - 0 1',
        shapes: [{ from: 'h1', to: 'e8', brush: 'blue' }],
        text: 'Rentgen: napadneš krále, a za ním na stejné čáře stojí dáma. Král uhne, dáma padne.',
      },
      {
        id: 'check',
        kind: 'move',
        fen: '4q3/pp4pp/8/4k3/8/6K1/PP5P/7R w - - 0 1',
        accept: ['h1e1'],
        completeness: { kind: 'best' },
        text: 'Dej šach věží po sloupci e. Král dámu zakrýt nemůže, stojí jí v cestě.',
        success: 'Výborně! Král musí pryč a věž si dámu vezme.',
        wrongDefault: 'Hledej šach po sloupci e. Král uhne a dáma za ním padne.',
      },
      {
        id: 'not-pin',
        kind: 'show',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        shapes: [{ from: 'd3', to: 'e8', brush: 'blue' }],
        text: 'Pozor na rozdíl od vazby: u rentgenu je vpředu ta cennější figurka. U vazby je vzadu král.',
      },
      {
        // Lichess puzzle HMT0w.
        id: 'bishop',
        kind: 'move',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        accept: ['d3b5'],
        completeness: { kind: 'best' },
        text: 'Najdi rentgen střelcem. Napadá dámu i věž za ní.',
        success: 'Paráda! Dáma musí uhnout a střelec pak sebere věž e8.',
        wrongDefault: 'Hledej tah střelcem, který napadne dámu c6 a přes ni míří na věž e8.',
      },
      {
        id: 'which-bigger',
        kind: 'choose',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        text: 'Co udělá černá dáma, když ji střelec napadne?',
        options: [
          { id: 'uhne', label: 'Uhne, věž za ní padne' },
          { id: 'nesmi', label: 'Nesmí táhnout, je vázaná' },
          { id: 'vezme', label: 'Vezme střelce zadarmo' },
        ],
        correct: ['uhne'],
        explain: 'Ano. Dáma není vázaná ke králi, smí uhnout. Ale pak přijde o věž e8.',
        wrongExplain: {
          nesmi: 'Vázaná není, za dámou stojí věž, ne král. Klidně uhne.',
          vezme: 'Střelce hlídá věž b3, brát ho se nevyplatí.',
        },
        wrongDefault: 'Dáma není vázaná. Podívej se, co za ní stojí.',
      },
    ],
    outro: 'Rentgen: napadni cennější figurku, a méně cenná za ní ti spadne do klína.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'skewer', count: 5, label: 'Úlohy: rentgen' }],
  },

  {
    id: 'l3-chycena-figurka',
    level: 3,
    number: 6,
    title: 'Chycená figurka',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: 'n5k1/2p2ppp/1p6/8/8/8/1PPPPPPP/R5K1 w - - 0 1',
        shapes: [
          { from: 'a8', to: 'b6', brush: 'red' },
          { from: 'a8', to: 'c7', brush: 'red' },
        ],
        text: 'Jezdec smí skočit jen na b6 nebo c7. Obě pole hlídají vlastní pěšci. Jezdec je chycený.',
      },
      {
        id: 'win',
        kind: 'move',
        fen: 'n5k1/2p2ppp/1p6/8/8/8/1PPPPPPP/R5K1 w - - 0 1',
        accept: ['a1a8'],
        completeness: { kind: 'best' },
        text: 'Jezdec nemá kam utéct. Vezmi ho.',
        success: 'Výborně! Jezdec neměl jediný tah, a teď je tvůj.',
        wrongDefault: 'Jezdec a8 nemá žádné pole, kam by mohl skočit. Vezmi ho.',
      },
      {
        id: 'idea2',
        kind: 'show',
        fen: '6k1/6pb/6p1/8/8/8/6PP/6K1 w - - 0 1',
        shapes: [{ from: 'h7', to: 'g6', brush: 'red' }],
        text: 'Stejně tak střelec h7. Vlastní pěšec g6 mu stojí v cestě, dál se nedostane.',
      },
      {
        id: 'which-trapped',
        kind: 'choose',
        fen: 'n5k1/2p2ppp/1p6/8/8/8/1PPPPPPP/R5K1 w - - 0 1',
        text: 'Která figurka je chycená?',
        options: [
          { id: 'a8', square: 'a8' },
          { id: 'b6', square: 'b6' },
          { id: 'c7', square: 'c7' },
        ],
        correct: ['a8'],
        explain: 'Ano! Jezdec a8 nemá jediné volné pole, kam by mohl skočit.',
        wrongExplain: {
          b6: 'Pěšec b6 chycený není, jen hlídá.',
          c7: 'Pěšec c7 chycený není, jen hlídá.',
        },
        wrongDefault: 'Hledej figurku, která nemá žádné volné pole.',
      },
      {
        id: 'why-search',
        kind: 'show',
        fen: 'n5k1/2p2ppp/1p6/8/8/8/1PPPPPPP/R5K1 w - - 0 1',
        text: 'Chycenou figurku hledej hlavně u kraje šachovnice. Uprostřed má každá figurka víc polí na útěk.',
      },
    ],
    outro: 'Chycená figurka nemá kam utéct. Nemusíš spěchat, klidně si na ni došlápni v klidu.',
    practice: [{ kind: 'puzzles', band: 'stredni', theme: 'trappedPiece', count: 5, label: 'Úlohy: chycená figurka' }],
  },

  {
    id: 'l3-mezitah',
    level: 3,
    number: 7,
    title: 'Mezitah',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        shapes: [{ from: 'f8', to: 'b4', brush: 'green' }],
        text: 'Bílý právě vzal tvoji dámu. Než ji vezmeš zpátky, zkus mezitah: silnější tah navíc.',
      },
      {
        // The "Elephant Trap" in the Queen's Gambit Declined: 1.d4 d5 2.c4 e6 3.Nc3 Nf6
        // 4.Bg5 Nbd7 5.cxd5 exd5 6.Nxd5?? Nxd5 7.Bxd8?? Bb4+! 8.Qd2 Bxd2+ 9.Kxd2 Kxd8.
        id: 'trap',
        kind: 'move',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        accept: ['f8b4'],
        completeness: { kind: 'best' },
        text: 'Nech dámu na d8 chvíli ležet. Dej šach střelcem.',
        success: 'Paráda! Po Dd2 Sxd2+ Kxd2 teprve vezmeš Kxd8. Máš tak o figurku víc, než kdybys bral hned.',
        wrongDefault: 'Bílá dáma na d8 nikam neuteče. Nejdřív dej šach střelcem na b4.',
      },
      {
        // Lichess puzzle 0JZ3N.
        id: 'rook-idea',
        kind: 'show',
        fen: 'r7/1ppnk3/p3p2p/4r1p1/4R3/6N1/PPP3PP/3R2K1 w - - 0 23',
        shapes: [{ from: 'd1', to: 'd7', brush: 'green' }],
        text: 'Věž e4 by mohla hned vzít věž e5. Ale nejdřív se podívej na šach na d7.',
      },
      {
        id: 'rook',
        kind: 'move',
        fen: 'r7/1ppnk3/p3p2p/4r1p1/4R3/6N1/PPP3PP/3R2K1 w - - 0 23',
        accept: ['d1d7'],
        completeness: { kind: 'best' },
        text: 'Zahraj mezitah. Nevezmi rovnou, dej nejdřív šach.',
        success: 'Výborně! Král musí vzít Kxd7, a pak teprve vezmeš Vxe5.',
        wrongDefault: 'Věž e5 ti neuteče. Nejdřív dej šach věží na d7.',
      },
      {
        id: 'when',
        kind: 'choose',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        text: 'Kdy se mezitah hodí nejvíc?',
        options: [
          { id: 'silnejsi', label: 'Když máš tah silnější než obyčejné braní zpátky' },
          { id: 'vzdy', label: 'Vždycky, braní zpátky nikdy nepospíchá' },
          { id: 'nikdy', label: 'Nikdy, vždycky ber zpátky hned' },
        ],
        correct: ['silnejsi'],
        explain: 'Ano! Mezitah hraješ, jen když máš po ruce tah se šachem nebo hrozbou.',
        wrongExplain: {
          vzdy: 'Někdy je nutné vzít rovnou, jinak přijdeš o víc.',
          nikdy: 'Někdy se ti mezitah vyplatí víc než braní hned.',
        },
        wrongDefault: 'Mezitah funguje jen s tahem, který soupeře donutí reagovat: šach nebo velká hrozba.',
      },
    ],
    outro: 'Než vezmeš zpátky, rozhlédni se. Máš po ruce šach nebo hrozbu? Zahraj ji nejdřív.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'intermezzo', count: 5, label: 'Úlohy: mezitah' }],
  },

  {
    id: 'l3-matove-obrazce-1',
    level: 3,
    number: 8,
    title: 'Matové obrazce I',
    steps: [
      {
        id: 'smothered-idea',
        kind: 'show',
        fen: '5r1k/6pp/7N/3Q4/8/8/8/6K1 w - - 0 1',
        shapes: [
          { from: 'g8', brush: 'red' },
          { from: 'g7', brush: 'red' },
          { from: 'h7', brush: 'red' },
        ],
        text: 'Dušený mat: krále obklopí vlastní figurky. Nemůže uhnout, i kdyby chtěl.',
      },
      {
        id: 'smothered-sac',
        kind: 'move',
        fen: '5r1k/6pp/7N/3Q4/8/8/8/6K1 w - - 0 1',
        movable: ['d5'],
        accept: ['d5g8'],
        completeness: { kind: 'best' },
        text: 'Obětuj dámu šachem na g8. Přinuť věž zpátky ke králi.',
        success: 'Výborně! Věž musí vzít, jinak je to hned mat. A tím se král udusí úplně.',
        wrongDefault: 'Hledej šach dámou na g8. Král ho vzít nemůže, jezdec h6 pole hlídá.',
      },
      {
        id: 'smothered-mate',
        kind: 'move',
        fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 2',
        accept: ['h6f7'],
        completeness: { kind: 'mate' },
        text: 'Král je teď obklopený vlastní věží a pěšci. Dej dušený mat.',
        success: 'Mat! Král nemá jediné volné pole, a jezdce nemá čím vzít.',
        wrongDefault: 'Skoč jezdcem tak, aby dal šach. Král se nemá kam hnout.',
      },
      {
        // Lichess puzzle PC9fl, after 39...Ne2+ 40.Kh2.
        id: 'anastasia-idea',
        kind: 'show',
        fen: '5r1k/1p4p1/p5Qp/2P5/2N1pr2/P3N3/4n1PK/8 b - - 4 40',
        shapes: [{ from: 'h4', to: 'h2', brush: 'blue' }],
        text: 'Anastasiin mat: král stojí na kraji, jezdec mu hlídá únik. Věž dá šach po řadě nebo sloupci.',
      },
      {
        id: 'anastasia-mate',
        kind: 'move',
        fen: '5r1k/1p4p1/p5Qp/2P5/2N1pr2/P3N3/4n1PK/8 b - - 4 40',
        accept: ['f4h4'],
        completeness: { kind: 'mate' },
        text: 'Jezdec e2 hlídá krále. Dej mat věží.',
        success: 'Mat! Král na h2 nemá kam utéct, jezdec e2 mu hlídá g1 i g3.',
        wrongDefault: 'Přesuň věž na sloupec h. Král uteče jen tam, kde ho nehlídá jezdec.',
      },
      {
        // Lichess puzzle JupYf, after 38...a2.
        id: 'arabian-idea',
        kind: 'show',
        fen: 'r6k/1p3R2/1p2pN1p/8/8/8/p5PP/7K w - - 0 39',
        shapes: [{ from: 'f7', to: 'h7', brush: 'blue' }],
        text: 'Arabský mat: jezdec a věž spolupracují v rohu. Jezdec hlídá únikové pole, věž šachuje po kraji.',
      },
      {
        id: 'arabian-mate',
        kind: 'move',
        fen: 'r6k/1p3R2/1p2pN1p/8/8/8/p5PP/7K w - - 0 39',
        accept: ['f7h7'],
        completeness: { kind: 'mate' },
        text: 'Jezdec f6 hlídá krále v rohu. Dej mat věží.',
        success: 'Mat! Král na h8 nemá kam utéct, jezdec f6 hlídá g8.',
        wrongDefault: 'Dej šach věží po osmé řadě, ne po sloupci h. Jezdec f6 zamyká pole g8.',
      },
    ],
    outro: 'Dušený, Anastasiin i arabský mat mají něco společného. Král nemá kam utéct, ještě než přijde šach.',
    practice: [
      { kind: 'puzzles', band: 'lehke', theme: 'mateIn2', count: 5, label: 'Úlohy: mat 2. tahem' },
      { kind: 'puzzles', band: 'lehke', theme: 'anastasiaMate', count: 5, label: 'Úlohy: Anastasiin mat' },
      { kind: 'puzzles', band: 'lehke', theme: 'arabianMate', count: 5, label: 'Úlohy: arabský mat' },
    ],
  },

  {
    id: 'l3-matove-obrazce-2',
    level: 3,
    number: 9,
    title: 'Matové obrazce II',
    steps: [
      {
        // Lichess puzzle kR7T6, after 34.Rxc6+ bxc6.
        id: 'boden-idea',
        kind: 'show',
        fen: '2kr3r/p2n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/6K1 w - - 0 35',
        shapes: [
          { from: 'd3', to: 'a6', brush: 'blue' },
          { from: 'e6', to: 'a2', brush: 'blue' },
        ],
        text: 'Bodenův mat: dva střelci míří na krále přes zkřížené úhlopříčky. Únik nikam nevede.',
      },
      {
        id: 'boden-mate',
        kind: 'move',
        fen: '2kr3r/p2n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/6K1 w - - 0 35',
        accept: ['d3a6'],
        completeness: { kind: 'mate' },
        text: 'Král c8 je v pasti mezi dvěma úhlopříčkami. Dej mat.',
        success: 'Mat! Druhý střelec e6 hlídá poslední únikové pole b7.',
        wrongDefault: 'Hledej tah druhým střelcem, který zamkne krále na c8.',
      },
      {
        // Lichess puzzle LU6Uv, after 44.Kf5 Rf3+ 45.Rf4.
        id: 'epaulette-idea',
        kind: 'show',
        fen: '8/1p2rk2/p2R1p1p/2P2K1P/1P3RP1/5r2/8/8 b - - 4 45',
        shapes: [
          { from: 'f4', brush: 'red' },
          { from: 'g4', brush: 'red' },
        ],
        text: 'Epoletový mat: krále hlídají po stranách vlastní figurky, jako nárameníky. Šach přijde zepředu.',
      },
      {
        id: 'epaulette-mate',
        kind: 'move',
        fen: '8/1p2rk2/p2R1p1p/2P2K1P/1P3RP1/5r2/8/8 b - - 4 45',
        accept: ['e7e5'],
        completeness: { kind: 'mate' },
        text: 'Bílý král stojí mezi vlastní věží a pěšcem. Dej mat.',
        success: 'Mat! Král nemá kam uhnout, vlastní věž a pěšec mu zavírají cestu.',
        wrongDefault: 'Hledej šach věží zepředu. Král stojí mezi vlastními figurkami.',
      },
      {
        // Lichess puzzle 5vSL8, after 40.Qd8+ Bxd8.
        id: 'sac-idea',
        kind: 'show',
        fen: '3b3k/1q4pp/8/2p5/6r1/P4RN1/1P5P/6K1 w - - 0 41',
        shapes: [{ from: 'f3', to: 'f8', brush: 'blue' }],
        text: 'Mat na poslední řadě jde i s obětí. Dáma se obětovala, aby střelce odlákala z f8.',
      },
      {
        id: 'sac-mate',
        kind: 'move',
        fen: '3b3k/1q4pp/8/2p5/6r1/P4RN1/1P5P/6K1 w - - 0 41',
        accept: ['f3f8'],
        completeness: { kind: 'mate' },
        text: 'Poslední řadu už nikdo nehlídá. Dej mat.',
        success: 'Mat! Král za svými pěšci nemá jediné volné pole.',
        wrongDefault: 'Hledej šach věží na poslední řadě. Nikdo ji už nehlídá.',
      },
      {
        id: 'recognise',
        kind: 'choose',
        fen: '2kr3r/p2n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/6K1 w - - 0 35',
        text: 'Dva střelci na zkřížených úhlopříčkách. Jak se ten mat jmenuje?',
        options: [
          { id: 'boden', label: 'Bodenův mat' },
          { id: 'dusen', label: 'Dušený mat' },
          { id: 'epolet', label: 'Epoletový mat' },
        ],
        correct: ['boden'],
        explain: 'Ano! Dva střelci na zkřížených úhlopříčkách jsou Bodenův mat.',
        wrongExplain: {
          dusen: 'Dušený mat dává jezdec, ne dva střelci.',
          epolet: 'Epoletový mat hlídají krále vlastní figurky po stranách, ne dva střelci.',
        },
        wrongDefault: 'Podívej se, kolik střelců tu dává mat a jak jejich úhlopříčky vedou.',
      },
    ],
    outro: 'Matové obrazce se opakují partii za partií. Čím víc jich znáš, tím rychleji je najdeš.',
    practice: [
      { kind: 'puzzles', band: 'lehke', theme: 'backRankMate', count: 5, label: 'Úlohy: mat na poslední řadě' },
      { kind: 'puzzles', band: 'zacatecnik', theme: 'bodenMate', count: 5, label: 'Úlohy: Bodenův mat' },
      { kind: 'puzzles', band: 'lehke', theme: 'epauletteMate', count: 3, label: 'Úlohy: epoletový mat' },
    ],
  },

  {
    id: 'l3-mat-2-tahem',
    level: 3,
    number: 10,
    title: 'Mat 2. tahem',
    steps: [
      {
        id: 'order',
        kind: 'show',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        text: 'Mat na dva tahy hledej v pořadí: šachy, pak braní, pak hrozby. Šach zúží soupeři možnosti nejvíc.',
      },
      {
        // Lichess puzzle eXE9H, after 35.Kg1.
        id: 'check-first',
        kind: 'move',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P2nP1/1P6/P2r1r2/4R1K1 b - - 3 35',
        orientation: 'black',
        accept: ['f4h3'],
        completeness: { kind: 'best' },
        text: 'Hraješ za černé. Nejdřív zkus šachy. Najdi šach jezdcem.',
        success: 'Výborně! Král musí na h1, kam ho zahnal skok jezdce.',
        wrongDefault: 'Hledej šach jezdcem. Zúží to bílému králi pole.',
      },
      {
        id: 'check-mate',
        kind: 'move',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P3P1/1P5n/P2r1r2/4R2K b - - 5 36',
        orientation: 'black',
        accept: ['f2h2'],
        completeness: { kind: 'mate' },
        text: 'Král je teď na h1 bez úniku. Dej mat.',
        success: 'Mat! Král h1 nemá jediné volné pole.',
        wrongDefault: 'Hledej šach věží na sloupci h. Král h1 nemá kam utéct.',
      },
      {
        // Lichess puzzle gYcwF, after 26.Kg1.
        id: 'another',
        kind: 'move',
        fen: '2Q1B1k1/1Rp2p2/p2p4/8/2P1qP2/6P1/P7/5bK1 b - - 2 26',
        accept: ['e4g2'],
        completeness: { kind: 'mate' },
        text: 'Zkus to samostatně. Dej mat dámou.',
        success: 'Mat! Střelec f1 hlídá h1, dáma hlídá zbytek.',
        wrongDefault: 'Hledej šach dámou blízko krále. Střelec f1 mu hlídá pole h1.',
      },
      {
        id: 'quiet',
        kind: 'show',
        fen: '2Q1B1k1/1Rp2p2/p2p4/8/2P1qP2/6P1/P7/5bK1 b - - 2 26',
        text: 'První tah nemusí být vždycky šach. Někdy stačí tichý tah, který hrozbu jen připraví.',
      },
      {
        id: 'order-choose',
        kind: 'choose',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        text: 'Co zkoušíš hledat jako první?',
        options: [
          { id: 'sachy', label: 'Šachy' },
          { id: 'hrozby', label: 'Hrozby' },
          { id: 'nahodne', label: 'Cokoli, na pořadí nezáleží' },
        ],
        correct: ['sachy'],
        explain: 'Ano! Šachy zkoušej první. Zúží soupeři pole a mat najdeš rychleji.',
        wrongExplain: {
          hrozby: 'Hrozby zkoušej až po šaších a braní.',
          nahodne: 'Na pořadí záleží. Šach, braní, hrozba — v tomhle pořadí je to rychlejší.',
        },
        wrongDefault: 'Zkoušej tahy v pořadí: šach, braní, hrozba.',
      },
    ],
    outro: 'Šach, braní, hrozba — v tomhle pořadí hledej mat na dva tahy. Zrychlí ti to propočet.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'mateIn2', count: 5, label: 'Úlohy: mat 2. tahem' }],
  },

  {
    id: 'l3-opozice',
    level: 3,
    number: 11,
    title: 'Opozice',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '4k3/8/8/4K3/4P3/8/8/8 b - - 0 1',
        shapes: [
          { from: 'e5', brush: 'blue' },
          { from: 'e8', brush: 'red' },
        ],
        text: 'Opozice: králové stojí proti sobě s jedním polem mezi sebou. Kdo je na tahu, musí uhnout a je na tom hůř.',
      },
      {
        id: 'defend',
        kind: 'move',
        fen: '4k3/8/8/4K3/4P3/8/8/8 b - - 0 1',
        accept: ['e8e7'],
        completeness: { kind: 'best' },
        text: 'Hraješ za černé. Vezmi si opozici, jinak bílý pěšec projde.',
        success: 'Výborně! Teď musí ustoupit bílý král. Remíza drží.',
        wrongDefault: 'Postav krále přímo proti bílému, s jedním polem mezi sebou.',
      },
      {
        id: 'without',
        kind: 'show',
        fen: '3k4/8/8/4K3/4P3/8/8/8 b - - 0 1',
        text: 'Bez opozice to nejde. Odsud bílý král prosmýkne dopředu a pěšec se promění.',
      },
      {
        // Koncovky: kp-win.
        id: 'attack',
        kind: 'move',
        fen: '4k3/8/3K4/4P3/8/8/8/8 w - - 0 1',
        accept: ['d6e6'],
        completeness: { kind: 'best' },
        text: 'Teď hraješ za bílé. Král je před pěšcem. Vezmi si opozici.',
        success: 'Výborně! Černý král musí ustoupit a pěšec projde.',
        wrongDefault: 'Postav krále přímo proti černému, s jedním polem mezi sebou.',
      },
      {
        id: 'who-has-it',
        kind: 'choose',
        fen: '8/8/8/3K4/8/3k4/8/8 w - - 0 1',
        text: 'Bílý je na tahu. Kdo má opozici?',
        options: [
          { id: 'bily', label: 'Bílý' },
          { id: 'cerny', label: 'Černý' },
          { id: 'nikdo', label: 'Nikdo' },
        ],
        correct: ['cerny'],
        explain: 'Ano! Bílý musí ustoupit. Kdo nemusí táhnout, ten má opozici.',
        wrongExplain: {
          bily: 'Opozici má ten, kdo nemusí táhnout. Teď táhne bílý.',
          nikdo: 'Králové stojí přímo proti sobě s jedním polem mezi sebou. Opozici má někdo.',
        },
        wrongDefault: 'Opozici má ten, kdo nemusí táhnout jako první.',
      },
    ],
    outro: 'Opozice rozhoduje v koncovkách krále a pěšce. Kdo ji má, tlačí soupeřova krále dozadu.',
    practice: [
      { kind: 'endgame', id: 'kp-win', label: 'Koncovky: král před pěšcem' },
      { kind: 'endgame', id: 'kp-draw', label: 'Koncovky: udrž remízu' },
    ],
  },

  {
    id: 'l3-ctverec',
    level: 3,
    number: 12,
    title: 'Pravidlo čtverce a závod pěšců',
    steps: [
      {
        // Koncovky: square.
        id: 'idea',
        kind: 'show',
        fen: '8/8/8/8/3k3P/8/8/7K b - - 0 1',
        shapes: [
          { from: 'h4', to: 'h8', brush: 'blue' },
          { from: 'h8', to: 'd8', brush: 'blue' },
          { from: 'd8', to: 'd4', brush: 'blue' },
        ],
        text: 'Pravidlo čtverce: nakresli si od pěšce čtverec až k poslední řadě. Král uvnitř ho dožene.',
      },
      {
        id: 'catch',
        kind: 'move',
        fen: '8/8/8/8/3k3P/8/8/7K b - - 0 1',
        accept: ['d4e5', 'd4e4', 'd4d5'],
        completeness: { kind: 'best' },
        text: 'Král stojí přesně na kraji čtverce. Zůstaň uvnitř a dožeň pěšce.',
        success: 'Výborně! Pěšec ti neuteče, král ho dostihne.',
        wrongDefault: 'Tímhle tahem bys vypadl ze čtverce. Pěšec by pak proběhl sám.',
      },
      {
        id: 'outside',
        kind: 'show',
        fen: '8/8/8/2k5/7P/8/8/7K b - - 0 1',
        shapes: [{ from: 'c5', brush: 'red' }],
        text: 'Tenhle král už je mimo čtverec. Ať běží, jak chce, pěšce nedožene.',
      },
      {
        // Koncovky: race.
        id: 'race',
        kind: 'move',
        fen: '8/6k1/8/8/8/8/P5K1/8 w - - 0 1',
        accept: ['a2a4'],
        completeness: { kind: 'best' },
        text: 'Teď ty máš pěšce. Vyběhni s ním o dvě pole, ať to stihneš do čtverce.',
        success: 'Výborně! Černý král je teď mimo čtverec a pěšec proběhne sám.',
        wrongDefault: 'Zkus vyrazit pěšcem o dvě pole. O jedno by to nestačilo.',
      },
      {
        id: 'is-inside',
        kind: 'choose',
        fen: '8/8/4k3/8/7P/8/8/7K b - - 0 1',
        text: 'Stihne černý král pěšce dohnat?',
        options: [
          { id: 'ano', label: 'Ano, je ve čtverci' },
          { id: 'ne', label: 'Ne, je mimo čtverec' },
        ],
        correct: ['ano'],
        explain: 'Správně, stihne. Král na e6 je ve čtverci, pěšce dožene.',
        wrongDefault: 'Spočítej pole od pěšce k poslední řadě a porovnej s králem.',
      },
    ],
    outro: 'Pravidlo čtverce ti hned řekne, jestli má cenu pěšce honit. Nebo radši utíkat s vlastním.',
    practice: [
      { kind: 'endgame', id: 'square', label: 'Koncovky: pravidlo čtverce' },
      { kind: 'endgame', id: 'race', label: 'Koncovky: utíkej s pěšcem' },
    ],
  },

  {
    id: 'l3-zkouska',
    level: 3,
    number: 13,
    title: 'Zkouška úrovně 3',
    test: {
      passScore: 9,
      badge: 'l3',
      failOutro: 'Tentokrát to nevyšlo. Zopakuj si lekce, kde to drhlo, a zkus to znovu.',
    },
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/8/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Zkouška úrovně 3! Čeká tě 11 úloh. Na každou máš jen jeden pokus a žádnou nápovědu.',
      },
      {
        // Lichess puzzle INSwD, as in l3-odstraneni-obrance.
        id: 't-guard',
        kind: 'move',
        fen: '4r2k/1pNr2pp/4q3/4P3/2QP4/1P3R1P/P5P1/6K1 b - - 6 32',
        accept: ['e6c4'],
        completeness: { kind: 'best' },
        text: 'Odstraň obránce a vyhraj figurku.',
        success: 'Správně!',
        wrongDefault: 'Bílá dáma hlídá jezdce c7. Vezmi ji.',
      },
      {
        // As in l3-pretizeni.
        id: 't-overload',
        kind: 'choose',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        text: 'Která figurka je přetížená?',
        options: [
          { id: 'd8', square: 'd8' },
          { id: 'd5', square: 'd5' },
          { id: 'a7', square: 'a7' },
        ],
        correct: ['d8'],
        explain: 'Věž d8 hlídá jezdce i střelce najednou.',
        wrongDefault: 'Hledej figurku, která hlídá dvě věci najednou.',
      },
      {
        // Lichess puzzle 2warR, as in l3-odlakani.
        id: 't-lure',
        kind: 'move',
        fen: '8/2pRP3/1p6/1P2rk1p/7p/8/5KP1/8 w - - 1 43',
        accept: ['d7d5'],
        completeness: { kind: 'best' },
        text: 'Odlákej věž, která hlídá cestu pěšci.',
        success: 'Správně!',
        wrongDefault: 'Dej šach věží. Černá věž ho musí vzít a odejde od pěšce.',
      },
      {
        // Légal's trap, as in l3-vlakani.
        id: 't-attract',
        kind: 'move',
        fen: 'rn1q1bnr/ppp1kB1p/3p2p1/4N3/4P3/2N5/PPPP1PPP/R1BbK2R w KQ - 1 7',
        accept: ['c3d5'],
        completeness: { kind: 'mate' },
        text: 'Král byl nalákaný na e7. Dej mat.',
        success: 'Mat!',
        wrongDefault: 'Skoč jezdcem tak, aby dal mat králi na e7.',
      },
      {
        // Lichess puzzle HMT0w, as in l3-rentgen.
        id: 't-skewer',
        kind: 'move',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        accept: ['d3b5'],
        completeness: { kind: 'best' },
        text: 'Najdi rentgen: napadni dámu, za ní stojí věž.',
        success: 'Správně!',
        wrongDefault: 'Hledej tah střelcem, který napadne dámu i věž za ní.',
      },
      {
        // Elephant Trap, as in l3-mezitah.
        id: 't-intermezzo',
        kind: 'move',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        accept: ['f8b4'],
        completeness: { kind: 'best' },
        text: 'Neber zpátky hned. Zahraj mezitah.',
        success: 'Správně!',
        wrongDefault: 'Dej nejdřív šach střelcem, než vezmeš zpátky.',
      },
      {
        // As in l3-matove-obrazce-2.
        id: 't-pattern',
        kind: 'choose',
        fen: '2kr3r/p2n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/6K1 w - - 0 35',
        text: 'Dva střelci na zkřížených úhlopříčkách. Jak se ten mat jmenuje?',
        options: [
          { id: 'boden', label: 'Bodenův mat' },
          { id: 'dusen', label: 'Dušený mat' },
          { id: 'epolet', label: 'Epoletový mat' },
        ],
        correct: ['boden'],
        explain: 'Dva střelci na zkřížených úhlopříčkách jsou Bodenův mat.',
        wrongDefault: 'Podívej se, kolik střelců tu dává mat.',
      },
      {
        // Lichess puzzle eXE9H, as in l3-mat-2-tahem.
        id: 't-mate2a',
        kind: 'move',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P3P1/1P5n/P2r1r2/4R2K b - - 5 36',
        orientation: 'black',
        accept: ['f2h2'],
        completeness: { kind: 'mate' },
        text: 'Dej mat 1 tahem.',
        success: 'Mat!',
        wrongDefault: 'Hledej šach věží na sloupci h.',
      },
      {
        // Lichess puzzle gYcwF, as in l3-mat-2-tahem.
        id: 't-mate2b',
        kind: 'move',
        fen: '2Q1B1k1/1Rp2p2/p2p4/8/2P1qP2/6P1/P7/5bK1 b - - 2 26',
        accept: ['e4g2'],
        completeness: { kind: 'mate' },
        text: 'Dej mat 1 tahem.',
        success: 'Mat!',
        wrongDefault: 'Hledej šach dámou blízko krále.',
      },
      {
        // As in l3-opozice.
        id: 't-opposition',
        kind: 'choose',
        fen: '8/8/8/3K4/8/3k4/8/8 w - - 0 1',
        text: 'Bílý je na tahu. Kdo má opozici?',
        options: [
          { id: 'bily', label: 'Bílý' },
          { id: 'cerny', label: 'Černý' },
          { id: 'nikdo', label: 'Nikdo' },
        ],
        correct: ['cerny'],
        explain: 'Opozici má ten, kdo nemusí táhnout jako první.',
        wrongDefault: 'Opozici má ten, kdo nemusí táhnout jako první.',
      },
      {
        // As in l3-ctverec.
        id: 't-square',
        kind: 'choose',
        fen: '8/8/4k3/8/7P/8/8/7K b - - 0 1',
        text: 'Stihne černý král pěšce dohnat?',
        options: [
          { id: 'ano', label: 'Ano, je ve čtverci' },
          { id: 'ne', label: 'Ne, je mimo čtverec' },
        ],
        correct: ['ano'],
        explain: 'Král na e6 je ve čtverci, pěšce dožene.',
        wrongDefault: 'Spočítej pole od pěšce k poslední řadě a porovnej s králem.',
      },
    ],
    outro: 'Zkouška je za tebou! Odznak je tvůj a můžeš si vytisknout diplom.',
    practice: [{ kind: 'play', level: 4, label: 'Zahraj si partii proti silnějšímu soupeři' }],
  },
];
