/**
 * Level 3 — Mírně pokročilý, lessons 1–13 (docs/phase-22-plan.md, curriculum). Tactics
 * (odstranění obránce, přetížení, odlákání, vlákání, rentgen, chycená figurka, mezitah),
 * mate patterns, mate in 2, and the first two pawn-endgame ideas (opozice, pravidlo
 * čtverce). Lesson 13 is the level test. Positions are game-like: simplified middlegames
 * (most from the Lichess puzzle database, CC0; the id is noted) and classic traps and
 * games (Légal's trap, Morphy's Opera Game, the Elephant Trap, Noah's Ark) verified move
 * by move with chess.js. Every tactic task is checked by `npm run check:lessons`: mates
 * with `mate`, "win material" tasks with `best` (Stockfish: no other move within the
 * margin); the first move of a mate in 2 uses `best` with `marginCp: 0` (only mates in 2
 * pass). The opposition and square-rule claims were checked against the Lichess
 * tablebase (coach review, 2026-09-26). Texts: informal „ty“, short sentences, Czech
 * letters (K D V S J), 0-0; „Anastáziin mat“ (one spelling, linted).
 */
import type { Lesson } from './types';

export const LEVEL3: readonly Lesson[] = [
  {
    id: 'l3-odstraneni-obrance',
    level: 3,
    number: 1,
    title: 'Odstranění obránce',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '6k1/pp3ppp/5n2/3b2B1/8/7P/PP3PP1/3R2K1 w - - 0 1',
        shapes: [
          { from: 'd1', to: 'd5', brush: 'blue' },
          { from: 'f6', to: 'd5', brush: 'red' },
        ],
        text: 'Tvoje věž napadá střelce d5. Jezdec f6 ho ale hlídá. Takové figurce se říká obránce.',
      },
      {
        id: 'remove',
        kind: 'move',
        fen: '6k1/pp3ppp/5n2/3b2B1/8/7P/PP3PP1/3R2K1 w - - 0 1',
        accept: ['g5f6'],
        completeness: { kind: 'best' },
        text: 'Vezmi obránce. Pak zůstane střelec d5 bez ochrany.',
        success: 'Výborně! Po gxf6 sebereš Vxd5. Obránce zmizel a střelec je tvůj.',
        wrong: { d1d5: 'Po Vxd5 Jxd5 přijdeš o věž. Nejdřív vezmi obránce f6.' },
        wrongDefault: 'Nejdřív vezmi jezdce f6. Právě on hlídá střelce d5.',
      },
      {
        // Lichess puzzle INSwD, after 32.Nc7.
        id: 'take-guard',
        kind: 'move',
        fen: '4r2k/1pNr2pp/4q3/4P3/2QP4/1P3R1P/P5P1/6K1 b - - 6 32',
        orientation: 'black',
        accept: ['e6c4'],
        completeness: { kind: 'best' },
        text: 'Hraješ za černé. Bílá dáma c4 hlídá jezdce c7. Vezmi ji.',
        success: 'Paráda! Po bxc4 je jezdec c7 bez obrany. Věž d7 ho příště sebere.',
        wrongDefault: 'Hledej tah dámou, po kterém bude jezdec c7 bez obrany.',
      },
      {
        // Lichess puzzle HKPPH, after 14...Nc6.
        id: 'combo',
        kind: 'move',
        fen: 'r2r2k1/pp2bppp/2n5/2pNN2n/2P5/7P/PP3PP1/R1B1K2R w KQ - 2 15',
        accept: ['e5c6'],
        completeness: { kind: 'best' },
        text: 'Jezdec c6 hlídá střelce e7. Odstraň ho.',
        success: 'Paráda! Po bxc6 vezme druhý jezdec Jxe7+ i střelce. Máš figurku navíc.',
        wrongDefault: 'Hledej tah, který sebere jezdce c6. Ten hlídá střelce e7.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '6k1/pp4pp/3bp3/5n2/6B1/7P/PP3PP1/3R2K1 w - - 0 1',
        text: 'Tvoje věž napadá střelce d6. Kterou figurku vezmeš nejdřív?',
        options: [
          { id: 'f5', square: 'f5' },
          { id: 'd6', square: 'd6' },
          { id: 'e6', square: 'e6' },
        ],
        correct: ['f5'],
        explain: 'Ano! Jezdec f5 hlídá střelce d6. Vezmi ho, a střelec zůstane bez obrany.',
        wrongExplain: {
          d6: 'Po Vxd6 Jxd6 přijdeš o věž. Jezdec f5 střelce hlídá.',
          e6: 'Pěšec e6 střelce d6 nehlídá. Hlídá ho jezdec f5.',
        },
        wrongDefault: 'Hledej figurku, která hlídá střelce d6.',
      },
    ],
    outro: 'Než zaútočíš na figurku, podívej se, kdo ji hlídá. Sundej obránce, a figurka je tvoje.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'capturingDefender', count: 5, label: 'Úlohy: odstranění obránce' }],
  },

  {
    id: 'l3-pretizeni',
    level: 3,
    number: 2,
    title: 'Přetížení',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        shapes: [
          { from: 'd8', to: 'd5', brush: 'blue' },
          { from: 'd8', to: 'b8', brush: 'blue' },
        ],
        text: 'Věž d8 hlídá dvě věci najednou: jezdce d5 i střelce b8. Tomu se říká přetížení.',
      },
      {
        id: 'win',
        kind: 'move',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        accept: ['a7b8'],
        completeness: { kind: 'best' },
        text: 'Věž d8 nestíhá obě práce. Vezmi jednu z figurek, které hlídá.',
        success: 'Výborně! Když věž vezme Vxb8, nehlídá už jezdce d5. Vxd5 ho sebereš zadarmo.',
        wrong: { d1d5: 'Po Vxd5 Vxd5 přijdeš o věž. Začni střelcem b8, tam nic neriskuješ.' },
        wrongDefault: 'Vezmi střelce b8. Věž d8 ho hlídá, ale pak přestane hlídat jezdce d5.',
      },
      {
        id: 'which-overloaded',
        kind: 'choose',
        fen: '1b1r2k1/B4ppp/8/3n4/8/8/PP3PPP/3R2K1 w - - 0 1',
        text: 'Která figurka je přetížená?',
        options: [
          { id: 'd8', square: 'd8' },
          { id: 'd5', square: 'd5' },
          { id: 'a7', square: 'a7' },
        ],
        correct: ['d8'],
        explain: 'Ano! Věž d8 musí hlídat jezdce i střelce najednou. Na obojí nestačí.',
        wrongExplain: {
          d5: 'Jezdec d5 žádnou svoji figurku nehlídá. Sám je hlídaný.',
          a7: 'Střelec a7 je tvoje figurka, žádnou práci navíc nemá.',
        },
        wrongDefault: 'Hledej figurku, která hlídá dvě věci najednou.',
      },
      {
        // Lichess puzzle exQ1C, after 26.Rd3-e3.
        id: 'rook-idea',
        kind: 'show',
        fen: '2r1r3/5kp1/p4n1p/P2p4/6P1/P1B1R2P/2P5/2K1R3 b - - 2 26',
        orientation: 'black',
        shapes: [
          { from: 'e3', to: 'c3', brush: 'blue' },
          { from: 'e3', to: 'e1', brush: 'blue' },
        ],
        text: 'Hraješ za černé. Bílá věž e3 taky hlídá dvě věci: střelce c3 a věž e1.',
      },
      {
        id: 'rook',
        kind: 'move',
        fen: '2r1r3/5kp1/p4n1p/P2p4/6P1/P1B1R2P/2P5/2K1R3 b - - 2 26',
        orientation: 'black',
        accept: ['c8c3'],
        completeness: { kind: 'best' },
        text: 'Využij toho. Vezmi jednu z figurek, které věž e3 hlídá.',
        success: 'Paráda! Po Vxc3 věž e3 zmizí z e-sloupce a Vxe1 sebereš druhou věž.',
        wrongDefault: 'Vezmi střelce c3. Věž e3 ho hlídá, ale hlídá i věž e1.',
      },
    ],
    outro: 'Když jedna figurka hlídá dvě věci, vezmi jednu z nich. Na obě nestačí.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'deflection', count: 5, label: 'Úlohy: přetížení a odlákání' }],
  },

  {
    id: 'l3-odlakani',
    level: 3,
    number: 3,
    title: 'Odlákání',
    steps: [
      {
        // Lichess puzzle 2warR, after 42...Kf5.
        id: 'idea',
        kind: 'show',
        fen: '8/2pRP3/1p6/1P2rk1p/7p/8/5KP1/8 w - - 1 43',
        shapes: [{ from: 'e5', to: 'e7', brush: 'red' }],
        text: 'Věž e5 hlídá pole před pěšcem. Bez ní pěšec projde a promění se. Musíš ji odlákat.',
      },
      {
        id: 'lure',
        kind: 'move',
        fen: '8/2pRP3/1p6/1P2rk1p/7p/8/5KP1/8 w - - 1 43',
        accept: ['d7d5'],
        completeness: { kind: 'best' },
        text: 'Napadni věž e5 svou věží. Černá věž je vázaná ke králi.',
        success: 'Výborně! Když černý vezme Vxd5, pěšec se promění e8D. Když nevezme, sebereš věž ty.',
        wrongDefault: 'Hledej tah věží, který napadne věž e5. Když ji vezme, odejde od pěšce.',
      },
      {
        // Lichess puzzle 9OVqg, after 56...Kb5.
        id: 'lure2',
        kind: 'move',
        fen: '8/2P5/8/1kr5/p4R2/8/4K3/8 w - - 2 57',
        accept: ['f4f5'],
        completeness: { kind: 'best' },
        text: 'Tady hlídá cestu k proměně věž c5. Odlákej ji.',
        success: 'Paráda! Po Vxf5 se pěšec promění c8D. Když věž nevezme, sebereš ji ty.',
        wrongDefault: 'Postav věž na pátou řadu. Černá věž je pak vázaná ke králi.',
      },
      {
        id: 'opera-idea',
        kind: 'show',
        fen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
        shapes: [{ from: 'd1', to: 'd8', brush: 'red' }],
        text: 'Slavná Operní partie, Paříž 1858. Morphy hraje bílými proti vévodovi a hraběti. Jeho věži stojí v cestě jezdec d7.',
      },
      {
        // Morphy – Duke Karl of Brunswick and Count Isouard, Paris 1858, 16.Qb8+!
        id: 'opera-sac',
        kind: 'move',
        fen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
        accept: ['b3b8'],
        completeness: { kind: 'best' },
        text: 'Obětuj dámu šachem. Odlákej jezdce z pole d7.',
        success: 'Paráda! Jezdec musí vzít Jxb8, jiný tah černý nemá. Sloupec d je volný.',
        wrongDefault: 'Hledej šach dámou, který jezdce d7 odláká pryč.',
      },
      {
        id: 'opera-mate',
        kind: 'move',
        fen: '1n2kb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 w k - 0 17',
        accept: ['d1d8'],
        completeness: { kind: 'mate' },
        text: 'Jezdec už věži v cestě nestojí. Dej mat!',
        success: 'Mat! Věž na d8 kryje střelec g5. Ten hlídá i pole e7.',
        wrongDefault: 'Sloupec d je volný. Dej šach věží na d8.',
      },
      {
        id: 'why',
        kind: 'choose',
        fen: '1n2kb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 w k - 0 17',
        text: 'Proč Morphy obětoval dámu na b8?',
        options: [
          { id: 'odlakat', label: 'Aby odlákal jezdce z pole d7' },
          { id: 'vymena', label: 'Aby dostal jezdce za dámu' },
          { id: 'omyl', label: 'Byl to omyl, dámu ztratil zbytečně' },
        ],
        correct: ['odlakat'],
        explain: 'Ano! Jezdec d7 stál věži v cestě. Obětí ho Morphy odlákal a dal mat.',
        wrongExplain: {
          vymena: 'Jezdec za dámu je špatný obchod. Morphy chtěl mat, ne jezdce.',
          omyl: 'Nebyl to omyl. Za dámu Morphy dostal mat.',
        },
        wrongDefault: 'Podívej se, kde stál jezdec, než šel na b8.',
      },
    ],
    outro: 'Odlákej figurku, která něco hlídá nebo ti stojí v cestě. Klidně za to zaplať.',
    practice: [
      { kind: 'puzzles', band: 'lehke', theme: 'deflection', count: 5, label: 'Úlohy: odlákání' },
      { kind: 'endgame', id: 'race', label: 'Koncovky: utíkej s pěšcem' },
    ],
  },

  {
    id: 'l3-vlakani',
    level: 3,
    number: 4,
    title: 'Vlákání',
    steps: [
      {
        // Légal's trap: 1.e4 e5 2.Jf3 d6 3.Sc4 Sg4 4.Jc3 g6 5.Jxe5!? Sxd1 6.Sxf7+ Ke7 7.Jd5#.
        id: 'idea',
        kind: 'show',
        fen: 'rn1qkbnr/ppp2p1p/3p2p1/4N3/2B1P3/2N5/PPPP1PPP/R1BbK2R w KQkq - 0 6',
        text: 'Vlákání je opak odlákání. Nalákáš soupeřovu figurku na špatné pole, nejčastěji krále. Tady černý právě vzal bílou dámu.',
      },
      {
        id: 'legal',
        kind: 'move',
        fen: 'rn1qkbnr/ppp2p1p/3p2p1/4N3/2B1P3/2N5/PPPP1PPP/R1BbK2R w KQkq - 0 6',
        accept: ['c4f7'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Dámu oželíš. Dej šach, po kterém musí král na e7.',
        success: 'Výborně! Král musí na e7, jiný tah nemá. Tam ho čeká mat.',
        wrongDefault: 'Hledej šach střelcem. Král pak bude muset na e7.',
      },
      {
        id: 'legal-mate',
        kind: 'move',
        fen: 'rn1q1bnr/ppp1kB1p/3p2p1/4N3/4P3/2N5/PPPP1PPP/R1BbK2R w KQ - 1 7',
        accept: ['c3d5'],
        completeness: { kind: 'mate' },
        text: 'Král je nalákaný na e7. Dej mat jezdcem!',
        success: 'Mat! Tomu se říká Légalova past. Bílý dal dámu a dostal za ni mat.',
        wrongDefault: 'Král stojí na e7. Hledej skok jezdce, který mu dá šach.',
      },
      {
        // Lichess puzzle yyMhr, after 30...Rd8.
        id: 'fork',
        kind: 'move',
        fen: '3rk2r/5pp1/p2Rp2p/P1p1N3/1p2P1P1/7P/2PK1P2/8 w k - 1 31',
        accept: ['d6d8'],
        completeness: { kind: 'best' },
        text: 'Krále můžeš vlákat i na pole vidličky. Obětuj věž a nalákej ho na d8.',
        success: 'Paráda! Když král vezme na d8, přijde vidlička. Když nevezme, sebereš věž h8.',
        wrongDefault: 'Vezmi věž d8 svou věží. Král ji vezme a skončí na špatném poli.',
      },
      {
        id: 'fork-win',
        kind: 'move',
        fen: '3k3r/5pp1/p3p2p/P1p1N3/1p2P1P1/7P/2PK1P2/8 w - - 0 32',
        accept: ['e5f7'],
        completeness: { kind: 'best' },
        text: 'Král vzal na d8. Teď vidlička jezdcem!',
        success: 'Výborně! Jezdec dává šach a napadá věž h8. Příště ji sebereš.',
        wrongDefault: 'Hledej skok jezdce se šachem, který napadne i věž h8.',
      },
      {
        id: 'why',
        kind: 'choose',
        fen: '3k3r/5pp1/p3p2p/P1p1N3/1p2P1P1/7P/2PK1P2/8 w - - 0 32',
        text: 'K čemu byla oběť věže na d8?',
        options: [
          { id: 'vlakat', label: 'Aby král přišel na pole vidličky' },
          { id: 'vymena', label: 'Jen kvůli výměně věží' },
          { id: 'omyl', label: 'Byla to chyba' },
        ],
        correct: ['vlakat'],
        explain: 'Ano! Král musel na d8, a tam ho jezdec napadl vidličkou.',
        wrongExplain: {
          vymena: 'Po výměně by jezdec neměl koho napadnout. Šlo o to dostat krále na d8.',
          omyl: 'Chyba to nebyla. Za věž dostaneš zpátky věž h8 a pěšce navíc.',
        },
        wrongDefault: 'Podívej se, kam se po oběti dostal král.',
      },
    ],
    outro: 'Vlákáním přitáhneš soupeřovu figurku na špatné pole. Klidně za to zaplať figurkou.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'attraction', count: 5, label: 'Úlohy: vlákání' }],
  },

  {
    id: 'l3-rentgen',
    level: 3,
    number: 5,
    title: 'Rentgen',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '4q3/pp4pp/8/4k3/8/6K1/PP5P/7R w - - 0 1',
        shapes: [
          { from: 'e5', brush: 'red' },
          { from: 'e8', brush: 'red' },
        ],
        text: 'Rentgen: napadneš cennou figurku, a za ní na stejné čáře stojí další. Tady král a za ním dáma.',
      },
      {
        id: 'check',
        kind: 'move',
        fen: '4q3/pp4pp/8/4k3/8/6K1/PP5P/7R w - - 0 1',
        accept: ['h1e1'],
        completeness: { kind: 'best' },
        text: 'Dej šach věží po sloupci e.',
        success: 'Výborně! Král musí uhnout a věž si vezme dámu.',
        wrongDefault: 'Hledej šach po sloupci e. Král uhne a dáma za ním padne.',
      },
      {
        // Lichess puzzle HMT0w, after 19...f6.
        id: 'not-pin',
        kind: 'show',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        text: 'Pozor na rozdíl od vazby. U rentgenu stojí vpředu cennější figurka. U vazby stojí cennější figurka vzadu.',
      },
      {
        id: 'bishop',
        kind: 'move',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        accept: ['d3b5'],
        completeness: { kind: 'best' },
        text: 'Najdi rentgen střelcem. Napadni dámu, za kterou stojí věž.',
        success: 'Paráda! Dáma musí uhnout a střelec pak sebere věž e8.',
        wrongDefault: 'Hledej tah střelcem, který napadne dámu c6 a přes ni míří na věž e8.',
      },
      {
        id: 'which-bigger',
        kind: 'choose',
        fen: 'r1b1r1k1/p5p1/2q1pp1p/2Pp4/3PnP2/1R1BP3/P5PP/3Q1RK1 w - - 0 20',
        text: 'Co udělá černá dáma, když ji střelec napadne?',
        options: [
          { id: 'uhne', label: 'Uhne, věž za ní padne' },
          { id: 'nesmi', label: 'Nesmí táhnout, je vázaná' },
          { id: 'vezme', label: 'Vezme střelce zadarmo' },
        ],
        correct: ['uhne'],
        explain: 'Ano. Dáma není vázaná ke králi, smí uhnout. Ale pak přijde o věž e8.',
        wrongExplain: {
          nesmi: 'Vázaná není, za dámou stojí věž, ne král. Klidně uhne.',
          vezme: 'Střelce na b5 hlídá věž b3. Brát ho se nevyplatí.',
        },
        wrongDefault: 'Dáma není vázaná. Podívej se, co za ní stojí.',
      },
    ],
    outro: 'Rentgen: napadni cennější figurku, a ta za ní ti spadne do klína.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'skewer', count: 5, label: 'Úlohy: rentgen' }],
  },

  {
    id: 'l3-chycena-figurka',
    level: 3,
    number: 6,
    title: 'Chycená figurka',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: '6k1/pp4pp/2p1pp2/7n/8/4P3/PPP2PPP/2B3K1 w - - 0 1',
        shapes: [{ from: 'h5', brush: 'red' }],
        text: 'Chycená figurka nemá kam utéct. Podívej se na černého jezdce h5. Kam by mohl skočit?',
      },
      {
        id: 'trap',
        kind: 'move',
        fen: '6k1/pp4pp/2p1pp2/7n/8/4P3/PPP2PPP/2B3K1 w - - 0 1',
        accept: ['g2g4'],
        completeness: { kind: 'best' },
        text: 'Napadni jezdce pěšcem. Utéct už nebude mít kam.',
        success: 'Výborně! Na f6 a g7 stojí jeho pěšci. Pole f4 a g3 hlídají tvoji pěšci.',
        wrongDefault: 'Hledej tah pěšcem, který jezdce h5 napadne.',
      },
      {
        // Noah's Ark trap: 1.e4 e5 2.Jf3 Jc6 3.Sb5 a6 4.Sa4 d6 5.d4 b5 6.Sb3 Jxd4
        // 7.Jxd4 exd4 8.Dxd4?? c5! 9.Dd5 Se6 10.Dc6+ Sd7 11.Dd5 c4.
        id: 'noah-idea',
        kind: 'show',
        fen: 'r1bqkbnr/2p2ppp/p2p4/1p6/3QP3/1B6/PPP2PPP/RNB1K2R b KQkq - 0 8',
        orientation: 'black',
        text: 'Chytit jde i figurka v zahájení. Téhle pasti se říká Noemova archa. Hraješ za černé.',
      },
      {
        id: 'noah',
        kind: 'move',
        fen: 'r1bqkbnr/2p2ppp/p2p4/1p6/3QP3/1B6/PPP2PPP/RNB1K2R b KQkq - 0 8',
        orientation: 'black',
        accept: ['c7c5'],
        completeness: { kind: 'best' },
        text: 'Napadni bílou dámu pěšcem. Později ho pošleš dál na c4.',
        success: 'Paráda! Dáma uhne a za pár tahů přijde c4. Pak střelec b3 nebude mít kam.',
        wrongDefault: 'Napadni dámu d4 pěšcem c. Ten pak zavře bílého střelce.',
      },
      {
        id: 'noah-trapped',
        kind: 'choose',
        fen: 'r2qkbnr/3b1ppp/p2p4/1p1Q4/2p1P3/1B6/PPP2PPP/RNB1K2R w KQkq - 0 12',
        orientation: 'black',
        text: 'Tak vypadá past po tahu c4. Která bílá figurka je chycená?',
        options: [
          { id: 'b3', square: 'b3' },
          { id: 'd5', square: 'd5' },
          { id: 'c1', square: 'c1' },
        ],
        correct: ['b3'],
        explain: 'Ano! Pěšec c4 napadá střelce b3. Pole a4 hlídá pěšec b5 a vlastní pěšci stojí na a2 a c2.',
        wrongExplain: {
          d5: 'Dáma má spoustu volných polí.',
          c1: 'Střelec c1 může ven přes d2 nebo e3.',
        },
        wrongDefault: 'Hledej figurku, kterou pěšec napadá a která nemá kam uhnout.',
      },
      {
        id: 'why-search',
        kind: 'show',
        fen: 'r2qkbnr/3b1ppp/p2p4/1p1Q4/2p1P3/1B6/PPP2PPP/RNB1K2R w KQkq - 0 12',
        orientation: 'black',
        text: 'Chycenou figurku hledej hlavně u kraje šachovnice. Tam má figurka málo polí na útěk.',
      },
    ],
    outro: 'Chycená figurka nemá kam utéct. Nespěchej, seber ji, až na to přijde řada.',
    practice: [{ kind: 'puzzles', band: 'stredni', theme: 'trappedPiece', count: 5, label: 'Úlohy: chycená figurka' }],
  },

  {
    id: 'l3-mezitah',
    level: 3,
    number: 7,
    title: 'Mezitah',
    steps: [
      {
        id: 'idea',
        kind: 'show',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        orientation: 'black',
        text: 'Bílý právě vzal tvoji dámu. Než ji vezmeš zpátky, zkus mezitah: silnější tah navíc.',
      },
      {
        // The Elephant Trap in the Queen's Gambit Declined: 1.d4 d5 2.c4 e6 3.Nc3 Nf6
        // 4.Bg5 Nbd7 5.cxd5 exd5 6.Nxd5?? Nxd5 7.Bxd8?? Bb4+! 8.Qd2 Bxd2+ 9.Kxd2 Kxd8.
        id: 'trap',
        kind: 'move',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        orientation: 'black',
        accept: ['f8b4'],
        completeness: { kind: 'best' },
        text: 'Nech bílého střelce na d8 chvíli stát. Dej nejdřív šach střelcem.',
        success: 'Paráda! Po Dd2 Sxd2+ Kxd2 teprve vezmeš Kxd8. Budeš mít o figurku víc. Téhle pasti se říká sloní past.',
        wrongDefault: 'Bílý střelec na d8 nikam neuteče. Nejdřív dej šach střelcem na b4.',
      },
      {
        // Lichess puzzle TYU0K, after 19...Qxf3.
        id: 'check-idea',
        kind: 'show',
        fen: 'r1b3k1/ppp2pp1/4R2p/8/5B2/2P2q1P/PPP2PP1/5RK1 w - - 0 20',
        shapes: [{ from: 'c8', to: 'e6', brush: 'red' }],
        text: 'Černá dáma vzala jezdce f3. Když ji vezmeš hned, černý střelec sebere tvoji věž e6.',
      },
      {
        id: 'check',
        kind: 'move',
        fen: 'r1b3k1/ppp2pp1/4R2p/8/5B2/2P2q1P/PPP2PP1/5RK1 w - - 0 20',
        accept: ['e6e8'],
        completeness: { kind: 'best' },
        text: 'Zahraj mezitah. Zachraň věž tahem se šachem.',
        success: 'Výborně! Král musí na h7, a pak vezmeš dámu gxf3. Věž je v bezpečí.',
        wrongDefault: 'Dáma f3 ti neuteče. Nejdřív dej šach věží, ať je z dosahu střelce.',
      },
      {
        id: 'when',
        kind: 'choose',
        fen: 'r1bBkb1r/pppn1ppp/8/3n4/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 7',
        orientation: 'black',
        text: 'Kdy se mezitah hodí nejvíc?',
        options: [
          { id: 'silnejsi', label: 'Když máš tah silnější než obyčejné braní zpátky' },
          { id: 'vzdy', label: 'Vždycky, braní zpátky nikdy nepospíchá' },
          { id: 'nikdy', label: 'Nikdy, vždycky ber zpátky hned' },
        ],
        correct: ['silnejsi'],
        explain: 'Ano! Mezitah hraješ, jen když máš po ruce tah se šachem nebo velkou hrozbou.',
        wrongExplain: {
          vzdy: 'Někdy je nutné vzít rovnou, jinak přijdeš o víc.',
          nikdy: 'Někdy se ti mezitah vyplatí víc než braní hned.',
        },
        wrongDefault: 'Mezitah funguje jen s tahem, který soupeře donutí reagovat: šach nebo velká hrozba.',
      },
    ],
    outro: 'Než vezmeš zpátky, rozhlédni se. Máš po ruce šach nebo hrozbu? Zahraj ji nejdřív.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'intermezzo', count: 5, label: 'Úlohy: mezitah' }],
  },

  {
    id: 'l3-matove-obrazce-1',
    level: 3,
    number: 8,
    title: 'Matové obrazce I',
    steps: [
      {
        id: 'smothered-idea',
        kind: 'show',
        fen: '5r1k/6pp/7N/3Q4/8/8/8/6K1 w - - 0 1',
        shapes: [
          { from: 'g7', brush: 'red' },
          { from: 'h7', brush: 'red' },
        ],
        text: 'Dušený mat: krále obklopí vlastní figurky. Nemůže uhnout, i kdyby chtěl.',
      },
      {
        id: 'smothered-sac',
        kind: 'move',
        fen: '5r1k/6pp/7N/3Q4/8/8/8/6K1 w - - 0 1',
        accept: ['d5g8'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Obětuj dámu šachem na g8. Přinuť věž zpátky ke králi.',
        success: 'Výborně! Věž musí vzít, jiný tah černý nemá. Tím krále sama zazdí.',
        wrongDefault: 'Hledej šach dámou na g8. Král ji vzít nemůže, jezdec h6 to pole hlídá.',
      },
      {
        id: 'smothered-mate',
        kind: 'move',
        fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 2',
        accept: ['h6f7'],
        completeness: { kind: 'mate' },
        text: 'Král je teď obklopený vlastní věží a pěšci. Dej dušený mat.',
        success: 'Mat! Král nemá jediné volné pole, a jezdce nemá čím vzít.',
        wrongDefault: 'Skoč jezdcem tak, aby dal šach. Král se nemá kam hnout.',
      },
      {
        // Lichess puzzle PC9fl, after 39...Ne2+ 40.Kh2.
        id: 'anastasia-idea',
        kind: 'show',
        fen: '5r1k/1p4p1/p5Qp/2P5/2N1pr2/P3N3/4n1PK/8 b - - 4 40',
        orientation: 'black',
        shapes: [
          { from: 'g1', brush: 'red' },
          { from: 'g3', brush: 'red' },
        ],
        text: 'Anastáziin mat: král stojí u kraje a vedle něj vlastní pěšec. Jezdec mu hlídá únikové pole, věž dá šach po kraji.',
      },
      {
        id: 'anastasia-mate',
        kind: 'move',
        fen: '5r1k/1p4p1/p5Qp/2P5/2N1pr2/P3N3/4n1PK/8 b - - 4 40',
        orientation: 'black',
        accept: ['f4h4'],
        completeness: { kind: 'mate' },
        text: 'Jezdec e2 hlídá pole g1 a g3. Dej mat věží.',
        success: 'Mat! Na g2 stojí bílý pěšec a g1 i g3 hlídá jezdec.',
        wrongDefault: 'Přesuň věž na sloupec h. Král uteče jen tam, kde ho nehlídá jezdec.',
      },
      {
        // Lichess puzzle JupYf, after 38.Nf6 a2.
        id: 'arabian-idea',
        kind: 'show',
        fen: 'r6k/1p3R2/1p2pN1p/8/8/8/p5PP/7K w - - 0 39',
        shapes: [{ from: 'f6', brush: 'blue' }],
        text: 'Arabský mat: jezdec a věž spolupracují v rohu. Věž stojí hned vedle krále a jezdec ji kryje.',
      },
      {
        id: 'arabian-mate',
        kind: 'move',
        fen: 'r6k/1p3R2/1p2pN1p/8/8/8/p5PP/7K w - - 0 39',
        accept: ['f7h7'],
        completeness: { kind: 'mate' },
        text: 'Jezdec f6 hlídá pole g8 a h7. Dej mat věží.',
        success: 'Mat! Věž na h7 kryje jezdec f6. Ten hlídá i pole g8.',
        wrongDefault: 'Postav věž těsně vedle krále. Jezdec f6 ji tam ochrání.',
      },
    ],
    outro: 'Dušený, Anastáziin i arabský mat mají něco společného. Král nemá kam utéct, ještě než přijde šach.',
    practice: [
      { kind: 'puzzles', band: 'lehke', theme: 'mateIn2', count: 5, label: 'Úlohy: mat 2. tahem' },
      { kind: 'puzzles', band: 'lehke', theme: 'anastasiaMate', count: 5, label: 'Úlohy: Anastáziin mat' },
      { kind: 'puzzles', band: 'lehke', theme: 'arabianMate', count: 5, label: 'Úlohy: arabský mat' },
    ],
  },

  {
    id: 'l3-matove-obrazce-2',
    level: 3,
    number: 9,
    title: 'Matové obrazce II',
    steps: [
      {
        // Lichess puzzle kR7T6, after 33...h4.
        id: 'boden-idea',
        kind: 'show',
        fen: '2kr3r/pp1n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/2R3K1 w - - 0 34',
        shapes: [{ from: 'd6', to: 'b8', brush: 'blue' }],
        text: 'Bodenův mat: dva střelci na zkřížených úhlopříčkách. Střelec d6 už hlídá b8 a c7.',
      },
      {
        id: 'boden-sac',
        kind: 'move',
        fen: '2kr3r/pp1n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/2R3K1 w - - 0 34',
        accept: ['c1c6'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Otevři druhému střelci úhlopříčku. Obětuj věž šachem.',
        success: 'Paráda! Po bxc6 je úhlopříčka k c8 volná.',
        wrongDefault: 'Pěšec b7 zavírá úhlopříčku a6–c8. Odlákej ho obětí věže na c6.',
      },
      {
        id: 'boden-mate',
        kind: 'move',
        fen: '2kr3r/p2n1p2/2pBb3/4Pn2/4N2p/3B2p1/P7/6K1 w - - 0 35',
        accept: ['d3a6'],
        completeness: { kind: 'mate' },
        text: 'Úhlopříčka a6–c8 je volná. Dej mat.',
        success: 'Mat! Střelec a6 hlídá b7, střelec d6 hlídá b8 a c7. Na d7 a d8 stojí vlastní figurky.',
        wrongDefault: 'Hledej tah druhým střelcem, který dá šach po úhlopříčce a6–c8.',
      },
      {
        // Lichess puzzle EZTOQ, after 40...Rb8.
        id: 'epaulette-idea',
        kind: 'show',
        fen: 'Qrkr4/8/3pP2p/2p1b1p1/8/3n2P1/5P1K/8 w - - 5 41',
        shapes: [
          { from: 'b8', brush: 'red' },
          { from: 'd8', brush: 'red' },
        ],
        text: 'Epoletový mat: král stojí mezi dvěma vlastními věžemi, jako mezi nárameníky. Šach přijde zepředu.',
      },
      {
        id: 'epaulette-mate',
        kind: 'move',
        fen: 'Qrkr4/8/3pP2p/2p1b1p1/8/3n2P1/5P1K/8 w - - 5 41',
        accept: ['a8c6'],
        completeness: { kind: 'mate' },
        text: 'Černý král c8 stojí mezi svými věžemi. Dej mat dámou.',
        success: 'Mat! Dáma hlídá b7, c7 i d7. Na b8 a d8 stojí vlastní věže.',
        wrongDefault: 'Dej šach dámou zepředu, o dvě pole před krále.',
      },
      {
        // Lichess puzzle 5vSL8, after 39...Be7.
        id: 'sac',
        kind: 'move',
        fen: '7k/1q2b1pp/8/2p5/6r1/P4RN1/1P5P/3Q2K1 w - - 10 40',
        accept: ['d1d8'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Mat na poslední řadě jde i s obětí. Střelec e7 hlídá f8. Odlákej ho dámou.',
        success: 'Výborně! Když střelec vezme dámu, pole f8 zůstane bez stráže.',
        wrongDefault: 'Obětuj dámu šachem na d8. Střelec ji vezme a odejde od f8.',
      },
      {
        id: 'sac-mate',
        kind: 'move',
        fen: '3b3k/1q4pp/8/2p5/6r1/P4RN1/1P5P/6K1 w - - 0 41',
        accept: ['f3f8'],
        completeness: { kind: 'mate' },
        text: 'Poslední řadu už nikdo nehlídá. Dej mat.',
        success: 'Mat! Král za svými pěšci nemá jediné volné pole.',
        wrongDefault: 'Hledej šach věží na poslední řadě. Nikdo ji už nehlídá.',
      },
      {
        id: 'recognise',
        kind: 'choose',
        fen: '2kr3r/p2n1p2/B1pBb3/4Pn2/4N2p/6p1/P7/6K1 b - - 1 35',
        text: 'Takhle skončil první příklad. Jak se ten mat jmenuje?',
        options: [
          { id: 'boden', label: 'Bodenův mat' },
          { id: 'dusen', label: 'Dušený mat' },
          { id: 'epolet', label: 'Epoletový mat' },
        ],
        correct: ['boden'],
        explain: 'Ano! Dva střelci na zkřížených úhlopříčkách dávají Bodenův mat.',
        wrongExplain: {
          dusen: 'Dušený mat dává jezdec, ne dva střelci.',
          epolet: 'U epoletového matu stojí vlastní figurky po obou stranách krále. A šach dává dáma zepředu.',
        },
        wrongDefault: 'Podívej se, kolik střelců tu dává mat a jak vedou jejich úhlopříčky.',
      },
    ],
    outro: 'Matové obrazce se opakují partii za partií. Čím víc jich znáš, tím rychleji je najdeš.',
    practice: [
      { kind: 'puzzles', band: 'lehke', theme: 'backRankMate', count: 5, label: 'Úlohy: mat na poslední řadě' },
      { kind: 'puzzles', band: 'zacatecnik', theme: 'bodenMate', count: 5, label: 'Úlohy: Bodenův mat' },
      { kind: 'puzzles', band: 'lehke', theme: 'epauletteMate', count: 3, label: 'Úlohy: epoletový mat' },
    ],
  },

  {
    id: 'l3-mat-2-tahem',
    level: 3,
    number: 10,
    title: 'Mat 2. tahem',
    steps: [
      {
        // Lichess puzzle eXE9H, after 35.Kg1.
        id: 'order',
        kind: 'show',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P2nP1/1P6/P2r1r2/4R1K1 b - - 3 35',
        orientation: 'black',
        text: 'Mat na dva tahy hledej v pořadí: šachy, pak braní, pak hrozby. Šach soupeři zúží možnosti nejvíc.',
      },
      {
        id: 'check-first',
        kind: 'move',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P2nP1/1P6/P2r1r2/4R1K1 b - - 3 35',
        orientation: 'black',
        accept: ['f4h3'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Hraješ za černé. Nejdřív zkus šachy. Najdi šach jezdcem.',
        success: 'Výborně! Král musí na h1, jiné pole nemá.',
        wrongDefault: 'Hledej šach jezdcem. Zúží to bílému králi pole.',
      },
      {
        id: 'check-mate',
        kind: 'move',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P3P1/1P5n/P2r1r2/4R2K b - - 5 36',
        orientation: 'black',
        accept: ['f2h2'],
        completeness: { kind: 'mate' },
        text: 'Král je teď na h1 bez úniku. Dej mat.',
        success: 'Mat! Věž h2 kryje druhá věž z d2. Pole g1 hlídá jezdec h3.',
        wrongDefault: 'Hledej šach věží na sloupci h. Král h1 nemá kam utéct.',
      },
      {
        // Lichess puzzle gYcwF, after 25.Qxc8.
        id: 'another',
        kind: 'move',
        fen: '2Q1B1k1/1Rp2p2/p2p2q1/8/2P2P2/6P1/P7/5b1K b - - 0 25',
        orientation: 'black',
        accept: ['g6e4'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Zkus to samostatně. Dej mat na dva tahy a začni šachem dámou.',
        success: 'Výborně! Král musí na g1 nebo h2. V obou případech přijde mat.',
        wrongDefault: 'Hledej šach dámou po dlouhé úhlopříčce. Střelec f1 pak pomůže.',
      },
      {
        id: 'another-mate',
        kind: 'move',
        fen: '2Q1B1k1/1Rp2p2/p2p4/8/2P1qP2/6P1/P7/5bK1 b - - 2 26',
        orientation: 'black',
        accept: ['e4g2'],
        completeness: { kind: 'mate' },
        text: 'Bílý král šel na g1. Dej mat.',
        success: 'Mat! Dámu na g2 kryje střelec f1.',
        wrongDefault: 'Hledej šach dámou těsně vedle krále. Střelec f1 ji tam ochrání.',
      },
      {
        // Lichess puzzle JupYf, after 37...a3: a quiet first move.
        id: 'quiet',
        kind: 'move',
        fen: 'r6k/1p3R2/1p2p2p/7N/8/p7/6PP/7K w - - 0 38',
        accept: ['h5f6'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'První tah nemusí být šach. Tady stačí tichý tah jezdcem, který připraví mat.',
        success: 'Paráda! Ať černý táhne cokoli, přijde Vh7 mat. Znáš ho, je to arabský mat.',
        wrongDefault: 'Hledej tah jezdcem, po kterém bude hrozit mat věží na h7.',
      },
      {
        id: 'quiet-mate',
        kind: 'move',
        fen: 'r6k/1p3R2/1p2pN1p/8/8/8/p5PP/7K w - - 0 39',
        accept: ['f7h7'],
        completeness: { kind: 'mate' },
        text: 'Černý táhl pěšcem a2. Dokonči mat.',
        success: 'Mat! Tichý tah jezdcem připravil arabský mat.',
        wrongDefault: 'Postav věž těsně vedle krále. Jezdec f6 ji tam kryje.',
      },
      {
        id: 'order-choose',
        kind: 'choose',
        fen: '5k2/6p1/p1B5/1p2R1p1/2P2nP1/1P6/P2r1r2/4R1K1 b - - 3 35',
        orientation: 'black',
        text: 'Co zkoušíš hledat jako první?',
        options: [
          { id: 'sachy', label: 'Šachy' },
          { id: 'hrozby', label: 'Hrozby' },
          { id: 'nahodne', label: 'Cokoli, na pořadí nezáleží' },
        ],
        correct: ['sachy'],
        explain: 'Ano! Šachy zkoušej první. Když žádný nefunguje, přijde řada na braní a tiché tahy.',
        wrongExplain: {
          hrozby: 'Hrozby zkoušej až po šaších a braní.',
          nahodne: 'Na pořadí záleží. Šach, braní, hrozba — v tomhle pořadí je to rychlejší.',
        },
        wrongDefault: 'Zkoušej tahy v pořadí: šach, braní, hrozba.',
      },
    ],
    outro: 'Šach, braní, hrozba — v tomhle pořadí hledej mat na dva tahy. A nezapomeň na tichý tah.',
    practice: [{ kind: 'puzzles', band: 'lehke', theme: 'mateIn2', count: 5, label: 'Úlohy: mat 2. tahem' }],
  },

  {
    id: 'l3-opozice',
    level: 3,
    number: 11,
    title: 'Opozice',
    steps: [
      {
        // Tablebase: draw (white to move cannot pass the black king).
        id: 'idea',
        kind: 'show',
        fen: '8/4k3/8/4K3/4P3/8/8/8 w - - 0 1',
        shapes: [
          { from: 'e5', brush: 'blue' },
          { from: 'e7', brush: 'red' },
        ],
        text: 'Opozice: králové stojí proti sobě s jedním polem mezi sebou. Kdo je na tahu, musí ustoupit. Opozici má ten druhý.',
      },
      {
        // Tablebase: only Ke7 draws; every other move loses.
        id: 'defend',
        kind: 'move',
        fen: '4k3/8/8/4K3/4P3/8/8/8 b - - 0 1',
        orientation: 'black',
        accept: ['e8e7'],
        completeness: { kind: 'best' },
        text: 'Hraješ za černé. Vezmi si opozici, jinak bílý pěšec projde.',
        success: 'Výborně! Teď musí ustoupit bílý král. Remíza drží.',
        wrongDefault: 'Postav krále přímo proti bílému, s jedním polem mezi sebou.',
      },
      {
        // Tablebase: white to move wins (Kf6).
        id: 'without',
        kind: 'show',
        fen: '8/3k4/8/4K3/4P3/8/8/8 w - - 0 1',
        shapes: [{ from: 'e5', to: 'f6', brush: 'red' }],
        text: 'Kdyby černý král šel na d7, opozici by ztratil. Bílý král pak projde přes f6 a pěšec se promění.',
      },
      {
        // Koncovky: kp-win. Tablebase: only Ke6 wins.
        id: 'attack',
        kind: 'move',
        fen: '4k3/8/3K4/4P3/8/8/8/8 w - - 0 1',
        accept: ['d6e6'],
        completeness: { kind: 'best' },
        text: 'Teď hraješ za bílé. Tvůj král stojí před pěšcem. Vezmi si opozici.',
        success: 'Výborně! Černý král musí ustoupit a tvůj král ho odtlačí. Pěšec projde.',
        wrongDefault: 'Postav krále přímo proti černému, s jedním polem mezi sebou.',
      },
      {
        id: 'who-has-it',
        kind: 'choose',
        fen: '8/8/8/3K4/8/3k4/8/8 w - - 0 1',
        text: 'Bílý je na tahu. Kdo má opozici?',
        options: [
          { id: 'bily', label: 'Bílý' },
          { id: 'cerny', label: 'Černý' },
          { id: 'nikdo', label: 'Nikdo' },
        ],
        correct: ['cerny'],
        explain: 'Ano! Bílý je na tahu a musí ustoupit. Opozici má ten, kdo na tahu není.',
        wrongExplain: {
          bily: 'Opozici má ten, kdo na tahu není. Teď táhne bílý.',
          nikdo: 'Králové stojí proti sobě s jedním polem mezi sebou. Opozici má někdo.',
        },
        wrongDefault: 'Opozici má ten, kdo na tahu není.',
      },
    ],
    outro: 'Opozice rozhoduje v koncovkách krále a pěšce. Kdo ji má, tlačí soupeřova krále dozadu.',
    practice: [
      { kind: 'endgame', id: 'kp-win', label: 'Koncovky: král před pěšcem' },
      { kind: 'endgame', id: 'kp-draw', label: 'Koncovky: udrž remízu' },
    ],
  },

  {
    id: 'l3-ctverec',
    level: 3,
    number: 12,
    title: 'Pravidlo čtverce a závod pěšců',
    steps: [
      {
        // Koncovky: square.
        id: 'idea',
        kind: 'show',
        fen: '8/8/8/8/3k3P/8/8/7K b - - 0 1',
        shapes: [
          { from: 'h4', to: 'h8', brush: 'blue' },
          { from: 'h8', to: 'd8', brush: 'blue' },
          { from: 'd8', to: 'd4', brush: 'blue' },
        ],
        text: 'Pravidlo čtverce: nakresli si od pěšce čtverec až k poslední řadě. Král ve čtverci pěšce dožene.',
      },
      {
        id: 'who-moves',
        kind: 'show',
        fen: '8/8/8/8/3k3P/8/8/7K b - - 0 1',
        text: 'Záleží, kdo je na tahu. Je-li na tahu král, stačí mu do čtverce vkročit. Je-li na tahu pěšec, musí v něm král už stát.',
      },
      {
        // Tablebase: Ke4, Kd5 and Ke5 draw; every other move loses.
        id: 'catch',
        kind: 'move',
        fen: '8/8/8/8/3k3P/8/8/7K b - - 0 1',
        orientation: 'black',
        accept: ['d4e5', 'd4e4', 'd4d5'],
        completeness: { kind: 'best' },
        text: 'Černý je na tahu a král stojí na kraji čtverce. Zůstaň uvnitř a dožeň pěšce.',
        success: 'Výborně! Pěšec ti neuteče, král ho dostihne.',
        wrongDefault: 'Tímhle tahem vypadneš ze čtverce. Pěšec pak proběhne sám.',
      },
      {
        // Tablebase: white to move wins (h5). With black to move it would be a draw.
        id: 'outside',
        kind: 'show',
        fen: '8/8/8/2k5/7P/8/8/7K w - - 0 1',
        shapes: [{ from: 'c5', brush: 'red' }],
        text: 'Tady je na tahu bílý. Král c5 stojí mimo čtverec, a tak pěšce nedožene.',
      },
      {
        // Koncovky: race. Tablebase: only a4 wins.
        id: 'race',
        kind: 'move',
        fen: '8/6k1/8/8/8/8/P5K1/8 w - - 0 1',
        accept: ['a2a4'],
        completeness: { kind: 'best' },
        text: 'Teď máš pěšce ty. Vyraž s ním hned o dvě pole.',
        success: 'Výborně! Čtverec pěšce a4 končí na sloupci e. Král g7 do něj nevkročí.',
        wrongDefault: 'Utíkej pěšcem, a hned o dvě pole. Jinak černý král do čtverce vkročí.',
      },
      {
        // Tablebase: draw.
        id: 'is-inside',
        kind: 'choose',
        fen: '8/8/4k3/8/7P/8/8/7K b - - 0 1',
        text: 'Černý je na tahu. Stihne černý král pěšce dohnat?',
        options: [
          { id: 'ano', label: 'Ano, je ve čtverci' },
          { id: 'ne', label: 'Ne, je mimo čtverec' },
        ],
        correct: ['ano'],
        explain: 'Správně, stihne. Král na e6 je ve čtverci, pěšce dožene.',
        wrongDefault: 'Nakresli si čtverec od h4 k poslední řadě a podívej se, kde stojí král.',
      },
    ],
    outro: 'Pravidlo čtverce ti hned řekne, jestli má cenu pěšce honit. Nebo radši utíkat s vlastním.',
    practice: [
      { kind: 'endgame', id: 'square', label: 'Koncovky: pravidlo čtverce' },
      { kind: 'endgame', id: 'race', label: 'Koncovky: utíkej s pěšcem' },
    ],
  },

  {
    id: 'l3-zkouska',
    level: 3,
    number: 13,
    title: 'Zkouška úrovně 3',
    test: {
      passScore: 9,
      badge: 'l3',
      failOutro: 'Tentokrát to nevyšlo. Zopakuj si lekce, kde to drhlo, a zkus to znovu.',
    },
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/8/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Zkouška úrovně 3! Čeká tě 11 úloh. Na každou máš jen jeden pokus a žádnou nápovědu.',
      },
      {
        // Lichess puzzle vECBy, after 14.Nxc4.
        id: 't-guard',
        kind: 'move',
        fen: '1r1q1rk1/p4ppp/b1pb1n2/4p3/2N5/1P2P1P1/PB3PBP/R2Q1RK1 b - - 0 14',
        orientation: 'black',
        accept: ['a6c4'],
        completeness: { kind: 'best' },
        text: 'Hraješ za černé. Odstraň obránce a vyhraj figurku.',
        success: 'Správně! Jezdec c4 hlídal střelce b2. Po bxc4 vezmeš Vxb2.',
        wrongDefault: 'Jezdec c4 hlídá střelce b2. Vezmi ho střelcem a6.',
      },
      {
        // Lichess puzzle exQ1C, as in l3-pretizeni.
        id: 't-overload',
        kind: 'choose',
        fen: '2r1r3/5kp1/p4n1p/P2p4/6P1/P1B1R2P/2P5/2K1R3 b - - 2 26',
        text: 'Která bílá figurka je přetížená?',
        options: [
          { id: 'e3', square: 'e3' },
          { id: 'c3', square: 'c3' },
          { id: 'e1', square: 'e1' },
        ],
        correct: ['e3'],
        explain: 'Věž e3 hlídá střelce c3 i věž e1 najednou.',
        wrongDefault: 'Hledej figurku, která hlídá dvě věci najednou.',
      },
      {
        // Lichess puzzle 0Msbe, after 53...f4.
        id: 't-lure',
        kind: 'move',
        fen: '8/1P4k1/2K5/8/5p2/8/1r4p1/6R1 w - - 0 54',
        accept: ['g1g2'],
        completeness: { kind: 'best' },
        text: 'Odlákej věž, která hlídá cestu tvému pěšci.',
        success: 'Správně! Po Vxg2 se pěšec promění b8D.',
        wrongDefault: 'Vezmi pěšce g2 se šachem. Černá věž ho vezme a odejde ze sloupce b.',
      },
      {
        // Lichess puzzle 54H4F, after 42...Kg6.
        id: 't-attract',
        kind: 'move',
        fen: '8/2p4R/1pPq2k1/6p1/3N1p2/4P1P1/5P1P/6K1 w - - 1 43',
        accept: ['h7h6'],
        completeness: { kind: 'best' },
        text: 'Nalákej krále na pole vidličky a vyhraj dámu.',
        success: 'Správně! Po Kxh6 přijde vidlička Jf5+ na krále a dámu.',
        wrongDefault: 'Obětuj věž šachem na h6. Po Kxh6 přijde vidlička Jf5+.',
      },
      {
        // Lichess puzzle dmyAF, after 44...Rxc3.
        id: 't-skewer',
        kind: 'move',
        fen: '8/p4R2/2k5/8/5BKP/2r5/6P1/5r2 w - - 0 45',
        accept: ['f7c7'],
        completeness: { kind: 'best' },
        text: 'Najdi rentgen a vyhraj věž.',
        success: 'Správně! Král musí ze sloupce c a věž c3 padne.',
        wrongDefault: 'Dej šach věží po sloupci c. Za králem stojí věž c3.',
      },
      {
        // Lichess puzzle AmID9, after 11.Bxb5.
        id: 't-intermezzo',
        kind: 'move',
        fen: 'rn2kb1r/p1q1ppp1/2p2np1/1B6/3P4/4P3/PPQ2PPP/RNB1K2R b KQkq - 0 11',
        orientation: 'black',
        accept: ['c7a5'],
        completeness: { kind: 'best' },
        text: 'Hraješ za černé. Bílý vzal na b5. Neber zpátky hned, zahraj mezitah.',
        success: 'Správně! Po šachu Da5+ vezmeš střelce b5. Dáma c7 už nebude na ráně.',
        wrongDefault: 'Po cxb5 by bílá dáma vzala tvoji dámu c7. Nejdřív dej šach Da5+.',
      },
      {
        // Lichess puzzle PtGwo, the final position after 28...Rh2#.
        id: 't-pattern',
        kind: 'choose',
        fen: 'r5k1/1p1P2bp/pQ4p1/4p3/4P1n1/2N2nP1/P6r/2RR3K w - - 3 29',
        text: 'Jak se tenhle mat jmenuje?',
        options: [
          { id: 'arab', label: 'Arabský mat' },
          { id: 'boden', label: 'Bodenův mat' },
          { id: 'dusen', label: 'Dušený mat' },
        ],
        correct: ['arab'],
        explain: 'Věž stojí vedle krále v rohu a kryje ji jezdec f3. To je arabský mat.',
        wrongDefault: 'Podívej se, které figurky dávají mat: věž vedle krále a jezdec.',
      },
      {
        // Lichess puzzle KDAZF, after 31.Bxc5.
        id: 't-mate2a',
        kind: 'move',
        fen: '1k5r/pp1q2p1/5p2/2BP4/2P5/PP3N2/5PK1/R2Q4 b - - 0 31',
        orientation: 'black',
        accept: ['d7h3'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Hraješ za černé. Dej mat 2. tahem. Zahraj první tah.',
        success: 'Správně! Po Kg1 přijde Dh1 mat.',
        wrongDefault: 'Začni šachem dámou na h3. Po Kg1 dá dáma mat na h1.',
      },
      {
        // Lichess puzzle 5vufz, after 9...a6.
        id: 't-mate2b',
        kind: 'move',
        fen: 'r1bn1b1r/1p1kpppp/p4n2/1N6/2B5/4PN2/PP3PPP/R1B1K2R w KQ - 0 10',
        accept: ['f3e5'],
        completeness: { kind: 'best', marginCp: 0 },
        text: 'Dej mat 2. tahem. Zahraj první tah.',
        success: 'Správně! Po Ke8 přijde Jc7 mat.',
        wrongDefault: 'Začni šachem jezdcem na e5. Po Ke8 dá druhý jezdec mat na c7.',
      },
      {
        id: 't-opposition',
        kind: 'choose',
        fen: '8/8/4k3/8/4K3/8/8/8 b - - 0 1',
        text: 'Černý je na tahu. Kdo má opozici?',
        options: [
          { id: 'bily', label: 'Bílý' },
          { id: 'cerny', label: 'Černý' },
          { id: 'nikdo', label: 'Nikdo' },
        ],
        correct: ['bily'],
        explain: 'Černý je na tahu a musí ustoupit. Opozici má bílý.',
        wrongDefault: 'Opozici má ten, kdo na tahu není.',
      },
      {
        // Tablebase: white to move wins (a5).
        id: 't-square',
        kind: 'choose',
        fen: '8/8/5k2/8/P7/8/8/7K w - - 0 1',
        text: 'Bílý je na tahu. Stihne černý král pěšce dohnat?',
        options: [
          { id: 'ano', label: 'Ano, je ve čtverci' },
          { id: 'ne', label: 'Ne, je mimo čtverec' },
        ],
        correct: ['ne'],
        explain: 'Na tahu je pěšec a král f6 stojí mimo čtverec. Pěšec proběhne.',
        wrongDefault: 'Nakresli si čtverec od a4 k poslední řadě. Na tahu je pěšec.',
      },
    ],
    outro: 'Zkouška je za tebou! Odznak je tvůj a můžeš si vytisknout diplom.',
    practice: [{ kind: 'play', level: 4, label: 'Zahraj si partii proti silnějšímu soupeři' }],
  },
];
