/**
 * Level 1 — Úplný začátečník, lessons 1–7: the board and every piece (docs/phase-21-plan.md,
 * curriculum). Checked by `npm run check:lessons`: FENs, accepted moves (complete),
 * collect limits, text lint. Texts: informal „ty“, short sentences, one idea per step,
 * Czech piece names; a piece's first mention uses the `{piece}` placeholder so the child
 * also hears how it looks in their animal set (text.ts).
 */
import type { Lesson } from './types';

const EMPTY = '8/8/8/8/8/8/8/8 w - - 0 1';

export const LEVEL1: readonly Lesson[] = [
  {
    id: 'l1-sachovnice',
    level: 1,
    number: 1,
    title: 'Šachovnice a cíl hry',
    steps: [
      {
        id: 'board',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        text: 'Ahoj! Tohle je šachovnice. Má 64 polí. Světlá a tmavá pole se pořád střídají.',
      },
      {
        id: 'h1',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'h1', brush: 'green' }],
        text: 'Šachovnici vždycky polož tak, aby vpravo dole bylo světlé pole. Pamatuj si: bílé pole vpravo dole.',
      },
      {
        id: 'names',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        shapes: [
          { from: 'a1', to: 'h1', brush: 'blue' },
          { from: 'a1', to: 'a8', brush: 'blue' },
        ],
        text: 'Sloupce mají písmena od a do h. Řady mají čísla od 1 do 8.',
      },
      {
        id: 'e4',
        kind: 'show',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'e4', brush: 'green' }],
        text: 'Každé pole má jméno. Nejdřív písmeno sloupce, potom číslo řady. Tohle pole se jmenuje e4.',
      },
      {
        id: 'name-it',
        kind: 'choose',
        fen: EMPTY,
        diagram: true,
        shapes: [{ from: 'd5', brush: 'green' }],
        text: 'Jak se jmenuje označené pole?',
        options: [
          { id: 'e5', label: 'e5' },
          { id: 'd5', label: 'd5' },
          { id: 'd4', label: 'd4' },
        ],
        correct: ['d5'],
        explain: 'Ano! Sloupec d, řada 5. To je pole d5.',
        wrongExplain: {
          e5: 'Řada 5 sedí. Ale podívej se ještě jednou na písmeno sloupce.',
          d4: 'Sloupec d sedí. Ale podívej se ještě jednou na číslo řady.',
        },
        wrongDefault: 'Písmeno najdeš dole pod sloupcem. Číslo najdeš vlevo vedle řady.',
      },
      {
        id: 'find-it',
        kind: 'choose',
        fen: EMPTY,
        diagram: true,
        text: 'Teď najdi pole f3. Klikni na něj.',
        options: [
          { id: 'f6', square: 'f6' },
          { id: 'c3', square: 'c3' },
          { id: 'f3', square: 'f3' },
        ],
        correct: ['f3'],
        explain: 'Přesně tak, tohle je f3!',
        wrongExplain: {
          f6: 'Tohle je f6. Sloupec sedí, ale řada 3 je níž.',
          c3: 'Tohle je c3. Řada sedí, ale sloupec f je víc vpravo.',
        },
        wrongDefault: 'Najdi nejdřív sloupec f. Potom v něm řadu 3.',
      },
      {
        id: 'goal',
        kind: 'show',
        fen: '7k/6Q1/6K1/8/8/8/8/8 b - - 0 1',
        shapes: [{ from: 'h8', brush: 'red' }],
        text: 'Cílem hry je dát soupeřovu králi mat. Černý král je napadený a nemá kam utéct. To je mat a hra končí.',
      },
      {
        id: 'no-capture',
        kind: 'show',
        fen: '7k/6Q1/6K1/8/8/8/8/8 b - - 0 1',
        text: 'Krále nikdo nikdy nebere. Hra skončí matem dřív, než by na to došlo.',
      },
    ],
    outro: 'Znáš šachovnici i cíl hry. Teď poznáš figurky, jednu po druhé.',
  },

  {
    id: 'l1-vez',
    level: 1,
    number: 2,
    title: 'Věž',
    piece: 'r',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd8', brush: 'green' },
          { from: 'd4', to: 'd1', brush: 'green' },
          { from: 'd4', to: 'a4', brush: 'green' },
          { from: 'd4', to: 'h4', brush: 'green' },
        ],
        text: 'Tohle je {věž}. Jezdí rovně: dopředu, dozadu, doleva a doprava.',
      },
      {
        id: 'distance',
        kind: 'show',
        fen: '8/8/8/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd5', brush: 'green' },
          { from: 'd4', to: 'h4', brush: 'green' },
        ],
        text: 'V jednom tahu jede věž jen jedním směrem. Může ujet jedno pole, nebo klidně celou šachovnici.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/R7 w - - 0 1',
        diagram: true,
        piece: 'a1',
        stars: ['a6', 'f6', 'f8'],
        text: 'Teď ty! Seber věží všechny hvězdy. Stačí na hvězdu dojet.',
        success: 'Paráda! Všechny hvězdy jsou tvoje.',
      },
      {
        id: 'no-jump',
        kind: 'show',
        fen: '8/8/3P4/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd5', brush: 'green' },
          { from: 'd6', brush: 'red' },
        ],
        text: 'Věž nepřeskakuje. Když jí v cestě stojí figurka, musí zastavit před ní.',
      },
      {
        id: 'around',
        kind: 'collect',
        fen: '8/8/8/1P6/8/8/1R2P3/8 w - - 0 1',
        diagram: true,
        piece: 'b2',
        stars: ['b8'],
        maxMoves: 3,
        text: 'Hvězda je schovaná za tvou figurkou. Najdi cestu kolem. Stačí ti 3 tahy.',
        success: 'Výborně! Když rovná cesta nevede, věž jede oklikou.',
      },
      {
        id: 'capture',
        kind: 'show',
        fen: '8/3n4/8/8/3R4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'd4', to: 'd7', brush: 'green' }],
        text: 'Věž bere stejně, jak jezdí. Stoupne si na pole soupeřovy figurky. Ta pak ze šachovnice zmizí.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: 'k7/8/1p6/8/3R2p1/8/8/7K w - - 0 1',
        movable: ['d4'],
        accept: ['d4g4'],
        completeness: { kind: 'lands', square: 'g4' },
        text: 'Vezmi věží černou figurku. Jen na jednu z nich věž dosáhne.',
        success: 'Výborně! Věž bere rovně, stejně jak jezdí.',
        wrongDefault: 'Tím nic nevezmeš. Najdi figurku, ke které vede rovná cesta.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '8/8/8/8/P7/8/8/R7 w - - 0 1',
        diagram: true,
        text: 'Na které označené pole dojede věž jedním tahem?',
        options: [
          { id: 'a6', square: 'a6' },
          { id: 'c3', square: 'c3' },
          { id: 'f1', square: 'f1' },
        ],
        correct: ['f1'],
        explain: 'Ano! Na f1 vede rovná a volná cesta.',
        wrongExplain: {
          a6: 'Na a6 ne. V cestě stojí tvoje figurka a věž nepřeskakuje.',
          c3: 'Na c3 ne. Cesta tam nevede rovně a věž jezdí jen rovně.',
        },
        wrongDefault: 'Věž jezdí jen rovně a nepřeskakuje.',
      },
    ],
    outro: 'Umíš věž! Jezdí rovně, nepřeskakuje a bere tam, kam jezdí.',
  },

  {
    id: 'l1-strelec',
    level: 1,
    number: 3,
    title: 'Střelec',
    piece: 'b',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3B4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'a7', brush: 'green' },
          { from: 'd4', to: 'h8', brush: 'green' },
          { from: 'd4', to: 'a1', brush: 'green' },
          { from: 'd4', to: 'g1', brush: 'green' },
        ],
        text: 'Tohle je {střelec}. Jezdí šikmo, daleko nebo jen o jedno pole.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/2B5 w - - 0 1',
        diagram: true,
        piece: 'c1',
        stars: ['e3', 'g5', 'h4'],
        text: 'Seber střelcem všechny hvězdy.',
        success: 'Paráda! Střelec to zvládl samými šikmými tahy.',
      },
      {
        id: 'colour',
        kind: 'show',
        fen: '8/8/8/8/8/8/8/2B5 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'a3', brush: 'blue' },
          { from: 'e3', brush: 'blue' },
          { from: 'g5', brush: 'blue' },
        ],
        text: 'Tenhle střelec stojí na tmavém poli. Proto chodí jen po tmavých polích, pořád.',
      },
      {
        id: 'never',
        kind: 'choose',
        fen: '8/8/8/8/8/8/8/2B5 w - - 0 1',
        diagram: true,
        stars: ['e4'],
        text: 'Dojde tenhle střelec někdy na hvězdu? Klidně i za víc tahů.',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nikdy. Hvězda je na světlém poli a tenhle střelec chodí jen po tmavých.',
        wrongDefault: 'Podívej se na barvu pole pod hvězdou. A potom na barvu pole pod střelcem.',
      },
      {
        id: 'same',
        kind: 'choose',
        fen: '8/8/8/8/8/8/8/5B2 w - - 0 1',
        diagram: true,
        stars: ['b5'],
        text: 'A tenhle střelec? Dojde na hvězdu?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ano'],
        explain: 'Ano! Střelec i hvězda jsou na světlých polích. Stačí jeden tah.',
        wrongDefault: 'Podívej se na barvu pole pod hvězdou i pod střelcem. Je stejná?',
      },
      {
        id: 'take',
        kind: 'move',
        fen: 'k7/8/8/6p1/2p5/8/8/2B3K1 w - - 0 1',
        movable: ['c1'],
        accept: ['c1g5'],
        completeness: { kind: 'lands', square: 'g5' },
        text: 'Střelec bere šikmo, stejně jak jezdí. Vezmi střelcem černou figurku.',
        success: 'Výborně! Na druhou figurku tvůj střelec nedosáhne. Stojí na světlém poli.',
        wrongDefault: 'Tím nic nevezmeš. Najdi figurku, ke které vede šikmá cesta.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '8/8/8/8/8/4P3/8/2B5 w - - 0 1',
        diagram: true,
        text: 'Na které označené pole dojede střelec jedním tahem?',
        options: [
          { id: 'g5', square: 'g5' },
          { id: 'c5', square: 'c5' },
          { id: 'a3', square: 'a3' },
        ],
        correct: ['a3'],
        explain: 'Ano! Na a3 vede volná šikmá cesta.',
        wrongExplain: {
          g5: 'Na g5 ne. V cestě stojí tvoje figurka a střelec nepřeskakuje.',
          c5: 'Na c5 ne. To je rovně a střelec jezdí jen šikmo.',
        },
        wrongDefault: 'Střelec jezdí jen šikmo a nepřeskakuje.',
      },
    ],
    outro: 'Umíš střelce! Jezdí šikmo, nepřeskakuje a zůstává na polích své barvy.',
  },

  {
    id: 'l1-dama',
    level: 1,
    number: 4,
    title: 'Dáma',
    piece: 'q',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3Q4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd8', brush: 'green' },
          { from: 'd4', to: 'd1', brush: 'green' },
          { from: 'd4', to: 'a4', brush: 'green' },
          { from: 'd4', to: 'h4', brush: 'green' },
          { from: 'd4', to: 'a7', brush: 'green' },
          { from: 'd4', to: 'h8', brush: 'green' },
          { from: 'd4', to: 'a1', brush: 'green' },
          { from: 'd4', to: 'g1', brush: 'green' },
        ],
        text: 'Tohle je {dáma}. Jezdí rovně jako věž i šikmo jako střelec.',
      },
      {
        id: 'not-there',
        kind: 'choose',
        fen: '8/8/8/8/3Q4/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Dáma umí hodně, ale ne všechno. Na které označené pole jedním tahem nedojede?',
        options: [
          { id: 'd8', square: 'd8' },
          { id: 'e6', square: 'e6' },
          { id: 'g7', square: 'g7' },
        ],
        correct: ['e6'],
        explain: 'Správně. Na e6 to není rovně ani šikmo. Tam dáma nedojede.',
        wrongExplain: {
          d8: 'Na d8 dojede. To je rovně, jako věž.',
          g7: 'Na g7 dojede. To je šikmo, jako střelec.',
        },
        wrongDefault: 'Dáma jezdí jen rovně a šikmo.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/Q7 w - - 0 1',
        diagram: true,
        piece: 'a1',
        stars: ['d4', 'd8', 'h4'],
        maxMoves: 3,
        text: 'Seber dámou všechny hvězdy. Zvládneš to na 3 tahy?',
        success: 'Paráda! Rovně i šikmo, přesně jak dáma umí.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: 'k7/8/5r2/8/8/8/1Q6/6K1 w - - 0 1',
        movable: ['b2'],
        accept: ['b2f6'],
        completeness: { kind: 'lands', square: 'f6' },
        text: 'Vezmi dámou černou věž.',
        success: 'Výborně! Dáma bere rovně i šikmo, jak jezdí.',
        wrongDefault: 'Tím věž nevezmeš. Najdi k ní rovnou nebo šikmou cestu.',
      },
      {
        id: 'way-out',
        kind: 'collect',
        fen: '8/8/8/8/8/8/2PPP3/3Q4 w - - 0 1',
        diagram: true,
        piece: 'd1',
        stars: ['h5', 'a4'],
        maxMoves: 4,
        text: 'Tvoje figurky stojí dámě v cestě. Najdi cestu ven a seber hvězdy.',
        success: 'Výborně! Dáma taky nepřeskakuje, ale cestu si najde.',
      },
    ],
    outro: 'Umíš dámu! Jezdí rovně i šikmo, jako věž a střelec dohromady.',
  },

  {
    id: 'l1-kral',
    level: 1,
    number: 5,
    title: 'Král',
    piece: 'k',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/4K3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: (['d3', 'e3', 'f3', 'd4', 'f4', 'd5', 'e5', 'f5'] as const).map((s) => ({ from: s, brush: 'green' as const })),
        text: 'Tohle je {král}. Chodí jen o jedno pole, ale kterýmkoli směrem.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/4K3 w - - 0 1',
        diagram: true,
        piece: 'e1',
        stars: ['e3', 'g3'],
        maxMoves: 4,
        text: 'Seber králem obě hvězdy. Pomalu, vždycky jen o jedno pole.',
        success: 'Paráda! Král je pomalý, ale dojde všude.',
      },
      {
        id: 'kings',
        kind: 'show',
        fen: '8/8/4k3/8/4K3/8/8/8 w - - 0 1',
        shapes: [
          { from: 'd5', brush: 'red' },
          { from: 'e5', brush: 'red' },
          { from: 'f5', brush: 'red' },
        ],
        text: 'Dva králové nikdy nestojí vedle sebe. Na červená pole tvůj král nesmí.',
      },
      {
        id: 'where',
        kind: 'move',
        fen: '8/8/4k3/8/4K3/8/8/8 w - - 0 1',
        movable: ['e4'],
        accept: ['e4d3', 'e4e3', 'e4f3', 'e4d4', 'e4f4'],
        completeness: { kind: 'legal', from: 'e4' },
        text: 'Táhni svým králem na pole, kam smí.',
        success: 'Ano, tam král smí.',
        wrongDefault: 'Tam král nedojde. Chodí jen o jedno pole.',
      },
      {
        id: 'which',
        kind: 'choose',
        fen: '8/8/8/8/3K1k2/8/8/8 w - - 0 1',
        text: 'Na které označené pole smí bílý král?',
        options: [
          { id: 'e4', square: 'e4' },
          { id: 'c5', square: 'c5' },
          { id: 'e5', square: 'e5' },
        ],
        correct: ['c5'],
        explain: 'Ano! Pole c5 je daleko od černého krále.',
        wrongExplain: {
          e4: 'Na e4 ne. Stál by hned vedle černého krále.',
          e5: 'Na e5 ne. Stál by šikmo vedle černého krále.',
        },
        wrongDefault: 'Králové nikdy nestojí vedle sebe.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '7k/8/8/3r4/4K3/8/8/8 w - - 0 1',
        movable: ['e4'],
        accept: ['e4d5'],
        completeness: { kind: 'lands', square: 'd5' },
        text: 'Král taky bere, o jedno pole. Vezmi králem černou věž.',
        success: 'Výborně! Věž stála hned vedle, a tak ji král vzal.',
        wrongDefault: 'Tím věž nevezmeš. Stoupni si králem na její pole.',
      },
    ],
    outro: 'Umíš krále! Chodí o jedno pole a nikdy nestojí vedle druhého krále.',
  },

  {
    id: 'l1-jezdec',
    level: 1,
    number: 6,
    title: 'Jezdec',
    piece: 'n',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: (['c6', 'e6', 'f5', 'f3', 'e2', 'c2', 'b3', 'b5'] as const).map((s) => ({ from: s, brush: 'green' as const })),
        text: 'Tohle je {jezdec}. Skáče do tvaru písmene L: dvě pole rovně a jedno do strany.',
      },
      {
        id: 'one-jump',
        kind: 'show',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'd6', brush: 'blue' },
          { from: 'd6', to: 'e6', brush: 'blue' },
          { from: 'e6', brush: 'green' },
        ],
        text: 'Tady je jeden skok. Dvě pole nahoru, jedno doprava. Jezdec přistane rovnou na e6.',
      },
      {
        id: 'jumps',
        kind: 'show',
        fen: '8/8/8/8/8/8/PPPP4/1N6 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'a3', brush: 'green' },
          { from: 'c3', brush: 'green' },
        ],
        text: 'Jezdec jako jediný přeskakuje. Nevadí mu, co stojí mezi.',
      },
      {
        id: 'stars',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/1N6 w - - 0 1',
        diagram: true,
        piece: 'b1',
        stars: ['c3', 'e4', 'f6'],
        text: 'Seber jezdcem všechny hvězdy.',
        success: 'Paráda! Hop, hop, hop.',
      },
      {
        id: 'colour',
        kind: 'show',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: (['c6', 'e6', 'f5', 'f3', 'e2', 'c2', 'b3', 'b5'] as const).map((s) => ({ from: s, brush: 'green' as const })),
        text: 'Jezdec stojí na tmavém poli. Po každém skoku přistane na poli opačné barvy.',
      },
      {
        id: 'detour',
        kind: 'collect',
        fen: '8/8/8/8/8/8/8/N7 w - - 0 1',
        diagram: true,
        piece: 'a1',
        stars: ['b2'],
        text: 'Hvězda je hned vedle jezdce. Stejně k ní musí skákat oklikou!',
        success: 'Výborně! Blízko neznamená pro jezdce snadno.',
      },
      {
        id: 'over',
        kind: 'show',
        fen: '8/8/4p3/3p4/3N4/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'd4', to: 'e6', brush: 'green' },
          { from: 'd5', brush: 'blue' },
        ],
        text: 'Jezdec bere jen tam, kam doskočí. Figurku, kterou přeskočí, nevezme.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '6k1/8/8/3r4/2p5/2N5/8/6K1 w - - 0 1',
        movable: ['c3'],
        accept: ['c3d5'],
        completeness: { kind: 'lands', square: 'd5' },
        text: 'Vezmi jezdcem černou věž.',
        success: 'Hop a věž je tvoje!',
        wrongDefault: 'Tím věž nevezmeš. Najdi skok do L, který skončí na věži.',
      },
    ],
    outro: 'Umíš jezdce! Skáče do L, přeskakuje a bere jen tam, kam doskočí.',
  },

  {
    id: 'l1-pesec',
    level: 1,
    number: 7,
    title: 'Pěšec',
    piece: 'p',
    steps: [
      {
        id: 'intro',
        kind: 'show',
        fen: '8/8/8/8/8/4P3/8/8 w - - 0 1',
        diagram: true,
        shapes: [{ from: 'e3', to: 'e4', brush: 'green' }],
        text: 'Tohle je {pěšec}. Chodí rovně dopředu, jen o jedno pole.',
      },
      {
        id: 'first',
        kind: 'show',
        fen: '8/8/8/8/8/8/4P3/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'e2', to: 'e3', brush: 'green' },
          { from: 'e2', to: 'e4', brush: 'green' },
        ],
        text: 'Když pěšec ještě netáhl, smí jít o jedno, nebo o dvě pole. Vybere si.',
      },
      {
        id: 'double',
        kind: 'move',
        fen: '4k3/8/8/8/8/8/4P3/4K3 w - - 0 1',
        movable: ['e2'],
        accept: ['e2e4'],
        completeness: { kind: 'lands', square: 'e4', from: 'e2' },
        text: 'Posuň pěšce co nejdál dopředu.',
        success: 'Výborně! O dvě pole smí jen při svém prvním tahu.',
        wrong: { e2e3: 'To je jen o jedno pole. Z prvního pole smí pěšec i o dvě.' },
        wrongDefault: 'Pěšec jde rovně dopředu. Z prvního pole smí i o dvě.',
      },
      {
        id: 'no-back',
        kind: 'show',
        fen: '8/8/8/8/4P3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'e4', to: 'e5', brush: 'green' },
          { from: 'e4', to: 'e3', brush: 'red' },
        ],
        text: 'Pěšec nikdy necouvá. Jde jen dopředu, směrem k soupeři.',
      },
      {
        id: 'capture',
        kind: 'show',
        fen: '8/8/8/3n1r2/4P3/8/8/8 w - - 0 1',
        diagram: true,
        shapes: [
          { from: 'e4', to: 'd5', brush: 'green' },
          { from: 'e4', to: 'f5', brush: 'green' },
        ],
        text: 'Pěšec bere jinak, než chodí. Bere šikmo dopředu, o jedno pole.',
      },
      {
        id: 'take',
        kind: 'move',
        fen: '6k1/8/8/3r1n2/4P3/8/8/6K1 w - - 0 1',
        movable: ['e4'],
        accept: ['e4d5', 'e4f5'],
        completeness: { kind: 'captures', from: 'e4' },
        text: 'Vezmi pěšcem černou figurku.',
        success: 'Výborně! Pěšec bere šikmo dopředu.',
        wrong: { e4e5: 'Tím nic nevezmeš. Rovně pěšec nebere, bere jen šikmo dopředu.' },
        wrongDefault: 'Pěšec bere šikmo dopředu, o jedno pole.',
      },
      {
        id: 'blocked',
        kind: 'choose',
        fen: '8/8/8/4p3/4P3/8/8/8 w - - 0 1',
        diagram: true,
        text: 'Bílý pěšec stojí proti černému. Může bílý pěšec táhnout?',
        options: [
          { id: 'ano', label: 'Ano' },
          { id: 'ne', label: 'Ne' },
        ],
        correct: ['ne'],
        explain: 'Správně, nemůže. Rovně mu stojí v cestě černý pěšec. Šikmo před ním nic není.',
        wrongDefault: 'Rovně pěšec nebere. A šikmo před ním žádná figurka nestojí.',
      },
    ],
    outro: 'Umíš pěšce! Teď už znáš všechny figurky. Zkus si zahrát první partii.',
    practice: [
      { kind: 'play', level: 1, label: 'Zahraj si partii proti nejslabšímu soupeři' },
      { kind: 'puzzles', band: 'zacatecnik', theme: 'oneMove', count: 5, label: 'Úlohy na jeden tah (začátečník)' },
    ],
  },
];
